// Generated by CIRCT firtool-1.62.0
module divider(
  input         clock,
                reset,
  input  [31:0] io_src1,
                io_src2,
  input  [3:0]  io_op,
  output [31:0] io_res,
  input         io_inst_valid,
  output        io_busy
);

  reg  [5:0]   cnt;
  reg          en;
  reg  [31:0]  ab_scr1;
  reg  [31:0]  ab_scr2_stage1;
  reg          res_sign_stage1;
  reg  [3:0]   op_stage1;
  reg  [4:0]   H1_src1;
  reg  [4:0]   H1_src2;
  reg  [31:0]  ab_scr2_stage2;
  reg          res_sign_stage2;
  reg  [3:0]   op_stage2;
  reg  [64:0]  quo;
  wire [31:0]  res_temp = op_stage2[0] ? quo[64:33] : quo[31:0];
  wire         sel = quo[63:32] >= ab_scr2_stage2;
  wire [31:0]  _quo_T_4 = sel ? 32'(quo[63:32] - ab_scr2_stage2) : quo[63:32];
  wire [31:0]  _H1_src1_T_6 = 32'(~io_src1 + 32'h1);
  wire [30:0]  _H1_src1_T_8 =
    (io_op == 4'h5 | io_op == 4'h4) & io_src1[31] ? _H1_src1_T_6[31:1] : io_src1[31:1];
  wire [7:0]   _GEN =
    {{_H1_src1_T_8[10:7], _H1_src1_T_8[14:13]} & 6'h33, 2'h0}
    | {_H1_src1_T_8[14:11], _H1_src1_T_8[18:15]} & 8'h33;
  wire [18:0]  _GEN_0 =
    {_H1_src1_T_8[4:3],
     _H1_src1_T_8[6:5],
     _H1_src1_T_8[8:7],
     _GEN,
     _H1_src1_T_8[18:17],
     _H1_src1_T_8[20:19],
     _H1_src1_T_8[22]} & 19'h55555;
  wire [3:0]   _GEN_1 = _GEN_0[18:15] | {_H1_src1_T_8[6:5], _H1_src1_T_8[8:7]} & 4'h5;
  wire [7:0]   _GEN_2 = _GEN_0[14:7] | _GEN & 8'h55;
  wire [3:0]   _GEN_3 =
    {_GEN_0[2:0], 1'h0} | {_H1_src1_T_8[22:21], _H1_src1_T_8[24:23]} & 4'h5;
  wire [31:0]  _H1_src2_T_6 = 32'(~io_src2 + 32'h1);
  wire [30:0]  _H1_src2_T_8 =
    (io_op == 4'h5 | io_op == 4'h4) & io_src2[31] ? _H1_src2_T_6[31:1] : io_src2[31:1];
  wire [7:0]   _GEN_4 =
    {{_H1_src2_T_8[10:7], _H1_src2_T_8[14:13]} & 6'h33, 2'h0}
    | {_H1_src2_T_8[14:11], _H1_src2_T_8[18:15]} & 8'h33;
  wire [18:0]  _GEN_5 =
    {_H1_src2_T_8[4:3],
     _H1_src2_T_8[6:5],
     _H1_src2_T_8[8:7],
     _GEN_4,
     _H1_src2_T_8[18:17],
     _H1_src2_T_8[20:19],
     _H1_src2_T_8[22]} & 19'h55555;
  wire [3:0]   _GEN_6 = _GEN_5[18:15] | {_H1_src2_T_8[6:5], _H1_src2_T_8[8:7]} & 4'h5;
  wire [7:0]   _GEN_7 = _GEN_5[14:7] | _GEN_4 & 8'h55;
  wire [3:0]   _GEN_8 =
    {_GEN_5[2:0], 1'h0} | {_H1_src2_T_8[22:21], _H1_src2_T_8[24:23]} & 4'h5;
  wire         _cnt_init_T = H1_src1 <= H1_src2;
  wire [4:0]   _cnt_init_T_5 = _cnt_init_T ? 5'(5'(H1_src2 + 5'h1) - H1_src1) : 5'h0;
  wire [4:0]   _H1_src1_T_91 = _H1_src1_T_8[1] ? 5'h1D : {4'hF, ~(_H1_src1_T_8[0])};
  wire [4:0]   _H1_src1_T_92 = _H1_src1_T_8[2] ? 5'h1C : _H1_src1_T_91;
  wire [4:0]   _H1_src1_T_93 = _H1_src1_T_8[3] ? 5'h1B : _H1_src1_T_92;
  wire [4:0]   _H1_src1_T_94 = _GEN_1[3] ? 5'h1A : _H1_src1_T_93;
  wire [4:0]   _H1_src1_T_95 = _GEN_1[2] ? 5'h19 : _H1_src1_T_94;
  wire [4:0]   _H1_src1_T_96 = _GEN_1[1] ? 5'h18 : _H1_src1_T_95;
  wire [4:0]   _H1_src1_T_97 = _GEN_1[0] ? 5'h17 : _H1_src1_T_96;
  wire [4:0]   _H1_src1_T_98 = _GEN_2[7] ? 5'h16 : _H1_src1_T_97;
  wire [4:0]   _H1_src1_T_99 = _GEN_2[6] ? 5'h15 : _H1_src1_T_98;
  wire [4:0]   _H1_src1_T_100 = _GEN_2[5] ? 5'h14 : _H1_src1_T_99;
  wire [4:0]   _H1_src1_T_101 = _GEN_2[4] ? 5'h13 : _H1_src1_T_100;
  wire [4:0]   _H1_src1_T_102 = _GEN_2[3] ? 5'h12 : _H1_src1_T_101;
  wire [4:0]   _H1_src1_T_103 = _GEN_2[2] ? 5'h11 : _H1_src1_T_102;
  wire [4:0]   _H1_src1_T_104 = _GEN_2[1] ? 5'h10 : _H1_src1_T_103;
  wire [4:0]   _H1_src1_T_105 = _GEN_2[0] ? 5'hF : _H1_src1_T_104;
  wire [4:0]   _H1_src1_T_106 = _GEN[1] ? 5'hE : _H1_src1_T_105;
  wire [4:0]   _H1_src1_T_107 = _GEN_0[5] | _H1_src1_T_8[17] ? 5'hD : _H1_src1_T_106;
  wire [4:0]   _H1_src1_T_108 = _H1_src1_T_8[18] ? 5'hC : _H1_src1_T_107;
  wire [4:0]   _H1_src1_T_109 = _H1_src1_T_8[19] ? 5'hB : _H1_src1_T_108;
  wire [4:0]   _H1_src1_T_110 = _GEN_3[3] ? 5'hA : _H1_src1_T_109;
  wire [4:0]   _H1_src1_T_111 = _GEN_3[2] ? 5'h9 : _H1_src1_T_110;
  wire [4:0]   _H1_src1_T_112 = _GEN_3[1] ? 5'h8 : _H1_src1_T_111;
  wire [4:0]   _H1_src1_T_113 = _GEN_3[0] ? 5'h7 : _H1_src1_T_112;
  wire [4:0]   _H1_src1_T_114 = _H1_src1_T_8[24] ? 5'h6 : _H1_src1_T_113;
  wire [4:0]   _H1_src1_T_115 = _H1_src1_T_8[25] ? 5'h5 : _H1_src1_T_114;
  wire [4:0]   _H1_src1_T_116 = _H1_src1_T_8[26] ? 5'h4 : _H1_src1_T_115;
  wire [4:0]   _H1_src1_T_117 = _H1_src1_T_8[27] ? 5'h3 : _H1_src1_T_116;
  wire [4:0]   _H1_src1_T_118 = _H1_src1_T_8[28] ? 5'h2 : _H1_src1_T_117;
  wire [4:0]   _H1_src1_T_119 = _H1_src1_T_8[29] ? 5'h1 : _H1_src1_T_118;
  wire [4:0]   _H1_src2_T_91 = _H1_src2_T_8[1] ? 5'h1D : {4'hF, ~(_H1_src2_T_8[0])};
  wire [4:0]   _H1_src2_T_92 = _H1_src2_T_8[2] ? 5'h1C : _H1_src2_T_91;
  wire [4:0]   _H1_src2_T_93 = _H1_src2_T_8[3] ? 5'h1B : _H1_src2_T_92;
  wire [4:0]   _H1_src2_T_94 = _GEN_6[3] ? 5'h1A : _H1_src2_T_93;
  wire [4:0]   _H1_src2_T_95 = _GEN_6[2] ? 5'h19 : _H1_src2_T_94;
  wire [4:0]   _H1_src2_T_96 = _GEN_6[1] ? 5'h18 : _H1_src2_T_95;
  wire [4:0]   _H1_src2_T_97 = _GEN_6[0] ? 5'h17 : _H1_src2_T_96;
  wire [4:0]   _H1_src2_T_98 = _GEN_7[7] ? 5'h16 : _H1_src2_T_97;
  wire [4:0]   _H1_src2_T_99 = _GEN_7[6] ? 5'h15 : _H1_src2_T_98;
  wire [4:0]   _H1_src2_T_100 = _GEN_7[5] ? 5'h14 : _H1_src2_T_99;
  wire [4:0]   _H1_src2_T_101 = _GEN_7[4] ? 5'h13 : _H1_src2_T_100;
  wire [4:0]   _H1_src2_T_102 = _GEN_7[3] ? 5'h12 : _H1_src2_T_101;
  wire [4:0]   _H1_src2_T_103 = _GEN_7[2] ? 5'h11 : _H1_src2_T_102;
  wire [4:0]   _H1_src2_T_104 = _GEN_7[1] ? 5'h10 : _H1_src2_T_103;
  wire [4:0]   _H1_src2_T_105 = _GEN_7[0] ? 5'hF : _H1_src2_T_104;
  wire [4:0]   _H1_src2_T_106 = _GEN_4[1] ? 5'hE : _H1_src2_T_105;
  wire [4:0]   _H1_src2_T_107 = _GEN_5[5] | _H1_src2_T_8[17] ? 5'hD : _H1_src2_T_106;
  wire [4:0]   _H1_src2_T_108 = _H1_src2_T_8[18] ? 5'hC : _H1_src2_T_107;
  wire [4:0]   _H1_src2_T_109 = _H1_src2_T_8[19] ? 5'hB : _H1_src2_T_108;
  wire [4:0]   _H1_src2_T_110 = _GEN_8[3] ? 5'hA : _H1_src2_T_109;
  wire [4:0]   _H1_src2_T_111 = _GEN_8[2] ? 5'h9 : _H1_src2_T_110;
  wire [4:0]   _H1_src2_T_112 = _GEN_8[1] ? 5'h8 : _H1_src2_T_111;
  wire [4:0]   _H1_src2_T_113 = _GEN_8[0] ? 5'h7 : _H1_src2_T_112;
  wire [4:0]   _H1_src2_T_114 = _H1_src2_T_8[24] ? 5'h6 : _H1_src2_T_113;
  wire [4:0]   _H1_src2_T_115 = _H1_src2_T_8[25] ? 5'h5 : _H1_src2_T_114;
  wire [4:0]   _H1_src2_T_116 = _H1_src2_T_8[26] ? 5'h4 : _H1_src2_T_115;
  wire [4:0]   _H1_src2_T_117 = _H1_src2_T_8[27] ? 5'h3 : _H1_src2_T_116;
  wire [4:0]   _H1_src2_T_118 = _H1_src2_T_8[28] ? 5'h2 : _H1_src2_T_117;
  wire [4:0]   _H1_src2_T_119 = _H1_src2_T_8[29] ? 5'h1 : _H1_src2_T_118;
  wire [5:0]   offset =
    _cnt_init_T ? 6'(6'({1'h0, H1_src1} - 6'h20) - {1'h0, H1_src2}) : 6'h21;
  wire [127:0] _quo_T_9 = {96'h0, ab_scr1} << offset;
  always @(posedge clock) begin
    if (reset) begin
      cnt <= 6'h0;
      en <= 1'h0;
      ab_scr1 <= 32'h0;
      ab_scr2_stage1 <= 32'h0;
      res_sign_stage1 <= 1'h0;
      op_stage1 <= 4'h0;
      H1_src1 <= 5'h0;
      H1_src2 <= 5'h0;
      ab_scr2_stage2 <= 32'h0;
      res_sign_stage2 <= 1'h0;
      op_stage2 <= 4'h0;
      quo <= 65'h0;
    end
    else if (|cnt) begin
      cnt <= 6'(cnt - 6'h1);
      quo <= {_quo_T_4, quo[31:0], sel};
    end
    else begin
      if (en)
        cnt <= {1'h0, _cnt_init_T_5};
      en <= io_op[2] & io_inst_valid;
      ab_scr1 <=
        (io_op == 4'h5 | io_op == 4'h4) & io_src1[31] ? 32'(~io_src1 + 32'h1) : io_src1;
      ab_scr2_stage1 <=
        (io_op == 4'h5 | io_op == 4'h4) & io_src2[31] ? 32'(~io_src2 + 32'h1) : io_src2;
      res_sign_stage1 <= ~(io_op[1]) & (~(io_op[0]) & io_src2[31] ^ io_src1[31]);
      op_stage1 <= io_op;
      H1_src1 <= _H1_src1_T_8[30] ? 5'h0 : _H1_src1_T_119;
      H1_src2 <= _H1_src2_T_8[30] ? 5'h0 : _H1_src2_T_119;
      ab_scr2_stage2 <= ab_scr2_stage1;
      res_sign_stage2 <= res_sign_stage1;
      op_stage2 <= op_stage1;
      if (en)
        quo <= _quo_T_9[64:0];
    end
  end // always @(posedge)
  assign io_res = ~(op_stage2[1]) & res_sign_stage2 ? 32'(~res_temp + 32'h1) : res_temp;
  assign io_busy = |cnt;
endmodule

