// Generated by CIRCT firtool-1.62.0
module FetchQueue(
  input         clock,
                reset,
                io_in_pack_inst_valid_0,
                io_in_pack_inst_valid_1,
  input  [31:0] io_in_pack_pc_0,
                io_in_pack_pc_1,
  input         io_in_pack_pred_jump_0,
                io_in_pack_pred_jump_1,
  input  [31:0] io_in_pack_pred_npc_0,
                io_in_pack_pred_npc_1,
  input  [7:0]  io_in_pack_exception_0,
                io_in_pack_exception_1,
  input  [1:0]  io_in_pack_br_cnt_0,
                io_in_pack_br_cnt_1,
  input  [31:0] io_in_pack_inst_0,
                io_in_pack_inst_1,
  output        io_out_pack_inst_valid_0,
                io_out_pack_inst_valid_1,
  output [31:0] io_out_pack_pc_0,
                io_out_pack_pc_1,
  output        io_out_pack_pred_jump_0,
                io_out_pack_pred_jump_1,
  output [31:0] io_out_pack_pred_npc_0,
                io_out_pack_pred_npc_1,
  output [7:0]  io_out_pack_exception_0,
                io_out_pack_exception_1,
  output [1:0]  io_out_pack_br_cnt_0,
                io_out_pack_br_cnt_1,
  output [31:0] io_out_pack_inst_0,
                io_out_pack_inst_1,
  output        io_out_valid,
  input         io_flush,
                io_stall,
  output        io_full
);

  reg         queue_inst_valid_0_0;
  reg         queue_inst_valid_0_1;
  reg         queue_inst_valid_0_2;
  reg         queue_inst_valid_0_3;
  reg         queue_inst_valid_0_4;
  reg         queue_inst_valid_0_5;
  reg         queue_inst_valid_0_6;
  reg         queue_inst_valid_0_7;
  reg         queue_inst_valid_1_0;
  reg         queue_inst_valid_1_1;
  reg         queue_inst_valid_1_2;
  reg         queue_inst_valid_1_3;
  reg         queue_inst_valid_1_4;
  reg         queue_inst_valid_1_5;
  reg         queue_inst_valid_1_6;
  reg         queue_inst_valid_1_7;
  reg  [31:0] queue_pc_0_0;
  reg  [31:0] queue_pc_0_1;
  reg  [31:0] queue_pc_0_2;
  reg  [31:0] queue_pc_0_3;
  reg  [31:0] queue_pc_0_4;
  reg  [31:0] queue_pc_0_5;
  reg  [31:0] queue_pc_0_6;
  reg  [31:0] queue_pc_0_7;
  reg  [31:0] queue_pc_1_0;
  reg  [31:0] queue_pc_1_1;
  reg  [31:0] queue_pc_1_2;
  reg  [31:0] queue_pc_1_3;
  reg  [31:0] queue_pc_1_4;
  reg  [31:0] queue_pc_1_5;
  reg  [31:0] queue_pc_1_6;
  reg  [31:0] queue_pc_1_7;
  reg         queue_pred_jump_0_0;
  reg         queue_pred_jump_0_1;
  reg         queue_pred_jump_0_2;
  reg         queue_pred_jump_0_3;
  reg         queue_pred_jump_0_4;
  reg         queue_pred_jump_0_5;
  reg         queue_pred_jump_0_6;
  reg         queue_pred_jump_0_7;
  reg         queue_pred_jump_1_0;
  reg         queue_pred_jump_1_1;
  reg         queue_pred_jump_1_2;
  reg         queue_pred_jump_1_3;
  reg         queue_pred_jump_1_4;
  reg         queue_pred_jump_1_5;
  reg         queue_pred_jump_1_6;
  reg         queue_pred_jump_1_7;
  reg  [31:0] queue_pred_npc_0_0;
  reg  [31:0] queue_pred_npc_0_1;
  reg  [31:0] queue_pred_npc_0_2;
  reg  [31:0] queue_pred_npc_0_3;
  reg  [31:0] queue_pred_npc_0_4;
  reg  [31:0] queue_pred_npc_0_5;
  reg  [31:0] queue_pred_npc_0_6;
  reg  [31:0] queue_pred_npc_0_7;
  reg  [31:0] queue_pred_npc_1_0;
  reg  [31:0] queue_pred_npc_1_1;
  reg  [31:0] queue_pred_npc_1_2;
  reg  [31:0] queue_pred_npc_1_3;
  reg  [31:0] queue_pred_npc_1_4;
  reg  [31:0] queue_pred_npc_1_5;
  reg  [31:0] queue_pred_npc_1_6;
  reg  [31:0] queue_pred_npc_1_7;
  reg  [7:0]  queue_exception_0_0;
  reg  [7:0]  queue_exception_0_1;
  reg  [7:0]  queue_exception_0_2;
  reg  [7:0]  queue_exception_0_3;
  reg  [7:0]  queue_exception_0_4;
  reg  [7:0]  queue_exception_0_5;
  reg  [7:0]  queue_exception_0_6;
  reg  [7:0]  queue_exception_0_7;
  reg  [7:0]  queue_exception_1_0;
  reg  [7:0]  queue_exception_1_1;
  reg  [7:0]  queue_exception_1_2;
  reg  [7:0]  queue_exception_1_3;
  reg  [7:0]  queue_exception_1_4;
  reg  [7:0]  queue_exception_1_5;
  reg  [7:0]  queue_exception_1_6;
  reg  [7:0]  queue_exception_1_7;
  reg  [1:0]  queue_br_cnt_0_0;
  reg  [1:0]  queue_br_cnt_0_1;
  reg  [1:0]  queue_br_cnt_0_2;
  reg  [1:0]  queue_br_cnt_0_3;
  reg  [1:0]  queue_br_cnt_0_4;
  reg  [1:0]  queue_br_cnt_0_5;
  reg  [1:0]  queue_br_cnt_0_6;
  reg  [1:0]  queue_br_cnt_0_7;
  reg  [1:0]  queue_br_cnt_1_0;
  reg  [1:0]  queue_br_cnt_1_1;
  reg  [1:0]  queue_br_cnt_1_2;
  reg  [1:0]  queue_br_cnt_1_3;
  reg  [1:0]  queue_br_cnt_1_4;
  reg  [1:0]  queue_br_cnt_1_5;
  reg  [1:0]  queue_br_cnt_1_6;
  reg  [1:0]  queue_br_cnt_1_7;
  reg  [31:0] queue_inst_0_0;
  reg  [31:0] queue_inst_0_1;
  reg  [31:0] queue_inst_0_2;
  reg  [31:0] queue_inst_0_3;
  reg  [31:0] queue_inst_0_4;
  reg  [31:0] queue_inst_0_5;
  reg  [31:0] queue_inst_0_6;
  reg  [31:0] queue_inst_0_7;
  reg  [31:0] queue_inst_1_0;
  reg  [31:0] queue_inst_1_1;
  reg  [31:0] queue_inst_1_2;
  reg  [31:0] queue_inst_1_3;
  reg  [31:0] queue_inst_1_4;
  reg  [31:0] queue_inst_1_5;
  reg  [31:0] queue_inst_1_6;
  reg  [31:0] queue_inst_1_7;
  reg  [7:0]  head;
  reg  [7:0]  tail;
  reg         cur;
  wire [7:0]  _io_full_T_3 = {tail[6:0], tail[7]} & head;
  wire [31:0] _GEN = head[0] ? queue_inst_0_0 : 32'h0;
  wire [31:0] _GEN_0 = head[1] ? queue_inst_0_1 : 32'h0;
  wire [31:0] _GEN_1 = head[2] ? queue_inst_0_2 : 32'h0;
  wire [31:0] _GEN_2 = head[3] ? queue_inst_0_3 : 32'h0;
  wire [31:0] _GEN_3 = head[4] ? queue_inst_0_4 : 32'h0;
  wire [31:0] _GEN_4 = head[5] ? queue_inst_0_5 : 32'h0;
  wire [31:0] _GEN_5 = head[6] ? queue_inst_0_6 : 32'h0;
  wire [31:0] _GEN_6 = head[7] ? queue_inst_0_7 : 32'h0;
  wire [1:0]  _GEN_7 = head[0] ? queue_br_cnt_0_0 : 2'h0;
  wire [1:0]  _GEN_8 = head[1] ? queue_br_cnt_0_1 : 2'h0;
  wire [1:0]  _GEN_9 = head[2] ? queue_br_cnt_0_2 : 2'h0;
  wire [1:0]  _GEN_10 = head[3] ? queue_br_cnt_0_3 : 2'h0;
  wire [1:0]  _GEN_11 = head[4] ? queue_br_cnt_0_4 : 2'h0;
  wire [1:0]  _GEN_12 = head[5] ? queue_br_cnt_0_5 : 2'h0;
  wire [1:0]  _GEN_13 = head[6] ? queue_br_cnt_0_6 : 2'h0;
  wire [1:0]  _GEN_14 = head[7] ? queue_br_cnt_0_7 : 2'h0;
  wire [7:0]  _GEN_15 = head[0] ? queue_exception_0_0 : 8'h0;
  wire [7:0]  _GEN_16 = head[1] ? queue_exception_0_1 : 8'h0;
  wire [7:0]  _GEN_17 = head[2] ? queue_exception_0_2 : 8'h0;
  wire [7:0]  _GEN_18 = head[3] ? queue_exception_0_3 : 8'h0;
  wire [7:0]  _GEN_19 = head[4] ? queue_exception_0_4 : 8'h0;
  wire [7:0]  _GEN_20 = head[5] ? queue_exception_0_5 : 8'h0;
  wire [7:0]  _GEN_21 = head[6] ? queue_exception_0_6 : 8'h0;
  wire [7:0]  _GEN_22 = head[7] ? queue_exception_0_7 : 8'h0;
  wire [31:0] _GEN_23 = head[0] ? queue_pred_npc_0_0 : 32'h0;
  wire [31:0] _GEN_24 = head[1] ? queue_pred_npc_0_1 : 32'h0;
  wire [31:0] _GEN_25 = head[2] ? queue_pred_npc_0_2 : 32'h0;
  wire [31:0] _GEN_26 = head[3] ? queue_pred_npc_0_3 : 32'h0;
  wire [31:0] _GEN_27 = head[4] ? queue_pred_npc_0_4 : 32'h0;
  wire [31:0] _GEN_28 = head[5] ? queue_pred_npc_0_5 : 32'h0;
  wire [31:0] _GEN_29 = head[6] ? queue_pred_npc_0_6 : 32'h0;
  wire [31:0] _GEN_30 = head[7] ? queue_pred_npc_0_7 : 32'h0;
  wire [31:0] _GEN_31 = head[0] ? queue_pc_0_0 : 32'h0;
  wire [31:0] _GEN_32 = head[1] ? queue_pc_0_1 : 32'h0;
  wire [31:0] _GEN_33 = head[2] ? queue_pc_0_2 : 32'h0;
  wire [31:0] _GEN_34 = head[3] ? queue_pc_0_3 : 32'h0;
  wire [31:0] _GEN_35 = head[4] ? queue_pc_0_4 : 32'h0;
  wire [31:0] _GEN_36 = head[5] ? queue_pc_0_5 : 32'h0;
  wire [31:0] _GEN_37 = head[6] ? queue_pc_0_6 : 32'h0;
  wire [31:0] _GEN_38 = head[7] ? queue_pc_0_7 : 32'h0;
  wire [31:0] _GEN_39 = head[0] ? queue_inst_1_0 : 32'h0;
  wire [31:0] _GEN_40 = head[1] ? queue_inst_1_1 : 32'h0;
  wire [31:0] _GEN_41 = head[2] ? queue_inst_1_2 : 32'h0;
  wire [31:0] _GEN_42 = head[3] ? queue_inst_1_3 : 32'h0;
  wire [31:0] _GEN_43 = head[4] ? queue_inst_1_4 : 32'h0;
  wire [31:0] _GEN_44 = head[5] ? queue_inst_1_5 : 32'h0;
  wire [31:0] _GEN_45 = head[6] ? queue_inst_1_6 : 32'h0;
  wire [31:0] _GEN_46 = head[7] ? queue_inst_1_7 : 32'h0;
  wire [1:0]  _GEN_47 = head[0] ? queue_br_cnt_1_0 : 2'h0;
  wire [1:0]  _GEN_48 = head[1] ? queue_br_cnt_1_1 : 2'h0;
  wire [1:0]  _GEN_49 = head[2] ? queue_br_cnt_1_2 : 2'h0;
  wire [1:0]  _GEN_50 = head[3] ? queue_br_cnt_1_3 : 2'h0;
  wire [1:0]  _GEN_51 = head[4] ? queue_br_cnt_1_4 : 2'h0;
  wire [1:0]  _GEN_52 = head[5] ? queue_br_cnt_1_5 : 2'h0;
  wire [1:0]  _GEN_53 = head[6] ? queue_br_cnt_1_6 : 2'h0;
  wire [1:0]  _GEN_54 = head[7] ? queue_br_cnt_1_7 : 2'h0;
  wire [7:0]  _GEN_55 = head[0] ? queue_exception_1_0 : 8'h0;
  wire [7:0]  _GEN_56 = head[1] ? queue_exception_1_1 : 8'h0;
  wire [7:0]  _GEN_57 = head[2] ? queue_exception_1_2 : 8'h0;
  wire [7:0]  _GEN_58 = head[3] ? queue_exception_1_3 : 8'h0;
  wire [7:0]  _GEN_59 = head[4] ? queue_exception_1_4 : 8'h0;
  wire [7:0]  _GEN_60 = head[5] ? queue_exception_1_5 : 8'h0;
  wire [7:0]  _GEN_61 = head[6] ? queue_exception_1_6 : 8'h0;
  wire [7:0]  _GEN_62 = head[7] ? queue_exception_1_7 : 8'h0;
  wire [31:0] _GEN_63 = head[0] ? queue_pred_npc_1_0 : 32'h0;
  wire [31:0] _GEN_64 = head[1] ? queue_pred_npc_1_1 : 32'h0;
  wire [31:0] _GEN_65 = head[2] ? queue_pred_npc_1_2 : 32'h0;
  wire [31:0] _GEN_66 = head[3] ? queue_pred_npc_1_3 : 32'h0;
  wire [31:0] _GEN_67 = head[4] ? queue_pred_npc_1_4 : 32'h0;
  wire [31:0] _GEN_68 = head[5] ? queue_pred_npc_1_5 : 32'h0;
  wire [31:0] _GEN_69 = head[6] ? queue_pred_npc_1_6 : 32'h0;
  wire [31:0] _GEN_70 = head[7] ? queue_pred_npc_1_7 : 32'h0;
  wire [31:0] _GEN_71 = head[0] ? queue_pc_1_0 : 32'h0;
  wire [31:0] _GEN_72 = head[1] ? queue_pc_1_1 : 32'h0;
  wire [31:0] _GEN_73 = head[2] ? queue_pc_1_2 : 32'h0;
  wire [31:0] _GEN_74 = head[3] ? queue_pc_1_3 : 32'h0;
  wire [31:0] _GEN_75 = head[4] ? queue_pc_1_4 : 32'h0;
  wire [31:0] _GEN_76 = head[5] ? queue_pc_1_5 : 32'h0;
  wire [31:0] _GEN_77 = head[6] ? queue_pc_1_6 : 32'h0;
  wire [31:0] _GEN_78 = head[7] ? queue_pc_1_7 : 32'h0;
  wire        _io_out_valid_T = (tail & head) == 8'h0;
  wire        io_out_valid_0 = _io_out_valid_T & ~io_stall;
  wire [7:0]  _GEN_79 = cur ? {tail[6:0], tail[7]} : tail;
  wire        to_insert_inst_valid_0 =
    io_in_pack_inst_valid_0 ? io_in_pack_inst_valid_0 : io_in_pack_inst_valid_1;
  wire [31:0] to_insert_pc_0 =
    io_in_pack_inst_valid_0 ? io_in_pack_pc_0 : io_in_pack_pc_1;
  wire        to_insert_pred_jump_0 =
    io_in_pack_inst_valid_0 ? io_in_pack_pred_jump_0 : io_in_pack_pred_jump_1;
  wire [31:0] to_insert_pred_npc_0 =
    io_in_pack_inst_valid_0 ? io_in_pack_pred_npc_0 : io_in_pack_pred_npc_1;
  wire [7:0]  to_insert_exception_0 =
    io_in_pack_inst_valid_0 ? io_in_pack_exception_0 : io_in_pack_exception_1;
  wire [1:0]  to_insert_br_cnt_0 =
    io_in_pack_inst_valid_0 ? io_in_pack_br_cnt_0 : io_in_pack_br_cnt_1;
  wire [31:0] to_insert_inst_0 =
    io_in_pack_inst_valid_0 ? io_in_pack_inst_0 : io_in_pack_inst_1;
  wire        _GEN_80 = tail[0] & ~cur;
  wire        _GEN_81 = tail[0] & cur;
  wire        _GEN_82 = tail[1] & ~cur;
  wire        _GEN_83 = tail[1] & cur;
  wire        _GEN_84 = tail[2] & ~cur;
  wire        _GEN_85 = tail[2] & cur;
  wire        _GEN_86 = tail[3] & ~cur;
  wire        _GEN_87 = tail[3] & cur;
  wire        _GEN_88 = tail[4] & ~cur;
  wire        _GEN_89 = tail[4] & cur;
  wire        _GEN_90 = tail[5] & ~cur;
  wire        _GEN_91 = tail[5] & cur;
  wire        _GEN_92 = tail[6] & ~cur;
  wire        _GEN_93 = tail[6] & cur;
  wire        _GEN_94 = tail[7] & ~cur;
  wire        _GEN_95 = tail[7] & cur;
  wire [1:0]  in_count =
    2'({1'h0, io_in_pack_inst_valid_0} + {1'h0, io_in_pack_inst_valid_1});
  wire        _GEN_96 = in_count == 2'h1;
  wire        _GEN_97 = in_count == 2'h2;
  always @(posedge clock) begin
    if (reset) begin
      queue_inst_valid_0_0 <= 1'h0;
      queue_inst_valid_0_1 <= 1'h0;
      queue_inst_valid_0_2 <= 1'h0;
      queue_inst_valid_0_3 <= 1'h0;
      queue_inst_valid_0_4 <= 1'h0;
      queue_inst_valid_0_5 <= 1'h0;
      queue_inst_valid_0_6 <= 1'h0;
      queue_inst_valid_0_7 <= 1'h0;
      queue_inst_valid_1_0 <= 1'h0;
      queue_inst_valid_1_1 <= 1'h0;
      queue_inst_valid_1_2 <= 1'h0;
      queue_inst_valid_1_3 <= 1'h0;
      queue_inst_valid_1_4 <= 1'h0;
      queue_inst_valid_1_5 <= 1'h0;
      queue_inst_valid_1_6 <= 1'h0;
      queue_inst_valid_1_7 <= 1'h0;
      queue_pc_0_0 <= 32'h0;
      queue_pc_0_1 <= 32'h0;
      queue_pc_0_2 <= 32'h0;
      queue_pc_0_3 <= 32'h0;
      queue_pc_0_4 <= 32'h0;
      queue_pc_0_5 <= 32'h0;
      queue_pc_0_6 <= 32'h0;
      queue_pc_0_7 <= 32'h0;
      queue_pc_1_0 <= 32'h0;
      queue_pc_1_1 <= 32'h0;
      queue_pc_1_2 <= 32'h0;
      queue_pc_1_3 <= 32'h0;
      queue_pc_1_4 <= 32'h0;
      queue_pc_1_5 <= 32'h0;
      queue_pc_1_6 <= 32'h0;
      queue_pc_1_7 <= 32'h0;
      queue_pred_jump_0_0 <= 1'h0;
      queue_pred_jump_0_1 <= 1'h0;
      queue_pred_jump_0_2 <= 1'h0;
      queue_pred_jump_0_3 <= 1'h0;
      queue_pred_jump_0_4 <= 1'h0;
      queue_pred_jump_0_5 <= 1'h0;
      queue_pred_jump_0_6 <= 1'h0;
      queue_pred_jump_0_7 <= 1'h0;
      queue_pred_jump_1_0 <= 1'h0;
      queue_pred_jump_1_1 <= 1'h0;
      queue_pred_jump_1_2 <= 1'h0;
      queue_pred_jump_1_3 <= 1'h0;
      queue_pred_jump_1_4 <= 1'h0;
      queue_pred_jump_1_5 <= 1'h0;
      queue_pred_jump_1_6 <= 1'h0;
      queue_pred_jump_1_7 <= 1'h0;
      queue_pred_npc_0_0 <= 32'h0;
      queue_pred_npc_0_1 <= 32'h0;
      queue_pred_npc_0_2 <= 32'h0;
      queue_pred_npc_0_3 <= 32'h0;
      queue_pred_npc_0_4 <= 32'h0;
      queue_pred_npc_0_5 <= 32'h0;
      queue_pred_npc_0_6 <= 32'h0;
      queue_pred_npc_0_7 <= 32'h0;
      queue_pred_npc_1_0 <= 32'h0;
      queue_pred_npc_1_1 <= 32'h0;
      queue_pred_npc_1_2 <= 32'h0;
      queue_pred_npc_1_3 <= 32'h0;
      queue_pred_npc_1_4 <= 32'h0;
      queue_pred_npc_1_5 <= 32'h0;
      queue_pred_npc_1_6 <= 32'h0;
      queue_pred_npc_1_7 <= 32'h0;
      queue_exception_0_0 <= 8'h0;
      queue_exception_0_1 <= 8'h0;
      queue_exception_0_2 <= 8'h0;
      queue_exception_0_3 <= 8'h0;
      queue_exception_0_4 <= 8'h0;
      queue_exception_0_5 <= 8'h0;
      queue_exception_0_6 <= 8'h0;
      queue_exception_0_7 <= 8'h0;
      queue_exception_1_0 <= 8'h0;
      queue_exception_1_1 <= 8'h0;
      queue_exception_1_2 <= 8'h0;
      queue_exception_1_3 <= 8'h0;
      queue_exception_1_4 <= 8'h0;
      queue_exception_1_5 <= 8'h0;
      queue_exception_1_6 <= 8'h0;
      queue_exception_1_7 <= 8'h0;
      queue_br_cnt_0_0 <= 2'h0;
      queue_br_cnt_0_1 <= 2'h0;
      queue_br_cnt_0_2 <= 2'h0;
      queue_br_cnt_0_3 <= 2'h0;
      queue_br_cnt_0_4 <= 2'h0;
      queue_br_cnt_0_5 <= 2'h0;
      queue_br_cnt_0_6 <= 2'h0;
      queue_br_cnt_0_7 <= 2'h0;
      queue_br_cnt_1_0 <= 2'h0;
      queue_br_cnt_1_1 <= 2'h0;
      queue_br_cnt_1_2 <= 2'h0;
      queue_br_cnt_1_3 <= 2'h0;
      queue_br_cnt_1_4 <= 2'h0;
      queue_br_cnt_1_5 <= 2'h0;
      queue_br_cnt_1_6 <= 2'h0;
      queue_br_cnt_1_7 <= 2'h0;
      queue_inst_0_0 <= 32'h0;
      queue_inst_0_1 <= 32'h0;
      queue_inst_0_2 <= 32'h0;
      queue_inst_0_3 <= 32'h0;
      queue_inst_0_4 <= 32'h0;
      queue_inst_0_5 <= 32'h0;
      queue_inst_0_6 <= 32'h0;
      queue_inst_0_7 <= 32'h0;
      queue_inst_1_0 <= 32'h0;
      queue_inst_1_1 <= 32'h0;
      queue_inst_1_2 <= 32'h0;
      queue_inst_1_3 <= 32'h0;
      queue_inst_1_4 <= 32'h0;
      queue_inst_1_5 <= 32'h0;
      queue_inst_1_6 <= 32'h0;
      queue_inst_1_7 <= 32'h0;
      head <= 8'h1;
      tail <= 8'h1;
      cur <= 1'h0;
    end
    else begin
      if (~(|_io_full_T_3)) begin
        if (_GEN_96) begin
          if (_GEN_80) begin
            queue_inst_valid_0_0 <= to_insert_inst_valid_0;
            queue_pc_0_0 <= to_insert_pc_0;
            queue_pred_jump_0_0 <= to_insert_pred_jump_0;
            queue_pred_npc_0_0 <= to_insert_pred_npc_0;
            queue_exception_0_0 <= to_insert_exception_0;
            queue_br_cnt_0_0 <= to_insert_br_cnt_0;
            queue_inst_0_0 <= to_insert_inst_0;
          end
          if (_GEN_82) begin
            queue_inst_valid_0_1 <= to_insert_inst_valid_0;
            queue_pc_0_1 <= to_insert_pc_0;
            queue_pred_jump_0_1 <= to_insert_pred_jump_0;
            queue_pred_npc_0_1 <= to_insert_pred_npc_0;
            queue_exception_0_1 <= to_insert_exception_0;
            queue_br_cnt_0_1 <= to_insert_br_cnt_0;
            queue_inst_0_1 <= to_insert_inst_0;
          end
          if (_GEN_84) begin
            queue_inst_valid_0_2 <= to_insert_inst_valid_0;
            queue_pc_0_2 <= to_insert_pc_0;
            queue_pred_jump_0_2 <= to_insert_pred_jump_0;
            queue_pred_npc_0_2 <= to_insert_pred_npc_0;
            queue_exception_0_2 <= to_insert_exception_0;
            queue_br_cnt_0_2 <= to_insert_br_cnt_0;
            queue_inst_0_2 <= to_insert_inst_0;
          end
          if (_GEN_86) begin
            queue_inst_valid_0_3 <= to_insert_inst_valid_0;
            queue_pc_0_3 <= to_insert_pc_0;
            queue_pred_jump_0_3 <= to_insert_pred_jump_0;
            queue_pred_npc_0_3 <= to_insert_pred_npc_0;
            queue_exception_0_3 <= to_insert_exception_0;
            queue_br_cnt_0_3 <= to_insert_br_cnt_0;
            queue_inst_0_3 <= to_insert_inst_0;
          end
          if (_GEN_88) begin
            queue_inst_valid_0_4 <= to_insert_inst_valid_0;
            queue_pc_0_4 <= to_insert_pc_0;
            queue_pred_jump_0_4 <= to_insert_pred_jump_0;
            queue_pred_npc_0_4 <= to_insert_pred_npc_0;
            queue_exception_0_4 <= to_insert_exception_0;
            queue_br_cnt_0_4 <= to_insert_br_cnt_0;
            queue_inst_0_4 <= to_insert_inst_0;
          end
          if (_GEN_90) begin
            queue_inst_valid_0_5 <= to_insert_inst_valid_0;
            queue_pc_0_5 <= to_insert_pc_0;
            queue_pred_jump_0_5 <= to_insert_pred_jump_0;
            queue_pred_npc_0_5 <= to_insert_pred_npc_0;
            queue_exception_0_5 <= to_insert_exception_0;
            queue_br_cnt_0_5 <= to_insert_br_cnt_0;
            queue_inst_0_5 <= to_insert_inst_0;
          end
          if (_GEN_92) begin
            queue_inst_valid_0_6 <= to_insert_inst_valid_0;
            queue_pc_0_6 <= to_insert_pc_0;
            queue_pred_jump_0_6 <= to_insert_pred_jump_0;
            queue_pred_npc_0_6 <= to_insert_pred_npc_0;
            queue_exception_0_6 <= to_insert_exception_0;
            queue_br_cnt_0_6 <= to_insert_br_cnt_0;
            queue_inst_0_6 <= to_insert_inst_0;
          end
          if (_GEN_94) begin
            queue_inst_valid_0_7 <= to_insert_inst_valid_0;
            queue_pc_0_7 <= to_insert_pc_0;
            queue_pred_jump_0_7 <= to_insert_pred_jump_0;
            queue_pred_npc_0_7 <= to_insert_pred_npc_0;
            queue_exception_0_7 <= to_insert_exception_0;
            queue_br_cnt_0_7 <= to_insert_br_cnt_0;
            queue_inst_0_7 <= to_insert_inst_0;
          end
          if (_GEN_81) begin
            queue_inst_valid_1_0 <= to_insert_inst_valid_0;
            queue_pc_1_0 <= to_insert_pc_0;
            queue_pred_jump_1_0 <= to_insert_pred_jump_0;
            queue_pred_npc_1_0 <= to_insert_pred_npc_0;
            queue_exception_1_0 <= to_insert_exception_0;
            queue_br_cnt_1_0 <= to_insert_br_cnt_0;
            queue_inst_1_0 <= to_insert_inst_0;
          end
          if (_GEN_83) begin
            queue_inst_valid_1_1 <= to_insert_inst_valid_0;
            queue_pc_1_1 <= to_insert_pc_0;
            queue_pred_jump_1_1 <= to_insert_pred_jump_0;
            queue_pred_npc_1_1 <= to_insert_pred_npc_0;
            queue_exception_1_1 <= to_insert_exception_0;
            queue_br_cnt_1_1 <= to_insert_br_cnt_0;
            queue_inst_1_1 <= to_insert_inst_0;
          end
          if (_GEN_85) begin
            queue_inst_valid_1_2 <= to_insert_inst_valid_0;
            queue_pc_1_2 <= to_insert_pc_0;
            queue_pred_jump_1_2 <= to_insert_pred_jump_0;
            queue_pred_npc_1_2 <= to_insert_pred_npc_0;
            queue_exception_1_2 <= to_insert_exception_0;
            queue_br_cnt_1_2 <= to_insert_br_cnt_0;
            queue_inst_1_2 <= to_insert_inst_0;
          end
          if (_GEN_87) begin
            queue_inst_valid_1_3 <= to_insert_inst_valid_0;
            queue_pc_1_3 <= to_insert_pc_0;
            queue_pred_jump_1_3 <= to_insert_pred_jump_0;
            queue_pred_npc_1_3 <= to_insert_pred_npc_0;
            queue_exception_1_3 <= to_insert_exception_0;
            queue_br_cnt_1_3 <= to_insert_br_cnt_0;
            queue_inst_1_3 <= to_insert_inst_0;
          end
          if (_GEN_89) begin
            queue_inst_valid_1_4 <= to_insert_inst_valid_0;
            queue_pc_1_4 <= to_insert_pc_0;
            queue_pred_jump_1_4 <= to_insert_pred_jump_0;
            queue_pred_npc_1_4 <= to_insert_pred_npc_0;
            queue_exception_1_4 <= to_insert_exception_0;
            queue_br_cnt_1_4 <= to_insert_br_cnt_0;
            queue_inst_1_4 <= to_insert_inst_0;
          end
          if (_GEN_91) begin
            queue_inst_valid_1_5 <= to_insert_inst_valid_0;
            queue_pc_1_5 <= to_insert_pc_0;
            queue_pred_jump_1_5 <= to_insert_pred_jump_0;
            queue_pred_npc_1_5 <= to_insert_pred_npc_0;
            queue_exception_1_5 <= to_insert_exception_0;
            queue_br_cnt_1_5 <= to_insert_br_cnt_0;
            queue_inst_1_5 <= to_insert_inst_0;
          end
          if (_GEN_93) begin
            queue_inst_valid_1_6 <= to_insert_inst_valid_0;
            queue_pc_1_6 <= to_insert_pc_0;
            queue_pred_jump_1_6 <= to_insert_pred_jump_0;
            queue_pred_npc_1_6 <= to_insert_pred_npc_0;
            queue_exception_1_6 <= to_insert_exception_0;
            queue_br_cnt_1_6 <= to_insert_br_cnt_0;
            queue_inst_1_6 <= to_insert_inst_0;
          end
          if (_GEN_95) begin
            queue_inst_valid_1_7 <= to_insert_inst_valid_0;
            queue_pc_1_7 <= to_insert_pc_0;
            queue_pred_jump_1_7 <= to_insert_pred_jump_0;
            queue_pred_npc_1_7 <= to_insert_pred_npc_0;
            queue_exception_1_7 <= to_insert_exception_0;
            queue_br_cnt_1_7 <= to_insert_br_cnt_0;
            queue_inst_1_7 <= to_insert_inst_0;
          end
        end
        else if (_GEN_97) begin
          if (_GEN_79[0] & cur) begin
            queue_inst_valid_0_0 <= io_in_pack_inst_valid_1;
            queue_pc_0_0 <= io_in_pack_pc_1;
            queue_pred_jump_0_0 <= io_in_pack_pred_jump_1;
            queue_pred_npc_0_0 <= io_in_pack_pred_npc_1;
            queue_exception_0_0 <= io_in_pack_exception_1;
            queue_br_cnt_0_0 <= io_in_pack_br_cnt_1;
            queue_inst_0_0 <= io_in_pack_inst_1;
          end
          else if (_GEN_80) begin
            queue_inst_valid_0_0 <= to_insert_inst_valid_0;
            queue_pc_0_0 <= to_insert_pc_0;
            queue_pred_jump_0_0 <= to_insert_pred_jump_0;
            queue_pred_npc_0_0 <= to_insert_pred_npc_0;
            queue_exception_0_0 <= to_insert_exception_0;
            queue_br_cnt_0_0 <= to_insert_br_cnt_0;
            queue_inst_0_0 <= to_insert_inst_0;
          end
          if (_GEN_79[1] & cur) begin
            queue_inst_valid_0_1 <= io_in_pack_inst_valid_1;
            queue_pc_0_1 <= io_in_pack_pc_1;
            queue_pred_jump_0_1 <= io_in_pack_pred_jump_1;
            queue_pred_npc_0_1 <= io_in_pack_pred_npc_1;
            queue_exception_0_1 <= io_in_pack_exception_1;
            queue_br_cnt_0_1 <= io_in_pack_br_cnt_1;
            queue_inst_0_1 <= io_in_pack_inst_1;
          end
          else if (_GEN_82) begin
            queue_inst_valid_0_1 <= to_insert_inst_valid_0;
            queue_pc_0_1 <= to_insert_pc_0;
            queue_pred_jump_0_1 <= to_insert_pred_jump_0;
            queue_pred_npc_0_1 <= to_insert_pred_npc_0;
            queue_exception_0_1 <= to_insert_exception_0;
            queue_br_cnt_0_1 <= to_insert_br_cnt_0;
            queue_inst_0_1 <= to_insert_inst_0;
          end
          if (_GEN_79[2] & cur) begin
            queue_inst_valid_0_2 <= io_in_pack_inst_valid_1;
            queue_pc_0_2 <= io_in_pack_pc_1;
            queue_pred_jump_0_2 <= io_in_pack_pred_jump_1;
            queue_pred_npc_0_2 <= io_in_pack_pred_npc_1;
            queue_exception_0_2 <= io_in_pack_exception_1;
            queue_br_cnt_0_2 <= io_in_pack_br_cnt_1;
            queue_inst_0_2 <= io_in_pack_inst_1;
          end
          else if (_GEN_84) begin
            queue_inst_valid_0_2 <= to_insert_inst_valid_0;
            queue_pc_0_2 <= to_insert_pc_0;
            queue_pred_jump_0_2 <= to_insert_pred_jump_0;
            queue_pred_npc_0_2 <= to_insert_pred_npc_0;
            queue_exception_0_2 <= to_insert_exception_0;
            queue_br_cnt_0_2 <= to_insert_br_cnt_0;
            queue_inst_0_2 <= to_insert_inst_0;
          end
          if (_GEN_79[3] & cur) begin
            queue_inst_valid_0_3 <= io_in_pack_inst_valid_1;
            queue_pc_0_3 <= io_in_pack_pc_1;
            queue_pred_jump_0_3 <= io_in_pack_pred_jump_1;
            queue_pred_npc_0_3 <= io_in_pack_pred_npc_1;
            queue_exception_0_3 <= io_in_pack_exception_1;
            queue_br_cnt_0_3 <= io_in_pack_br_cnt_1;
            queue_inst_0_3 <= io_in_pack_inst_1;
          end
          else if (_GEN_86) begin
            queue_inst_valid_0_3 <= to_insert_inst_valid_0;
            queue_pc_0_3 <= to_insert_pc_0;
            queue_pred_jump_0_3 <= to_insert_pred_jump_0;
            queue_pred_npc_0_3 <= to_insert_pred_npc_0;
            queue_exception_0_3 <= to_insert_exception_0;
            queue_br_cnt_0_3 <= to_insert_br_cnt_0;
            queue_inst_0_3 <= to_insert_inst_0;
          end
          if (_GEN_79[4] & cur) begin
            queue_inst_valid_0_4 <= io_in_pack_inst_valid_1;
            queue_pc_0_4 <= io_in_pack_pc_1;
            queue_pred_jump_0_4 <= io_in_pack_pred_jump_1;
            queue_pred_npc_0_4 <= io_in_pack_pred_npc_1;
            queue_exception_0_4 <= io_in_pack_exception_1;
            queue_br_cnt_0_4 <= io_in_pack_br_cnt_1;
            queue_inst_0_4 <= io_in_pack_inst_1;
          end
          else if (_GEN_88) begin
            queue_inst_valid_0_4 <= to_insert_inst_valid_0;
            queue_pc_0_4 <= to_insert_pc_0;
            queue_pred_jump_0_4 <= to_insert_pred_jump_0;
            queue_pred_npc_0_4 <= to_insert_pred_npc_0;
            queue_exception_0_4 <= to_insert_exception_0;
            queue_br_cnt_0_4 <= to_insert_br_cnt_0;
            queue_inst_0_4 <= to_insert_inst_0;
          end
          if (_GEN_79[5] & cur) begin
            queue_inst_valid_0_5 <= io_in_pack_inst_valid_1;
            queue_pc_0_5 <= io_in_pack_pc_1;
            queue_pred_jump_0_5 <= io_in_pack_pred_jump_1;
            queue_pred_npc_0_5 <= io_in_pack_pred_npc_1;
            queue_exception_0_5 <= io_in_pack_exception_1;
            queue_br_cnt_0_5 <= io_in_pack_br_cnt_1;
            queue_inst_0_5 <= io_in_pack_inst_1;
          end
          else if (_GEN_90) begin
            queue_inst_valid_0_5 <= to_insert_inst_valid_0;
            queue_pc_0_5 <= to_insert_pc_0;
            queue_pred_jump_0_5 <= to_insert_pred_jump_0;
            queue_pred_npc_0_5 <= to_insert_pred_npc_0;
            queue_exception_0_5 <= to_insert_exception_0;
            queue_br_cnt_0_5 <= to_insert_br_cnt_0;
            queue_inst_0_5 <= to_insert_inst_0;
          end
          if (_GEN_79[6] & cur) begin
            queue_inst_valid_0_6 <= io_in_pack_inst_valid_1;
            queue_pc_0_6 <= io_in_pack_pc_1;
            queue_pred_jump_0_6 <= io_in_pack_pred_jump_1;
            queue_pred_npc_0_6 <= io_in_pack_pred_npc_1;
            queue_exception_0_6 <= io_in_pack_exception_1;
            queue_br_cnt_0_6 <= io_in_pack_br_cnt_1;
            queue_inst_0_6 <= io_in_pack_inst_1;
          end
          else if (_GEN_92) begin
            queue_inst_valid_0_6 <= to_insert_inst_valid_0;
            queue_pc_0_6 <= to_insert_pc_0;
            queue_pred_jump_0_6 <= to_insert_pred_jump_0;
            queue_pred_npc_0_6 <= to_insert_pred_npc_0;
            queue_exception_0_6 <= to_insert_exception_0;
            queue_br_cnt_0_6 <= to_insert_br_cnt_0;
            queue_inst_0_6 <= to_insert_inst_0;
          end
          if (_GEN_79[7] & cur) begin
            queue_inst_valid_0_7 <= io_in_pack_inst_valid_1;
            queue_pc_0_7 <= io_in_pack_pc_1;
            queue_pred_jump_0_7 <= io_in_pack_pred_jump_1;
            queue_pred_npc_0_7 <= io_in_pack_pred_npc_1;
            queue_exception_0_7 <= io_in_pack_exception_1;
            queue_br_cnt_0_7 <= io_in_pack_br_cnt_1;
            queue_inst_0_7 <= io_in_pack_inst_1;
          end
          else if (_GEN_94) begin
            queue_inst_valid_0_7 <= to_insert_inst_valid_0;
            queue_pc_0_7 <= to_insert_pc_0;
            queue_pred_jump_0_7 <= to_insert_pred_jump_0;
            queue_pred_npc_0_7 <= to_insert_pred_npc_0;
            queue_exception_0_7 <= to_insert_exception_0;
            queue_br_cnt_0_7 <= to_insert_br_cnt_0;
            queue_inst_0_7 <= to_insert_inst_0;
          end
          if (_GEN_79[0] & ~cur) begin
            queue_inst_valid_1_0 <= io_in_pack_inst_valid_1;
            queue_pc_1_0 <= io_in_pack_pc_1;
            queue_pred_jump_1_0 <= io_in_pack_pred_jump_1;
            queue_pred_npc_1_0 <= io_in_pack_pred_npc_1;
            queue_exception_1_0 <= io_in_pack_exception_1;
            queue_br_cnt_1_0 <= io_in_pack_br_cnt_1;
            queue_inst_1_0 <= io_in_pack_inst_1;
          end
          else if (_GEN_81) begin
            queue_inst_valid_1_0 <= to_insert_inst_valid_0;
            queue_pc_1_0 <= to_insert_pc_0;
            queue_pred_jump_1_0 <= to_insert_pred_jump_0;
            queue_pred_npc_1_0 <= to_insert_pred_npc_0;
            queue_exception_1_0 <= to_insert_exception_0;
            queue_br_cnt_1_0 <= to_insert_br_cnt_0;
            queue_inst_1_0 <= to_insert_inst_0;
          end
          if (_GEN_79[1] & ~cur) begin
            queue_inst_valid_1_1 <= io_in_pack_inst_valid_1;
            queue_pc_1_1 <= io_in_pack_pc_1;
            queue_pred_jump_1_1 <= io_in_pack_pred_jump_1;
            queue_pred_npc_1_1 <= io_in_pack_pred_npc_1;
            queue_exception_1_1 <= io_in_pack_exception_1;
            queue_br_cnt_1_1 <= io_in_pack_br_cnt_1;
            queue_inst_1_1 <= io_in_pack_inst_1;
          end
          else if (_GEN_83) begin
            queue_inst_valid_1_1 <= to_insert_inst_valid_0;
            queue_pc_1_1 <= to_insert_pc_0;
            queue_pred_jump_1_1 <= to_insert_pred_jump_0;
            queue_pred_npc_1_1 <= to_insert_pred_npc_0;
            queue_exception_1_1 <= to_insert_exception_0;
            queue_br_cnt_1_1 <= to_insert_br_cnt_0;
            queue_inst_1_1 <= to_insert_inst_0;
          end
          if (_GEN_79[2] & ~cur) begin
            queue_inst_valid_1_2 <= io_in_pack_inst_valid_1;
            queue_pc_1_2 <= io_in_pack_pc_1;
            queue_pred_jump_1_2 <= io_in_pack_pred_jump_1;
            queue_pred_npc_1_2 <= io_in_pack_pred_npc_1;
            queue_exception_1_2 <= io_in_pack_exception_1;
            queue_br_cnt_1_2 <= io_in_pack_br_cnt_1;
            queue_inst_1_2 <= io_in_pack_inst_1;
          end
          else if (_GEN_85) begin
            queue_inst_valid_1_2 <= to_insert_inst_valid_0;
            queue_pc_1_2 <= to_insert_pc_0;
            queue_pred_jump_1_2 <= to_insert_pred_jump_0;
            queue_pred_npc_1_2 <= to_insert_pred_npc_0;
            queue_exception_1_2 <= to_insert_exception_0;
            queue_br_cnt_1_2 <= to_insert_br_cnt_0;
            queue_inst_1_2 <= to_insert_inst_0;
          end
          if (_GEN_79[3] & ~cur) begin
            queue_inst_valid_1_3 <= io_in_pack_inst_valid_1;
            queue_pc_1_3 <= io_in_pack_pc_1;
            queue_pred_jump_1_3 <= io_in_pack_pred_jump_1;
            queue_pred_npc_1_3 <= io_in_pack_pred_npc_1;
            queue_exception_1_3 <= io_in_pack_exception_1;
            queue_br_cnt_1_3 <= io_in_pack_br_cnt_1;
            queue_inst_1_3 <= io_in_pack_inst_1;
          end
          else if (_GEN_87) begin
            queue_inst_valid_1_3 <= to_insert_inst_valid_0;
            queue_pc_1_3 <= to_insert_pc_0;
            queue_pred_jump_1_3 <= to_insert_pred_jump_0;
            queue_pred_npc_1_3 <= to_insert_pred_npc_0;
            queue_exception_1_3 <= to_insert_exception_0;
            queue_br_cnt_1_3 <= to_insert_br_cnt_0;
            queue_inst_1_3 <= to_insert_inst_0;
          end
          if (_GEN_79[4] & ~cur) begin
            queue_inst_valid_1_4 <= io_in_pack_inst_valid_1;
            queue_pc_1_4 <= io_in_pack_pc_1;
            queue_pred_jump_1_4 <= io_in_pack_pred_jump_1;
            queue_pred_npc_1_4 <= io_in_pack_pred_npc_1;
            queue_exception_1_4 <= io_in_pack_exception_1;
            queue_br_cnt_1_4 <= io_in_pack_br_cnt_1;
            queue_inst_1_4 <= io_in_pack_inst_1;
          end
          else if (_GEN_89) begin
            queue_inst_valid_1_4 <= to_insert_inst_valid_0;
            queue_pc_1_4 <= to_insert_pc_0;
            queue_pred_jump_1_4 <= to_insert_pred_jump_0;
            queue_pred_npc_1_4 <= to_insert_pred_npc_0;
            queue_exception_1_4 <= to_insert_exception_0;
            queue_br_cnt_1_4 <= to_insert_br_cnt_0;
            queue_inst_1_4 <= to_insert_inst_0;
          end
          if (_GEN_79[5] & ~cur) begin
            queue_inst_valid_1_5 <= io_in_pack_inst_valid_1;
            queue_pc_1_5 <= io_in_pack_pc_1;
            queue_pred_jump_1_5 <= io_in_pack_pred_jump_1;
            queue_pred_npc_1_5 <= io_in_pack_pred_npc_1;
            queue_exception_1_5 <= io_in_pack_exception_1;
            queue_br_cnt_1_5 <= io_in_pack_br_cnt_1;
            queue_inst_1_5 <= io_in_pack_inst_1;
          end
          else if (_GEN_91) begin
            queue_inst_valid_1_5 <= to_insert_inst_valid_0;
            queue_pc_1_5 <= to_insert_pc_0;
            queue_pred_jump_1_5 <= to_insert_pred_jump_0;
            queue_pred_npc_1_5 <= to_insert_pred_npc_0;
            queue_exception_1_5 <= to_insert_exception_0;
            queue_br_cnt_1_5 <= to_insert_br_cnt_0;
            queue_inst_1_5 <= to_insert_inst_0;
          end
          if (_GEN_79[6] & ~cur) begin
            queue_inst_valid_1_6 <= io_in_pack_inst_valid_1;
            queue_pc_1_6 <= io_in_pack_pc_1;
            queue_pred_jump_1_6 <= io_in_pack_pred_jump_1;
            queue_pred_npc_1_6 <= io_in_pack_pred_npc_1;
            queue_exception_1_6 <= io_in_pack_exception_1;
            queue_br_cnt_1_6 <= io_in_pack_br_cnt_1;
            queue_inst_1_6 <= io_in_pack_inst_1;
          end
          else if (_GEN_93) begin
            queue_inst_valid_1_6 <= to_insert_inst_valid_0;
            queue_pc_1_6 <= to_insert_pc_0;
            queue_pred_jump_1_6 <= to_insert_pred_jump_0;
            queue_pred_npc_1_6 <= to_insert_pred_npc_0;
            queue_exception_1_6 <= to_insert_exception_0;
            queue_br_cnt_1_6 <= to_insert_br_cnt_0;
            queue_inst_1_6 <= to_insert_inst_0;
          end
          if (_GEN_79[7] & ~cur) begin
            queue_inst_valid_1_7 <= io_in_pack_inst_valid_1;
            queue_pc_1_7 <= io_in_pack_pc_1;
            queue_pred_jump_1_7 <= io_in_pack_pred_jump_1;
            queue_pred_npc_1_7 <= io_in_pack_pred_npc_1;
            queue_exception_1_7 <= io_in_pack_exception_1;
            queue_br_cnt_1_7 <= io_in_pack_br_cnt_1;
            queue_inst_1_7 <= io_in_pack_inst_1;
          end
          else if (_GEN_95) begin
            queue_inst_valid_1_7 <= to_insert_inst_valid_0;
            queue_pc_1_7 <= to_insert_pc_0;
            queue_pred_jump_1_7 <= to_insert_pred_jump_0;
            queue_pred_npc_1_7 <= to_insert_pred_npc_0;
            queue_exception_1_7 <= to_insert_exception_0;
            queue_br_cnt_1_7 <= to_insert_br_cnt_0;
            queue_inst_1_7 <= to_insert_inst_0;
          end
        end
      end
      if (io_flush) begin
        head <= 8'h1;
        tail <= 8'h1;
      end
      else begin
        if (_io_out_valid_T & ~io_stall)
          head <= {head[6:0], head[7]};
        if (~(|_io_full_T_3)) begin
          if (_GEN_96) begin
            if (cur)
              tail <= {tail[6:0], tail[7]};
          end
          else if (_GEN_97)
            tail <= {tail[6:0], tail[7]};
        end
      end
      cur <= ~io_flush & (~(|_io_full_T_3) & _GEN_96 ^ cur);
    end
  end // always @(posedge)
  assign io_out_pack_inst_valid_0 =
    io_out_valid_0
    & (head[0] & queue_inst_valid_0_0 | head[1] & queue_inst_valid_0_1 | head[2]
       & queue_inst_valid_0_2 | head[3] & queue_inst_valid_0_3 | head[4]
       & queue_inst_valid_0_4 | head[5] & queue_inst_valid_0_5 | head[6]
       & queue_inst_valid_0_6 | head[7] & queue_inst_valid_0_7);
  assign io_out_pack_inst_valid_1 =
    io_out_valid_0
    & (head[0] & queue_inst_valid_1_0 | head[1] & queue_inst_valid_1_1 | head[2]
       & queue_inst_valid_1_2 | head[3] & queue_inst_valid_1_3 | head[4]
       & queue_inst_valid_1_4 | head[5] & queue_inst_valid_1_5 | head[6]
       & queue_inst_valid_1_6 | head[7] & queue_inst_valid_1_7);
  assign io_out_pack_pc_0 =
    _GEN_31 | _GEN_32 | _GEN_33 | _GEN_34 | _GEN_35 | _GEN_36 | _GEN_37 | _GEN_38;
  assign io_out_pack_pc_1 =
    _GEN_71 | _GEN_72 | _GEN_73 | _GEN_74 | _GEN_75 | _GEN_76 | _GEN_77 | _GEN_78;
  assign io_out_pack_pred_jump_0 =
    head[0] & queue_pred_jump_0_0 | head[1] & queue_pred_jump_0_1 | head[2]
    & queue_pred_jump_0_2 | head[3] & queue_pred_jump_0_3 | head[4] & queue_pred_jump_0_4
    | head[5] & queue_pred_jump_0_5 | head[6] & queue_pred_jump_0_6 | head[7]
    & queue_pred_jump_0_7;
  assign io_out_pack_pred_jump_1 =
    head[0] & queue_pred_jump_1_0 | head[1] & queue_pred_jump_1_1 | head[2]
    & queue_pred_jump_1_2 | head[3] & queue_pred_jump_1_3 | head[4] & queue_pred_jump_1_4
    | head[5] & queue_pred_jump_1_5 | head[6] & queue_pred_jump_1_6 | head[7]
    & queue_pred_jump_1_7;
  assign io_out_pack_pred_npc_0 =
    _GEN_23 | _GEN_24 | _GEN_25 | _GEN_26 | _GEN_27 | _GEN_28 | _GEN_29 | _GEN_30;
  assign io_out_pack_pred_npc_1 =
    _GEN_63 | _GEN_64 | _GEN_65 | _GEN_66 | _GEN_67 | _GEN_68 | _GEN_69 | _GEN_70;
  assign io_out_pack_exception_0 =
    _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_21 | _GEN_22;
  assign io_out_pack_exception_1 =
    _GEN_55 | _GEN_56 | _GEN_57 | _GEN_58 | _GEN_59 | _GEN_60 | _GEN_61 | _GEN_62;
  assign io_out_pack_br_cnt_0 =
    _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14;
  assign io_out_pack_br_cnt_1 =
    _GEN_47 | _GEN_48 | _GEN_49 | _GEN_50 | _GEN_51 | _GEN_52 | _GEN_53 | _GEN_54;
  assign io_out_pack_inst_0 =
    _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6;
  assign io_out_pack_inst_1 =
    _GEN_39 | _GEN_40 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44 | _GEN_45 | _GEN_46;
  assign io_out_valid = io_out_valid_0;
  assign io_full = |_io_full_T_3;
endmodule

