// Generated by CIRCT firtool-1.62.0
module Icache(
  input         clock,
                reset,
  input  [31:0] io_addr_IF,
                io_paddr_IF,
  input         io_exception,
                io_rvalid_IF,
                io_uncache_IF,
                io_cacop_en,
  input  [1:0]  io_cacop_op,
  output        io_has_cacop_IF,
  output [31:0] io_inst_0,
                io_inst_1,
  output        io_inst_valid,
                io_cache_miss,
  input         io_i_rready,
  input  [31:0] io_i_rdata,
  input         io_i_rlast,
  output        io_i_rvalid,
  output [31:0] io_i_araddr,
  output [7:0]  io_i_rlen,
  input         io_stall
);

  wire              data_sel;
  wire              addr_sel;
  wire              _xilinx_single_port_ram_no_change_3_wea;
  wire [511:0]      _xilinx_single_port_ram_no_change_3_douta;
  wire              _xilinx_single_port_ram_no_change_2_wea;
  wire [511:0]      _xilinx_single_port_ram_no_change_2_douta;
  wire              _xilinx_single_port_ram_no_change_1_wea;
  wire [19:0]       _xilinx_single_port_ram_no_change_1_douta;
  wire              _xilinx_single_port_ram_no_change_wea;
  wire [19:0]       _xilinx_single_port_ram_no_change_douta;
  reg               cacop_en_IF;
  reg  [1:0]        cacop_op_IF;
  reg  [31:0]       cacop_addr_IF;
  reg  [31:0]       paddr_reg;
  reg               rvalid_reg;
  reg               uncache_reg;
  reg               cacop_en_reg;
  reg  [1:0]        cacop_op_reg;
  reg  [511:0]      rbuf;
  reg  [31:0]       rbuf_inst;
  reg               rready;
  wire [6:0]        tag_BRAM_addra_0 = addr_sel ? paddr_reg[12:6] : io_addr_IF[12:6];
  wire [19:0]       _tag_BRAM_1_dina_T = {1'h1, paddr_reg[31:13]};
  wire [19:0]       tag_BRAM_dina_0 = cacop_en_reg ? 20'h0 : _tag_BRAM_1_dina_T;
  wire [6:0]        tag_BRAM_addra_1 = addr_sel ? paddr_reg[12:6] : io_addr_IF[12:6];
  wire [19:0]       tag_BRAM_dina_1 = cacop_en_reg ? 20'h0 : _tag_BRAM_1_dina_T;
  wire [6:0]        cmem_addra_0 = addr_sel ? paddr_reg[12:6] : io_addr_IF[12:6];
  wire [6:0]        cmem_addra_1 = addr_sel ? paddr_reg[12:6] : io_addr_IF[12:6];
  wire              cache_hit_oh_0 =
    _xilinx_single_port_ram_no_change_douta[19]
    & (_xilinx_single_port_ram_no_change_douta[18:0] ^ paddr_reg[31:13]) == 19'h0;
  wire              cache_hit_oh_1 =
    _xilinx_single_port_ram_no_change_1_douta[19]
    & (_xilinx_single_port_ram_no_change_1_douta[18:0] ^ paddr_reg[31:13]) == 19'h0;
  wire [1:0]        _cache_hit_T = {cache_hit_oh_1, cache_hit_oh_0};
  wire              cacop_way_RM = cacop_op_reg[1] ? cache_hit_oh_1 : paddr_reg[0];
  wire              cacop_exec_RM = ~(cacop_op_reg[1]) | (|_cache_hit_T);
  wire [511:0]      _cmem_hit_line_T =
    cache_hit_oh_0 ? _xilinx_single_port_ram_no_change_2_douta : 512'h0;
  wire [511:0]      _cmem_hit_line_T_1 =
    cache_hit_oh_1 ? _xilinx_single_port_ram_no_change_3_douta : 512'h0;
  wire [511:0]      cmem_hit_line = _cmem_hit_line_T | _cmem_hit_line_T_1;
  wire [15:0][63:0] _GEN =
    {{{32'h0, rbuf[511:480]}},
     {rbuf[511:448]},
     {rbuf[479:416]},
     {rbuf[447:384]},
     {rbuf[415:352]},
     {rbuf[383:320]},
     {rbuf[351:288]},
     {rbuf[319:256]},
     {rbuf[287:224]},
     {rbuf[255:192]},
     {rbuf[223:160]},
     {rbuf[191:128]},
     {rbuf[159:96]},
     {rbuf[127:64]},
     {rbuf[95:32]},
     {rbuf[63:0]}};
  wire [63:0]       rbuf_rdata = uncache_reg ? rbuf[511:448] : _GEN[paddr_reg[5:2]];
  wire [15:0][63:0] _GEN_0 =
    {{{32'h0, cmem_hit_line[511:480]}},
     {cmem_hit_line[511:448]},
     {cmem_hit_line[479:416]},
     {cmem_hit_line[447:384]},
     {cmem_hit_line[415:352]},
     {cmem_hit_line[383:320]},
     {cmem_hit_line[351:288]},
     {cmem_hit_line[319:256]},
     {cmem_hit_line[287:224]},
     {cmem_hit_line[255:192]},
     {cmem_hit_line[223:160]},
     {cmem_hit_line[191:128]},
     {cmem_hit_line[159:96]},
     {cmem_hit_line[127:64]},
     {cmem_hit_line[95:32]},
     {cmem_hit_line[63:0]}};
  wire [63:0]       _GEN_1 = _GEN_0[paddr_reg[5:2]];
  reg               lru_0;
  reg               lru_1;
  reg               lru_2;
  reg               lru_3;
  reg               lru_4;
  reg               lru_5;
  reg               lru_6;
  reg               lru_7;
  reg               lru_8;
  reg               lru_9;
  reg               lru_10;
  reg               lru_11;
  reg               lru_12;
  reg               lru_13;
  reg               lru_14;
  reg               lru_15;
  reg               lru_16;
  reg               lru_17;
  reg               lru_18;
  reg               lru_19;
  reg               lru_20;
  reg               lru_21;
  reg               lru_22;
  reg               lru_23;
  reg               lru_24;
  reg               lru_25;
  reg               lru_26;
  reg               lru_27;
  reg               lru_28;
  reg               lru_29;
  reg               lru_30;
  reg               lru_31;
  reg               lru_32;
  reg               lru_33;
  reg               lru_34;
  reg               lru_35;
  reg               lru_36;
  reg               lru_37;
  reg               lru_38;
  reg               lru_39;
  reg               lru_40;
  reg               lru_41;
  reg               lru_42;
  reg               lru_43;
  reg               lru_44;
  reg               lru_45;
  reg               lru_46;
  reg               lru_47;
  reg               lru_48;
  reg               lru_49;
  reg               lru_50;
  reg               lru_51;
  reg               lru_52;
  reg               lru_53;
  reg               lru_54;
  reg               lru_55;
  reg               lru_56;
  reg               lru_57;
  reg               lru_58;
  reg               lru_59;
  reg               lru_60;
  reg               lru_61;
  reg               lru_62;
  reg               lru_63;
  reg               lru_64;
  reg               lru_65;
  reg               lru_66;
  reg               lru_67;
  reg               lru_68;
  reg               lru_69;
  reg               lru_70;
  reg               lru_71;
  reg               lru_72;
  reg               lru_73;
  reg               lru_74;
  reg               lru_75;
  reg               lru_76;
  reg               lru_77;
  reg               lru_78;
  reg               lru_79;
  reg               lru_80;
  reg               lru_81;
  reg               lru_82;
  reg               lru_83;
  reg               lru_84;
  reg               lru_85;
  reg               lru_86;
  reg               lru_87;
  reg               lru_88;
  reg               lru_89;
  reg               lru_90;
  reg               lru_91;
  reg               lru_92;
  reg               lru_93;
  reg               lru_94;
  reg               lru_95;
  reg               lru_96;
  reg               lru_97;
  reg               lru_98;
  reg               lru_99;
  reg               lru_100;
  reg               lru_101;
  reg               lru_102;
  reg               lru_103;
  reg               lru_104;
  reg               lru_105;
  reg               lru_106;
  reg               lru_107;
  reg               lru_108;
  reg               lru_109;
  reg               lru_110;
  reg               lru_111;
  reg               lru_112;
  reg               lru_113;
  reg               lru_114;
  reg               lru_115;
  reg               lru_116;
  reg               lru_117;
  reg               lru_118;
  reg               lru_119;
  reg               lru_120;
  reg               lru_121;
  reg               lru_122;
  reg               lru_123;
  reg               lru_124;
  reg               lru_125;
  reg               lru_126;
  reg               lru_127;
  wire [127:0]      _GEN_2 =
    {{lru_127},
     {lru_126},
     {lru_125},
     {lru_124},
     {lru_123},
     {lru_122},
     {lru_121},
     {lru_120},
     {lru_119},
     {lru_118},
     {lru_117},
     {lru_116},
     {lru_115},
     {lru_114},
     {lru_113},
     {lru_112},
     {lru_111},
     {lru_110},
     {lru_109},
     {lru_108},
     {lru_107},
     {lru_106},
     {lru_105},
     {lru_104},
     {lru_103},
     {lru_102},
     {lru_101},
     {lru_100},
     {lru_99},
     {lru_98},
     {lru_97},
     {lru_96},
     {lru_95},
     {lru_94},
     {lru_93},
     {lru_92},
     {lru_91},
     {lru_90},
     {lru_89},
     {lru_88},
     {lru_87},
     {lru_86},
     {lru_85},
     {lru_84},
     {lru_83},
     {lru_82},
     {lru_81},
     {lru_80},
     {lru_79},
     {lru_78},
     {lru_77},
     {lru_76},
     {lru_75},
     {lru_74},
     {lru_73},
     {lru_72},
     {lru_71},
     {lru_70},
     {lru_69},
     {lru_68},
     {lru_67},
     {lru_66},
     {lru_65},
     {lru_64},
     {lru_63},
     {lru_62},
     {lru_61},
     {lru_60},
     {lru_59},
     {lru_58},
     {lru_57},
     {lru_56},
     {lru_55},
     {lru_54},
     {lru_53},
     {lru_52},
     {lru_51},
     {lru_50},
     {lru_49},
     {lru_48},
     {lru_47},
     {lru_46},
     {lru_45},
     {lru_44},
     {lru_43},
     {lru_42},
     {lru_41},
     {lru_40},
     {lru_39},
     {lru_38},
     {lru_37},
     {lru_36},
     {lru_35},
     {lru_34},
     {lru_33},
     {lru_32},
     {lru_31},
     {lru_30},
     {lru_29},
     {lru_28},
     {lru_27},
     {lru_26},
     {lru_25},
     {lru_24},
     {lru_23},
     {lru_22},
     {lru_21},
     {lru_20},
     {lru_19},
     {lru_18},
     {lru_17},
     {lru_16},
     {lru_15},
     {lru_14},
     {lru_13},
     {lru_12},
     {lru_11},
     {lru_10},
     {lru_9},
     {lru_8},
     {lru_7},
     {lru_6},
     {lru_5},
     {lru_4},
     {lru_3},
     {lru_2},
     {lru_1},
     {lru_0}};
  wire              _GEN_3 = _GEN_2[paddr_reg[12:6]];
  reg  [1:0]        state;
  reg               read_finish;
  wire              _GEN_4 = state == 2'h0;
  wire              _GEN_5 = io_exception | cacop_en_reg;
  wire              _GEN_6 =
    cacop_en_reg ? cacop_exec_RM : rvalid_reg & (uncache_reg | io_stall);
  wire              _GEN_7 = rvalid_reg & ~uncache_reg & (|_cache_hit_T);
  wire              _GEN_8 = cacop_en_reg ? ~cacop_exec_RM : _GEN_7;
  wire              _GEN_9 =
    cacop_en_reg ? cacop_exec_RM : rvalid_reg & (uncache_reg | ~(|_cache_hit_T));
  wire              _GEN_10 = state == 2'h1;
  wire              _GEN_11 = state == 2'h2;
  assign addr_sel = _GEN_4 ? ~io_exception & _GEN_6 : ~_GEN_10 & _GEN_11;
  wire              _GEN_12 = _GEN_4 | _GEN_10;
  wire              lru_miss_upd = ~_GEN_12 & _GEN_11 & ~cacop_en_reg;
  wire              _GEN_13 = cacop_en_reg ? cacop_way_RM : _GEN_3;
  assign data_sel = ~_GEN_4 | _GEN_5 | ~rvalid_reg | uncache_reg;
  wire              cache_miss_RM = _GEN_4 ? ~io_exception & _GEN_9 : _GEN_10 | _GEN_11;
  wire [3:0]        _io_i_rlen_T = uncache_reg ? 4'h1 : 4'hF;
  wire              _GEN_14 = io_stall | cache_miss_RM;
  wire              _GEN_15 = paddr_reg[12:6] == 7'h0;
  wire              _GEN_16 = paddr_reg[12:6] == 7'h1;
  wire              _GEN_17 = paddr_reg[12:6] == 7'h2;
  wire              _GEN_18 = paddr_reg[12:6] == 7'h3;
  wire              _GEN_19 = paddr_reg[12:6] == 7'h4;
  wire              _GEN_20 = paddr_reg[12:6] == 7'h5;
  wire              _GEN_21 = paddr_reg[12:6] == 7'h6;
  wire              _GEN_22 = paddr_reg[12:6] == 7'h7;
  wire              _GEN_23 = paddr_reg[12:6] == 7'h8;
  wire              _GEN_24 = paddr_reg[12:6] == 7'h9;
  wire              _GEN_25 = paddr_reg[12:6] == 7'hA;
  wire              _GEN_26 = paddr_reg[12:6] == 7'hB;
  wire              _GEN_27 = paddr_reg[12:6] == 7'hC;
  wire              _GEN_28 = paddr_reg[12:6] == 7'hD;
  wire              _GEN_29 = paddr_reg[12:6] == 7'hE;
  wire              _GEN_30 = paddr_reg[12:6] == 7'hF;
  wire              _GEN_31 = paddr_reg[12:6] == 7'h10;
  wire              _GEN_32 = paddr_reg[12:6] == 7'h11;
  wire              _GEN_33 = paddr_reg[12:6] == 7'h12;
  wire              _GEN_34 = paddr_reg[12:6] == 7'h13;
  wire              _GEN_35 = paddr_reg[12:6] == 7'h14;
  wire              _GEN_36 = paddr_reg[12:6] == 7'h15;
  wire              _GEN_37 = paddr_reg[12:6] == 7'h16;
  wire              _GEN_38 = paddr_reg[12:6] == 7'h17;
  wire              _GEN_39 = paddr_reg[12:6] == 7'h18;
  wire              _GEN_40 = paddr_reg[12:6] == 7'h19;
  wire              _GEN_41 = paddr_reg[12:6] == 7'h1A;
  wire              _GEN_42 = paddr_reg[12:6] == 7'h1B;
  wire              _GEN_43 = paddr_reg[12:6] == 7'h1C;
  wire              _GEN_44 = paddr_reg[12:6] == 7'h1D;
  wire              _GEN_45 = paddr_reg[12:6] == 7'h1E;
  wire              _GEN_46 = paddr_reg[12:6] == 7'h1F;
  wire              _GEN_47 = paddr_reg[12:6] == 7'h20;
  wire              _GEN_48 = paddr_reg[12:6] == 7'h21;
  wire              _GEN_49 = paddr_reg[12:6] == 7'h22;
  wire              _GEN_50 = paddr_reg[12:6] == 7'h23;
  wire              _GEN_51 = paddr_reg[12:6] == 7'h24;
  wire              _GEN_52 = paddr_reg[12:6] == 7'h25;
  wire              _GEN_53 = paddr_reg[12:6] == 7'h26;
  wire              _GEN_54 = paddr_reg[12:6] == 7'h27;
  wire              _GEN_55 = paddr_reg[12:6] == 7'h28;
  wire              _GEN_56 = paddr_reg[12:6] == 7'h29;
  wire              _GEN_57 = paddr_reg[12:6] == 7'h2A;
  wire              _GEN_58 = paddr_reg[12:6] == 7'h2B;
  wire              _GEN_59 = paddr_reg[12:6] == 7'h2C;
  wire              _GEN_60 = paddr_reg[12:6] == 7'h2D;
  wire              _GEN_61 = paddr_reg[12:6] == 7'h2E;
  wire              _GEN_62 = paddr_reg[12:6] == 7'h2F;
  wire              _GEN_63 = paddr_reg[12:6] == 7'h30;
  wire              _GEN_64 = paddr_reg[12:6] == 7'h31;
  wire              _GEN_65 = paddr_reg[12:6] == 7'h32;
  wire              _GEN_66 = paddr_reg[12:6] == 7'h33;
  wire              _GEN_67 = paddr_reg[12:6] == 7'h34;
  wire              _GEN_68 = paddr_reg[12:6] == 7'h35;
  wire              _GEN_69 = paddr_reg[12:6] == 7'h36;
  wire              _GEN_70 = paddr_reg[12:6] == 7'h37;
  wire              _GEN_71 = paddr_reg[12:6] == 7'h38;
  wire              _GEN_72 = paddr_reg[12:6] == 7'h39;
  wire              _GEN_73 = paddr_reg[12:6] == 7'h3A;
  wire              _GEN_74 = paddr_reg[12:6] == 7'h3B;
  wire              _GEN_75 = paddr_reg[12:6] == 7'h3C;
  wire              _GEN_76 = paddr_reg[12:6] == 7'h3D;
  wire              _GEN_77 = paddr_reg[12:6] == 7'h3E;
  wire              _GEN_78 = paddr_reg[12:6] == 7'h3F;
  wire              _GEN_79 = paddr_reg[12:6] == 7'h40;
  wire              _GEN_80 = paddr_reg[12:6] == 7'h41;
  wire              _GEN_81 = paddr_reg[12:6] == 7'h42;
  wire              _GEN_82 = paddr_reg[12:6] == 7'h43;
  wire              _GEN_83 = paddr_reg[12:6] == 7'h44;
  wire              _GEN_84 = paddr_reg[12:6] == 7'h45;
  wire              _GEN_85 = paddr_reg[12:6] == 7'h46;
  wire              _GEN_86 = paddr_reg[12:6] == 7'h47;
  wire              _GEN_87 = paddr_reg[12:6] == 7'h48;
  wire              _GEN_88 = paddr_reg[12:6] == 7'h49;
  wire              _GEN_89 = paddr_reg[12:6] == 7'h4A;
  wire              _GEN_90 = paddr_reg[12:6] == 7'h4B;
  wire              _GEN_91 = paddr_reg[12:6] == 7'h4C;
  wire              _GEN_92 = paddr_reg[12:6] == 7'h4D;
  wire              _GEN_93 = paddr_reg[12:6] == 7'h4E;
  wire              _GEN_94 = paddr_reg[12:6] == 7'h4F;
  wire              _GEN_95 = paddr_reg[12:6] == 7'h50;
  wire              _GEN_96 = paddr_reg[12:6] == 7'h51;
  wire              _GEN_97 = paddr_reg[12:6] == 7'h52;
  wire              _GEN_98 = paddr_reg[12:6] == 7'h53;
  wire              _GEN_99 = paddr_reg[12:6] == 7'h54;
  wire              _GEN_100 = paddr_reg[12:6] == 7'h55;
  wire              _GEN_101 = paddr_reg[12:6] == 7'h56;
  wire              _GEN_102 = paddr_reg[12:6] == 7'h57;
  wire              _GEN_103 = paddr_reg[12:6] == 7'h58;
  wire              _GEN_104 = paddr_reg[12:6] == 7'h59;
  wire              _GEN_105 = paddr_reg[12:6] == 7'h5A;
  wire              _GEN_106 = paddr_reg[12:6] == 7'h5B;
  wire              _GEN_107 = paddr_reg[12:6] == 7'h5C;
  wire              _GEN_108 = paddr_reg[12:6] == 7'h5D;
  wire              _GEN_109 = paddr_reg[12:6] == 7'h5E;
  wire              _GEN_110 = paddr_reg[12:6] == 7'h5F;
  wire              _GEN_111 = paddr_reg[12:6] == 7'h60;
  wire              _GEN_112 = paddr_reg[12:6] == 7'h61;
  wire              _GEN_113 = paddr_reg[12:6] == 7'h62;
  wire              _GEN_114 = paddr_reg[12:6] == 7'h63;
  wire              _GEN_115 = paddr_reg[12:6] == 7'h64;
  wire              _GEN_116 = paddr_reg[12:6] == 7'h65;
  wire              _GEN_117 = paddr_reg[12:6] == 7'h66;
  wire              _GEN_118 = paddr_reg[12:6] == 7'h67;
  wire              _GEN_119 = paddr_reg[12:6] == 7'h68;
  wire              _GEN_120 = paddr_reg[12:6] == 7'h69;
  wire              _GEN_121 = paddr_reg[12:6] == 7'h6A;
  wire              _GEN_122 = paddr_reg[12:6] == 7'h6B;
  wire              _GEN_123 = paddr_reg[12:6] == 7'h6C;
  wire              _GEN_124 = paddr_reg[12:6] == 7'h6D;
  wire              _GEN_125 = paddr_reg[12:6] == 7'h6E;
  wire              _GEN_126 = paddr_reg[12:6] == 7'h6F;
  wire              _GEN_127 = paddr_reg[12:6] == 7'h70;
  wire              _GEN_128 = paddr_reg[12:6] == 7'h71;
  wire              _GEN_129 = paddr_reg[12:6] == 7'h72;
  wire              _GEN_130 = paddr_reg[12:6] == 7'h73;
  wire              _GEN_131 = paddr_reg[12:6] == 7'h74;
  wire              _GEN_132 = paddr_reg[12:6] == 7'h75;
  wire              _GEN_133 = paddr_reg[12:6] == 7'h76;
  wire              _GEN_134 = paddr_reg[12:6] == 7'h77;
  wire              _GEN_135 = paddr_reg[12:6] == 7'h78;
  wire              _GEN_136 = paddr_reg[12:6] == 7'h79;
  wire              _GEN_137 = paddr_reg[12:6] == 7'h7A;
  wire              _GEN_138 = paddr_reg[12:6] == 7'h7B;
  wire              _GEN_139 = paddr_reg[12:6] == 7'h7C;
  wire              _GEN_140 = paddr_reg[12:6] == 7'h7D;
  wire              _GEN_141 = paddr_reg[12:6] == 7'h7E;
  wire [1:0]        _state_T_3 = read_finish ? {1'h1, uncache_reg} : 2'h1;
  wire [1:0]        _GEN_142 = rvalid_reg ? {1'h0, uncache_reg | cache_miss_RM} : state;
  wire [1:0]        _GEN_143 = cacop_en_reg ? {cacop_exec_RM, 1'h0} : _GEN_142;
  wire [1:0]        _GEN_144 = io_exception ? 2'h0 : _GEN_143;
  wire [3:0][1:0]   _GEN_145 = {{{2{io_stall}}}, {2'h3}, {_state_T_3}, {_GEN_144}};
  always @(posedge clock) begin
    if (reset) begin
      cacop_en_IF <= 1'h0;
      cacop_op_IF <= 2'h0;
      cacop_addr_IF <= 32'h0;
      paddr_reg <= 32'h0;
      rvalid_reg <= 1'h0;
      uncache_reg <= 1'h0;
      cacop_en_reg <= 1'h0;
      cacop_op_reg <= 2'h0;
      rbuf <= 512'h0;
      rbuf_inst <= 32'h0;
      lru_0 <= 1'h0;
      lru_1 <= 1'h0;
      lru_2 <= 1'h0;
      lru_3 <= 1'h0;
      lru_4 <= 1'h0;
      lru_5 <= 1'h0;
      lru_6 <= 1'h0;
      lru_7 <= 1'h0;
      lru_8 <= 1'h0;
      lru_9 <= 1'h0;
      lru_10 <= 1'h0;
      lru_11 <= 1'h0;
      lru_12 <= 1'h0;
      lru_13 <= 1'h0;
      lru_14 <= 1'h0;
      lru_15 <= 1'h0;
      lru_16 <= 1'h0;
      lru_17 <= 1'h0;
      lru_18 <= 1'h0;
      lru_19 <= 1'h0;
      lru_20 <= 1'h0;
      lru_21 <= 1'h0;
      lru_22 <= 1'h0;
      lru_23 <= 1'h0;
      lru_24 <= 1'h0;
      lru_25 <= 1'h0;
      lru_26 <= 1'h0;
      lru_27 <= 1'h0;
      lru_28 <= 1'h0;
      lru_29 <= 1'h0;
      lru_30 <= 1'h0;
      lru_31 <= 1'h0;
      lru_32 <= 1'h0;
      lru_33 <= 1'h0;
      lru_34 <= 1'h0;
      lru_35 <= 1'h0;
      lru_36 <= 1'h0;
      lru_37 <= 1'h0;
      lru_38 <= 1'h0;
      lru_39 <= 1'h0;
      lru_40 <= 1'h0;
      lru_41 <= 1'h0;
      lru_42 <= 1'h0;
      lru_43 <= 1'h0;
      lru_44 <= 1'h0;
      lru_45 <= 1'h0;
      lru_46 <= 1'h0;
      lru_47 <= 1'h0;
      lru_48 <= 1'h0;
      lru_49 <= 1'h0;
      lru_50 <= 1'h0;
      lru_51 <= 1'h0;
      lru_52 <= 1'h0;
      lru_53 <= 1'h0;
      lru_54 <= 1'h0;
      lru_55 <= 1'h0;
      lru_56 <= 1'h0;
      lru_57 <= 1'h0;
      lru_58 <= 1'h0;
      lru_59 <= 1'h0;
      lru_60 <= 1'h0;
      lru_61 <= 1'h0;
      lru_62 <= 1'h0;
      lru_63 <= 1'h0;
      lru_64 <= 1'h0;
      lru_65 <= 1'h0;
      lru_66 <= 1'h0;
      lru_67 <= 1'h0;
      lru_68 <= 1'h0;
      lru_69 <= 1'h0;
      lru_70 <= 1'h0;
      lru_71 <= 1'h0;
      lru_72 <= 1'h0;
      lru_73 <= 1'h0;
      lru_74 <= 1'h0;
      lru_75 <= 1'h0;
      lru_76 <= 1'h0;
      lru_77 <= 1'h0;
      lru_78 <= 1'h0;
      lru_79 <= 1'h0;
      lru_80 <= 1'h0;
      lru_81 <= 1'h0;
      lru_82 <= 1'h0;
      lru_83 <= 1'h0;
      lru_84 <= 1'h0;
      lru_85 <= 1'h0;
      lru_86 <= 1'h0;
      lru_87 <= 1'h0;
      lru_88 <= 1'h0;
      lru_89 <= 1'h0;
      lru_90 <= 1'h0;
      lru_91 <= 1'h0;
      lru_92 <= 1'h0;
      lru_93 <= 1'h0;
      lru_94 <= 1'h0;
      lru_95 <= 1'h0;
      lru_96 <= 1'h0;
      lru_97 <= 1'h0;
      lru_98 <= 1'h0;
      lru_99 <= 1'h0;
      lru_100 <= 1'h0;
      lru_101 <= 1'h0;
      lru_102 <= 1'h0;
      lru_103 <= 1'h0;
      lru_104 <= 1'h0;
      lru_105 <= 1'h0;
      lru_106 <= 1'h0;
      lru_107 <= 1'h0;
      lru_108 <= 1'h0;
      lru_109 <= 1'h0;
      lru_110 <= 1'h0;
      lru_111 <= 1'h0;
      lru_112 <= 1'h0;
      lru_113 <= 1'h0;
      lru_114 <= 1'h0;
      lru_115 <= 1'h0;
      lru_116 <= 1'h0;
      lru_117 <= 1'h0;
      lru_118 <= 1'h0;
      lru_119 <= 1'h0;
      lru_120 <= 1'h0;
      lru_121 <= 1'h0;
      lru_122 <= 1'h0;
      lru_123 <= 1'h0;
      lru_124 <= 1'h0;
      lru_125 <= 1'h0;
      lru_126 <= 1'h0;
      lru_127 <= 1'h0;
      state <= 2'h0;
    end
    else begin
      if (cacop_en_IF)
        cacop_en_IF <= _GEN_14 & cacop_en_IF;
      else begin
        cacop_en_IF <= io_cacop_en;
        cacop_op_IF <= io_cacop_op;
        cacop_addr_IF <= io_paddr_IF;
      end
      if (~_GEN_14) begin
        paddr_reg <= cacop_en_IF ? cacop_addr_IF : io_paddr_IF;
        rvalid_reg <= io_rvalid_IF;
        uncache_reg <= io_uncache_IF;
        cacop_en_reg <= cacop_en_IF;
        cacop_op_reg <= cacop_op_IF;
      end
      if (rready)
        rbuf <= {rbuf_inst, rbuf[511:32]};
      if (io_i_rready)
        rbuf_inst <= io_i_rdata;
      if (_GEN_4 & ~_GEN_5 & _GEN_7) begin
        if (_GEN_15)
          lru_0 <= ~cache_hit_oh_1;
        if (_GEN_16)
          lru_1 <= ~cache_hit_oh_1;
        if (_GEN_17)
          lru_2 <= ~cache_hit_oh_1;
        if (_GEN_18)
          lru_3 <= ~cache_hit_oh_1;
        if (_GEN_19)
          lru_4 <= ~cache_hit_oh_1;
        if (_GEN_20)
          lru_5 <= ~cache_hit_oh_1;
        if (_GEN_21)
          lru_6 <= ~cache_hit_oh_1;
        if (_GEN_22)
          lru_7 <= ~cache_hit_oh_1;
        if (_GEN_23)
          lru_8 <= ~cache_hit_oh_1;
        if (_GEN_24)
          lru_9 <= ~cache_hit_oh_1;
        if (_GEN_25)
          lru_10 <= ~cache_hit_oh_1;
        if (_GEN_26)
          lru_11 <= ~cache_hit_oh_1;
        if (_GEN_27)
          lru_12 <= ~cache_hit_oh_1;
        if (_GEN_28)
          lru_13 <= ~cache_hit_oh_1;
        if (_GEN_29)
          lru_14 <= ~cache_hit_oh_1;
        if (_GEN_30)
          lru_15 <= ~cache_hit_oh_1;
        if (_GEN_31)
          lru_16 <= ~cache_hit_oh_1;
        if (_GEN_32)
          lru_17 <= ~cache_hit_oh_1;
        if (_GEN_33)
          lru_18 <= ~cache_hit_oh_1;
        if (_GEN_34)
          lru_19 <= ~cache_hit_oh_1;
        if (_GEN_35)
          lru_20 <= ~cache_hit_oh_1;
        if (_GEN_36)
          lru_21 <= ~cache_hit_oh_1;
        if (_GEN_37)
          lru_22 <= ~cache_hit_oh_1;
        if (_GEN_38)
          lru_23 <= ~cache_hit_oh_1;
        if (_GEN_39)
          lru_24 <= ~cache_hit_oh_1;
        if (_GEN_40)
          lru_25 <= ~cache_hit_oh_1;
        if (_GEN_41)
          lru_26 <= ~cache_hit_oh_1;
        if (_GEN_42)
          lru_27 <= ~cache_hit_oh_1;
        if (_GEN_43)
          lru_28 <= ~cache_hit_oh_1;
        if (_GEN_44)
          lru_29 <= ~cache_hit_oh_1;
        if (_GEN_45)
          lru_30 <= ~cache_hit_oh_1;
        if (_GEN_46)
          lru_31 <= ~cache_hit_oh_1;
        if (_GEN_47)
          lru_32 <= ~cache_hit_oh_1;
        if (_GEN_48)
          lru_33 <= ~cache_hit_oh_1;
        if (_GEN_49)
          lru_34 <= ~cache_hit_oh_1;
        if (_GEN_50)
          lru_35 <= ~cache_hit_oh_1;
        if (_GEN_51)
          lru_36 <= ~cache_hit_oh_1;
        if (_GEN_52)
          lru_37 <= ~cache_hit_oh_1;
        if (_GEN_53)
          lru_38 <= ~cache_hit_oh_1;
        if (_GEN_54)
          lru_39 <= ~cache_hit_oh_1;
        if (_GEN_55)
          lru_40 <= ~cache_hit_oh_1;
        if (_GEN_56)
          lru_41 <= ~cache_hit_oh_1;
        if (_GEN_57)
          lru_42 <= ~cache_hit_oh_1;
        if (_GEN_58)
          lru_43 <= ~cache_hit_oh_1;
        if (_GEN_59)
          lru_44 <= ~cache_hit_oh_1;
        if (_GEN_60)
          lru_45 <= ~cache_hit_oh_1;
        if (_GEN_61)
          lru_46 <= ~cache_hit_oh_1;
        if (_GEN_62)
          lru_47 <= ~cache_hit_oh_1;
        if (_GEN_63)
          lru_48 <= ~cache_hit_oh_1;
        if (_GEN_64)
          lru_49 <= ~cache_hit_oh_1;
        if (_GEN_65)
          lru_50 <= ~cache_hit_oh_1;
        if (_GEN_66)
          lru_51 <= ~cache_hit_oh_1;
        if (_GEN_67)
          lru_52 <= ~cache_hit_oh_1;
        if (_GEN_68)
          lru_53 <= ~cache_hit_oh_1;
        if (_GEN_69)
          lru_54 <= ~cache_hit_oh_1;
        if (_GEN_70)
          lru_55 <= ~cache_hit_oh_1;
        if (_GEN_71)
          lru_56 <= ~cache_hit_oh_1;
        if (_GEN_72)
          lru_57 <= ~cache_hit_oh_1;
        if (_GEN_73)
          lru_58 <= ~cache_hit_oh_1;
        if (_GEN_74)
          lru_59 <= ~cache_hit_oh_1;
        if (_GEN_75)
          lru_60 <= ~cache_hit_oh_1;
        if (_GEN_76)
          lru_61 <= ~cache_hit_oh_1;
        if (_GEN_77)
          lru_62 <= ~cache_hit_oh_1;
        if (_GEN_78)
          lru_63 <= ~cache_hit_oh_1;
        if (_GEN_79)
          lru_64 <= ~cache_hit_oh_1;
        if (_GEN_80)
          lru_65 <= ~cache_hit_oh_1;
        if (_GEN_81)
          lru_66 <= ~cache_hit_oh_1;
        if (_GEN_82)
          lru_67 <= ~cache_hit_oh_1;
        if (_GEN_83)
          lru_68 <= ~cache_hit_oh_1;
        if (_GEN_84)
          lru_69 <= ~cache_hit_oh_1;
        if (_GEN_85)
          lru_70 <= ~cache_hit_oh_1;
        if (_GEN_86)
          lru_71 <= ~cache_hit_oh_1;
        if (_GEN_87)
          lru_72 <= ~cache_hit_oh_1;
        if (_GEN_88)
          lru_73 <= ~cache_hit_oh_1;
        if (_GEN_89)
          lru_74 <= ~cache_hit_oh_1;
        if (_GEN_90)
          lru_75 <= ~cache_hit_oh_1;
        if (_GEN_91)
          lru_76 <= ~cache_hit_oh_1;
        if (_GEN_92)
          lru_77 <= ~cache_hit_oh_1;
        if (_GEN_93)
          lru_78 <= ~cache_hit_oh_1;
        if (_GEN_94)
          lru_79 <= ~cache_hit_oh_1;
        if (_GEN_95)
          lru_80 <= ~cache_hit_oh_1;
        if (_GEN_96)
          lru_81 <= ~cache_hit_oh_1;
        if (_GEN_97)
          lru_82 <= ~cache_hit_oh_1;
        if (_GEN_98)
          lru_83 <= ~cache_hit_oh_1;
        if (_GEN_99)
          lru_84 <= ~cache_hit_oh_1;
        if (_GEN_100)
          lru_85 <= ~cache_hit_oh_1;
        if (_GEN_101)
          lru_86 <= ~cache_hit_oh_1;
        if (_GEN_102)
          lru_87 <= ~cache_hit_oh_1;
        if (_GEN_103)
          lru_88 <= ~cache_hit_oh_1;
        if (_GEN_104)
          lru_89 <= ~cache_hit_oh_1;
        if (_GEN_105)
          lru_90 <= ~cache_hit_oh_1;
        if (_GEN_106)
          lru_91 <= ~cache_hit_oh_1;
        if (_GEN_107)
          lru_92 <= ~cache_hit_oh_1;
        if (_GEN_108)
          lru_93 <= ~cache_hit_oh_1;
        if (_GEN_109)
          lru_94 <= ~cache_hit_oh_1;
        if (_GEN_110)
          lru_95 <= ~cache_hit_oh_1;
        if (_GEN_111)
          lru_96 <= ~cache_hit_oh_1;
        if (_GEN_112)
          lru_97 <= ~cache_hit_oh_1;
        if (_GEN_113)
          lru_98 <= ~cache_hit_oh_1;
        if (_GEN_114)
          lru_99 <= ~cache_hit_oh_1;
        if (_GEN_115)
          lru_100 <= ~cache_hit_oh_1;
        if (_GEN_116)
          lru_101 <= ~cache_hit_oh_1;
        if (_GEN_117)
          lru_102 <= ~cache_hit_oh_1;
        if (_GEN_118)
          lru_103 <= ~cache_hit_oh_1;
        if (_GEN_119)
          lru_104 <= ~cache_hit_oh_1;
        if (_GEN_120)
          lru_105 <= ~cache_hit_oh_1;
        if (_GEN_121)
          lru_106 <= ~cache_hit_oh_1;
        if (_GEN_122)
          lru_107 <= ~cache_hit_oh_1;
        if (_GEN_123)
          lru_108 <= ~cache_hit_oh_1;
        if (_GEN_124)
          lru_109 <= ~cache_hit_oh_1;
        if (_GEN_125)
          lru_110 <= ~cache_hit_oh_1;
        if (_GEN_126)
          lru_111 <= ~cache_hit_oh_1;
        if (_GEN_127)
          lru_112 <= ~cache_hit_oh_1;
        if (_GEN_128)
          lru_113 <= ~cache_hit_oh_1;
        if (_GEN_129)
          lru_114 <= ~cache_hit_oh_1;
        if (_GEN_130)
          lru_115 <= ~cache_hit_oh_1;
        if (_GEN_131)
          lru_116 <= ~cache_hit_oh_1;
        if (_GEN_132)
          lru_117 <= ~cache_hit_oh_1;
        if (_GEN_133)
          lru_118 <= ~cache_hit_oh_1;
        if (_GEN_134)
          lru_119 <= ~cache_hit_oh_1;
        if (_GEN_135)
          lru_120 <= ~cache_hit_oh_1;
        if (_GEN_136)
          lru_121 <= ~cache_hit_oh_1;
        if (_GEN_137)
          lru_122 <= ~cache_hit_oh_1;
        if (_GEN_138)
          lru_123 <= ~cache_hit_oh_1;
        if (_GEN_139)
          lru_124 <= ~cache_hit_oh_1;
        if (_GEN_140)
          lru_125 <= ~cache_hit_oh_1;
        if (_GEN_141)
          lru_126 <= ~cache_hit_oh_1;
        if (&(paddr_reg[12:6]))
          lru_127 <= ~cache_hit_oh_1;
      end
      else begin
        if (lru_miss_upd & _GEN_15)
          lru_0 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_16)
          lru_1 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_17)
          lru_2 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_18)
          lru_3 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_19)
          lru_4 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_20)
          lru_5 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_21)
          lru_6 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_22)
          lru_7 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_23)
          lru_8 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_24)
          lru_9 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_25)
          lru_10 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_26)
          lru_11 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_27)
          lru_12 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_28)
          lru_13 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_29)
          lru_14 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_30)
          lru_15 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_31)
          lru_16 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_32)
          lru_17 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_33)
          lru_18 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_34)
          lru_19 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_35)
          lru_20 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_36)
          lru_21 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_37)
          lru_22 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_38)
          lru_23 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_39)
          lru_24 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_40)
          lru_25 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_41)
          lru_26 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_42)
          lru_27 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_43)
          lru_28 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_44)
          lru_29 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_45)
          lru_30 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_46)
          lru_31 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_47)
          lru_32 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_48)
          lru_33 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_49)
          lru_34 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_50)
          lru_35 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_51)
          lru_36 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_52)
          lru_37 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_53)
          lru_38 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_54)
          lru_39 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_55)
          lru_40 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_56)
          lru_41 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_57)
          lru_42 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_58)
          lru_43 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_59)
          lru_44 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_60)
          lru_45 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_61)
          lru_46 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_62)
          lru_47 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_63)
          lru_48 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_64)
          lru_49 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_65)
          lru_50 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_66)
          lru_51 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_67)
          lru_52 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_68)
          lru_53 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_69)
          lru_54 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_70)
          lru_55 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_71)
          lru_56 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_72)
          lru_57 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_73)
          lru_58 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_74)
          lru_59 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_75)
          lru_60 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_76)
          lru_61 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_77)
          lru_62 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_78)
          lru_63 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_79)
          lru_64 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_80)
          lru_65 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_81)
          lru_66 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_82)
          lru_67 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_83)
          lru_68 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_84)
          lru_69 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_85)
          lru_70 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_86)
          lru_71 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_87)
          lru_72 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_88)
          lru_73 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_89)
          lru_74 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_90)
          lru_75 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_91)
          lru_76 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_92)
          lru_77 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_93)
          lru_78 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_94)
          lru_79 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_95)
          lru_80 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_96)
          lru_81 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_97)
          lru_82 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_98)
          lru_83 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_99)
          lru_84 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_100)
          lru_85 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_101)
          lru_86 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_102)
          lru_87 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_103)
          lru_88 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_104)
          lru_89 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_105)
          lru_90 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_106)
          lru_91 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_107)
          lru_92 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_108)
          lru_93 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_109)
          lru_94 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_110)
          lru_95 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_111)
          lru_96 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_112)
          lru_97 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_113)
          lru_98 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_114)
          lru_99 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_115)
          lru_100 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_116)
          lru_101 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_117)
          lru_102 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_118)
          lru_103 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_119)
          lru_104 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_120)
          lru_105 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_121)
          lru_106 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_122)
          lru_107 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_123)
          lru_108 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_124)
          lru_109 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_125)
          lru_110 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_126)
          lru_111 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_127)
          lru_112 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_128)
          lru_113 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_129)
          lru_114 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_130)
          lru_115 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_131)
          lru_116 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_132)
          lru_117 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_133)
          lru_118 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_134)
          lru_119 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_135)
          lru_120 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_136)
          lru_121 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_137)
          lru_122 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_138)
          lru_123 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_139)
          lru_124 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_140)
          lru_125 <= ~_GEN_3;
        if (lru_miss_upd & _GEN_141)
          lru_126 <= ~_GEN_3;
        if (lru_miss_upd & (&(paddr_reg[12:6])))
          lru_127 <= ~_GEN_3;
      end
      state <= _GEN_145[state];
    end
    rready <= io_i_rready;
    read_finish <= io_i_rlast & io_i_rready;
  end // always @(posedge)
  assign _xilinx_single_port_ram_no_change_wea = ~_GEN_12 & _GEN_11 & ~_GEN_13;
  xilinx_single_port_ram_no_change #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(20)
  ) xilinx_single_port_ram_no_change (
    .addra (tag_BRAM_addra_0),
    .dina  (tag_BRAM_dina_0),
    .clka  (clock),
    .wea   (_xilinx_single_port_ram_no_change_wea),
    .douta (_xilinx_single_port_ram_no_change_douta)
  );
  assign _xilinx_single_port_ram_no_change_1_wea = ~_GEN_12 & _GEN_11 & _GEN_13;
  xilinx_single_port_ram_no_change #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(20)
  ) xilinx_single_port_ram_no_change_1 (
    .addra (tag_BRAM_addra_1),
    .dina  (tag_BRAM_dina_1),
    .clka  (clock),
    .wea   (_xilinx_single_port_ram_no_change_1_wea),
    .douta (_xilinx_single_port_ram_no_change_1_douta)
  );
  assign _xilinx_single_port_ram_no_change_2_wea =
    ~_GEN_12 & _GEN_11 & ~_GEN_3 & ~cacop_en_reg;
  xilinx_single_port_ram_no_change #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(512)
  ) xilinx_single_port_ram_no_change_2 (
    .addra (cmem_addra_0),
    .dina  (rbuf),
    .clka  (clock),
    .wea   (_xilinx_single_port_ram_no_change_2_wea),
    .douta (_xilinx_single_port_ram_no_change_2_douta)
  );
  assign _xilinx_single_port_ram_no_change_3_wea =
    ~_GEN_12 & _GEN_11 & _GEN_3 & ~cacop_en_reg;
  xilinx_single_port_ram_no_change #(
    .RAM_DEPTH(128),
    .RAM_WIDTH(512)
  ) xilinx_single_port_ram_no_change_3 (
    .addra (cmem_addra_1),
    .dina  (rbuf),
    .clka  (clock),
    .wea   (_xilinx_single_port_ram_no_change_3_wea),
    .douta (_xilinx_single_port_ram_no_change_3_douta)
  );
  assign io_has_cacop_IF = cacop_en_IF;
  assign io_inst_0 = data_sel ? rbuf_rdata[31:0] : _GEN_1[31:0];
  assign io_inst_1 = data_sel ? rbuf_rdata[63:32] : _GEN_1[63:32];
  assign io_inst_valid =
    _GEN_4 ? ~io_exception & _GEN_8 : ~(_GEN_10 | _GEN_11) & (&state);
  assign io_cache_miss = cache_miss_RM;
  assign io_i_rvalid = ~_GEN_4 & _GEN_10 & ~read_finish;
  assign io_i_araddr = uncache_reg ? paddr_reg : {paddr_reg[31:6], 6'h0};
  assign io_i_rlen = {4'h0, _io_i_rlen_T};
endmodule

