// Generated by CIRCT firtool-1.62.0
module PreDecode(
  input         io_insts_inst_valid_0,
                io_insts_inst_valid_1,
  input  [31:0] io_insts_pc_0,
                io_insts_pc_1,
  input         io_insts_pred_valid_0,
                io_insts_pred_valid_1,
                io_insts_pred_jump_0,
                io_insts_pred_jump_1,
  input  [31:0] io_insts_pred_npc_0,
                io_insts_pred_npc_1,
  input  [7:0]  io_insts_exception_0,
                io_insts_exception_1,
  input  [1:0]  io_insts_br_cnt_0,
                io_insts_br_cnt_1,
  input  [31:0] io_insts_inst_0,
                io_insts_inst_1,
  output        io_insts_PD_inst_valid_0,
                io_insts_PD_inst_valid_1,
  output [31:0] io_insts_PD_pc_0,
                io_insts_PD_pc_1,
  output        io_insts_PD_pred_jump_0,
                io_insts_PD_pred_jump_1,
  output [31:0] io_insts_PD_pred_npc_0,
                io_insts_PD_pred_npc_1,
  output [7:0]  io_insts_PD_exception_0,
                io_insts_PD_exception_1,
  output [1:0]  io_insts_PD_br_cnt_0,
                io_insts_PD_br_cnt_1,
  output [31:0] io_insts_PD_inst_0,
                io_insts_PD_inst_1,
  output        io_pd_fix_en,
  output [31:0] io_pd_fix_target,
  output        io_pd_fix_is_bl,
  output [31:0] io_pd_fix_pc
);

  wire [1:0]  _jump_type_T_10 =
    io_insts_inst_0[29:26] == 4'h3
      ? 2'h0
      : {1'h1, ~(io_insts_inst_0[29:26] == 4'h4 | io_insts_inst_0[29:26] == 4'h5)};
  wire [1:0]  jump_type_0 = io_insts_inst_0[31:30] == 2'h1 ? _jump_type_T_10 : 2'h1;
  wire [1:0]  _jump_type_T_22 =
    io_insts_inst_1[29:26] == 4'h3
      ? 2'h0
      : {1'h1, ~(io_insts_inst_1[29:26] == 4'h4 | io_insts_inst_1[29:26] == 4'h5)};
  wire [1:0]  jump_type_1 = io_insts_inst_1[31:30] == 2'h1 ? _jump_type_T_22 : 2'h1;
  wire        _GEN = jump_type_0 == 2'h1;
  wire        _GEN_0 = jump_type_0 == 2'h2;
  wire [31:0] _npc_T_7 =
    32'(io_insts_pc_0
        + {{4{io_insts_inst_0[9]}}, io_insts_inst_0[9:0], io_insts_inst_0[25:10], 2'h0});
  wire        _GEN_1 = (&jump_type_0) & ~io_insts_pred_valid_0;
  wire        _GEN_2 =
    _GEN_0
      ? ~io_insts_pred_jump_0 | io_insts_pred_npc_0 != _npc_T_7
      : _GEN_1 & io_insts_inst_0[25];
  wire        _GEN_3 = _GEN ? io_insts_pred_jump_0 : _GEN_2;
  wire        need_fix_0 = io_insts_inst_valid_0 & _GEN_3;
  wire        _GEN_4 = _GEN_1 ? io_insts_inst_0[25] : io_insts_pred_jump_0;
  wire [31:0] _insts_PD_0_pred_npc_T_4 =
    io_insts_inst_0[25]
      ? 32'(io_insts_pc_0 + {{14{io_insts_inst_0[25]}}, io_insts_inst_0[25:10], 2'h0})
      : 32'(io_insts_pc_0 + 32'h4);
  wire [31:0] _GEN_5 = _GEN_1 ? _insts_PD_0_pred_npc_T_4 : io_insts_pred_npc_0;
  wire [31:0] _GEN_6 = _GEN_0 ? _npc_T_7 : _GEN_5;
  wire [31:0] _GEN_7 = _GEN ? 32'(io_insts_pc_0 + 32'h4) : _GEN_6;
  wire [31:0] insts_PD_pred_npc_0 = io_insts_inst_valid_0 ? _GEN_7 : io_insts_pred_npc_0;
  wire        _GEN_8 = jump_type_1 == 2'h1;
  wire        _GEN_9 = jump_type_1 == 2'h2;
  wire [31:0] _npc_T_21 =
    32'(io_insts_pc_1
        + {{4{io_insts_inst_1[9]}}, io_insts_inst_1[9:0], io_insts_inst_1[25:10], 2'h0});
  wire        _GEN_10 = (&jump_type_1) & ~io_insts_pred_valid_1;
  wire        _GEN_11 =
    _GEN_9
      ? ~io_insts_pred_jump_1 | io_insts_pred_npc_1 != _npc_T_21
      : _GEN_10 & io_insts_inst_1[25];
  wire        _GEN_12 = _GEN_8 ? io_insts_pred_jump_1 : _GEN_11;
  wire        _GEN_13 = _GEN_10 ? io_insts_inst_1[25] : io_insts_pred_jump_1;
  wire [31:0] _insts_PD_1_pred_npc_T_4 =
    io_insts_inst_1[25]
      ? 32'(io_insts_pc_1 + {{14{io_insts_inst_1[25]}}, io_insts_inst_1[25:10], 2'h0})
      : 32'(io_insts_pc_1 + 32'h4);
  wire [31:0] _GEN_14 = _GEN_10 ? _insts_PD_1_pred_npc_T_4 : io_insts_pred_npc_1;
  wire [31:0] _GEN_15 = _GEN_9 ? _npc_T_21 : _GEN_14;
  wire [31:0] _GEN_16 = _GEN_8 ? 32'(io_insts_pc_1 + 32'h4) : _GEN_15;
  wire [31:0] insts_PD_pred_npc_1 = io_insts_inst_valid_1 ? _GEN_16 : io_insts_pred_npc_1;
  wire [3:0]  _io_pd_fix_is_bl_T =
    need_fix_0 ? io_insts_inst_0[29:26] : io_insts_inst_1[29:26];
  assign io_insts_PD_inst_valid_0 = io_insts_inst_valid_0;
  assign io_insts_PD_inst_valid_1 =
    io_insts_inst_valid_0 & io_insts_inst_valid_1 & ~need_fix_0;
  assign io_insts_PD_pc_0 = io_insts_pc_0;
  assign io_insts_PD_pc_1 = io_insts_pc_1;
  assign io_insts_PD_pred_jump_0 =
    io_insts_inst_valid_0 ? ~_GEN & (_GEN_0 | _GEN_4) : io_insts_pred_jump_0;
  assign io_insts_PD_pred_jump_1 =
    io_insts_inst_valid_1 ? ~_GEN_8 & (_GEN_9 | _GEN_13) : io_insts_pred_jump_1;
  assign io_insts_PD_pred_npc_0 = insts_PD_pred_npc_0;
  assign io_insts_PD_pred_npc_1 = insts_PD_pred_npc_1;
  assign io_insts_PD_exception_0 = io_insts_exception_0;
  assign io_insts_PD_exception_1 = io_insts_exception_1;
  assign io_insts_PD_br_cnt_0 = io_insts_br_cnt_0;
  assign io_insts_PD_br_cnt_1 = io_insts_br_cnt_1;
  assign io_insts_PD_inst_0 = (|io_insts_exception_0) ? 32'h1C0000 : io_insts_inst_0;
  assign io_insts_PD_inst_1 = (|io_insts_exception_1) ? 32'h1C0000 : io_insts_inst_1;
  assign io_pd_fix_en = |{io_insts_inst_valid_1 & _GEN_12, need_fix_0};
  assign io_pd_fix_target = need_fix_0 ? insts_PD_pred_npc_0 : insts_PD_pred_npc_1;
  assign io_pd_fix_is_bl = _io_pd_fix_is_bl_T == 4'h5;
  assign io_pd_fix_pc = need_fix_0 ? io_insts_pc_0 : io_insts_pc_1;
endmodule

