// Generated by CIRCT firtool-1.62.0
module ARAT(
  input         clock,
                reset,
                io_rob_commit_en_0,
                io_rob_commit_en_1,
                io_rob_rd_valid_0,
                io_rob_rd_valid_1,
  input  [5:0]  io_rob_prd_0,
                io_rob_prd_1,
                io_rob_pprd_0,
                io_rob_pprd_1,
  output        io_arat_0,
                io_arat_1,
                io_arat_2,
                io_arat_3,
                io_arat_4,
                io_arat_5,
                io_arat_6,
                io_arat_7,
                io_arat_8,
                io_arat_9,
                io_arat_10,
                io_arat_11,
                io_arat_12,
                io_arat_13,
                io_arat_14,
                io_arat_15,
                io_arat_16,
                io_arat_17,
                io_arat_18,
                io_arat_19,
                io_arat_20,
                io_arat_21,
                io_arat_22,
                io_arat_23,
                io_arat_24,
                io_arat_25,
                io_arat_26,
                io_arat_27,
                io_arat_28,
                io_arat_29,
                io_arat_30,
                io_arat_31,
                io_arat_32,
                io_arat_33,
                io_arat_34,
                io_arat_35,
                io_arat_36,
                io_arat_37,
                io_arat_38,
                io_arat_39,
                io_arat_40,
                io_arat_41,
                io_arat_42,
                io_arat_43,
                io_arat_44,
                io_arat_45,
                io_arat_46,
                io_arat_47,
                io_arat_48,
                io_arat_49,
                io_arat_50,
                io_arat_51,
                io_arat_52,
                io_arat_53,
  output [5:0]  io_head,
  input  [1:0]  io_br_type,
  input  [31:0] io_pc_cmt,
  input         io_pred_update_en,
                io_real_jump,
  output [2:0]  io_top,
  output [31:0] io_ras_0,
                io_ras_1,
                io_ras_2,
                io_ras_3,
                io_ras_4,
                io_ras_5,
                io_ras_6,
                io_ras_7,
  output [7:0]  io_ghr
);

  reg         arat_0;
  reg         arat_1;
  reg         arat_2;
  reg         arat_3;
  reg         arat_4;
  reg         arat_5;
  reg         arat_6;
  reg         arat_7;
  reg         arat_8;
  reg         arat_9;
  reg         arat_10;
  reg         arat_11;
  reg         arat_12;
  reg         arat_13;
  reg         arat_14;
  reg         arat_15;
  reg         arat_16;
  reg         arat_17;
  reg         arat_18;
  reg         arat_19;
  reg         arat_20;
  reg         arat_21;
  reg         arat_22;
  reg         arat_23;
  reg         arat_24;
  reg         arat_25;
  reg         arat_26;
  reg         arat_27;
  reg         arat_28;
  reg         arat_29;
  reg         arat_30;
  reg         arat_31;
  reg         arat_32;
  reg         arat_33;
  reg         arat_34;
  reg         arat_35;
  reg         arat_36;
  reg         arat_37;
  reg         arat_38;
  reg         arat_39;
  reg         arat_40;
  reg         arat_41;
  reg         arat_42;
  reg         arat_43;
  reg         arat_44;
  reg         arat_45;
  reg         arat_46;
  reg         arat_47;
  reg         arat_48;
  reg         arat_49;
  reg         arat_50;
  reg         arat_51;
  reg         arat_52;
  reg         arat_53;
  reg  [5:0]  head;
  reg  [2:0]  top;
  reg  [31:0] ras_0;
  reg  [31:0] ras_1;
  reg  [31:0] ras_2;
  reg  [31:0] ras_3;
  reg  [31:0] ras_4;
  reg  [31:0] ras_5;
  reg  [31:0] ras_6;
  reg  [31:0] ras_7;
  reg  [7:0]  ghr;
  wire        rd_write_0 = io_rob_commit_en_0 & io_rob_rd_valid_0;
  wire        rd_write_1 = io_rob_commit_en_1 & io_rob_rd_valid_1;
  wire        _GEN = (|io_rob_pprd_0) & (io_rob_prd_0 == 6'h0 | arat_0);
  wire        _GEN_0 = io_rob_pprd_0 != 6'h1 & (io_rob_prd_0 == 6'h1 | arat_1);
  wire        _GEN_1 = io_rob_pprd_0 != 6'h2 & (io_rob_prd_0 == 6'h2 | arat_2);
  wire        _GEN_2 = io_rob_pprd_0 != 6'h3 & (io_rob_prd_0 == 6'h3 | arat_3);
  wire        _GEN_3 = io_rob_pprd_0 != 6'h4 & (io_rob_prd_0 == 6'h4 | arat_4);
  wire        _GEN_4 = io_rob_pprd_0 != 6'h5 & (io_rob_prd_0 == 6'h5 | arat_5);
  wire        _GEN_5 = io_rob_pprd_0 != 6'h6 & (io_rob_prd_0 == 6'h6 | arat_6);
  wire        _GEN_6 = io_rob_pprd_0 != 6'h7 & (io_rob_prd_0 == 6'h7 | arat_7);
  wire        _GEN_7 = io_rob_pprd_0 != 6'h8 & (io_rob_prd_0 == 6'h8 | arat_8);
  wire        _GEN_8 = io_rob_pprd_0 != 6'h9 & (io_rob_prd_0 == 6'h9 | arat_9);
  wire        _GEN_9 = io_rob_pprd_0 != 6'hA & (io_rob_prd_0 == 6'hA | arat_10);
  wire        _GEN_10 = io_rob_pprd_0 != 6'hB & (io_rob_prd_0 == 6'hB | arat_11);
  wire        _GEN_11 = io_rob_pprd_0 != 6'hC & (io_rob_prd_0 == 6'hC | arat_12);
  wire        _GEN_12 = io_rob_pprd_0 != 6'hD & (io_rob_prd_0 == 6'hD | arat_13);
  wire        _GEN_13 = io_rob_pprd_0 != 6'hE & (io_rob_prd_0 == 6'hE | arat_14);
  wire        _GEN_14 = io_rob_pprd_0 != 6'hF & (io_rob_prd_0 == 6'hF | arat_15);
  wire        _GEN_15 = io_rob_pprd_0 != 6'h10 & (io_rob_prd_0 == 6'h10 | arat_16);
  wire        _GEN_16 = io_rob_pprd_0 != 6'h11 & (io_rob_prd_0 == 6'h11 | arat_17);
  wire        _GEN_17 = io_rob_pprd_0 != 6'h12 & (io_rob_prd_0 == 6'h12 | arat_18);
  wire        _GEN_18 = io_rob_pprd_0 != 6'h13 & (io_rob_prd_0 == 6'h13 | arat_19);
  wire        _GEN_19 = io_rob_pprd_0 != 6'h14 & (io_rob_prd_0 == 6'h14 | arat_20);
  wire        _GEN_20 = io_rob_pprd_0 != 6'h15 & (io_rob_prd_0 == 6'h15 | arat_21);
  wire        _GEN_21 = io_rob_pprd_0 != 6'h16 & (io_rob_prd_0 == 6'h16 | arat_22);
  wire        _GEN_22 = io_rob_pprd_0 != 6'h17 & (io_rob_prd_0 == 6'h17 | arat_23);
  wire        _GEN_23 = io_rob_pprd_0 != 6'h18 & (io_rob_prd_0 == 6'h18 | arat_24);
  wire        _GEN_24 = io_rob_pprd_0 != 6'h19 & (io_rob_prd_0 == 6'h19 | arat_25);
  wire        _GEN_25 = io_rob_pprd_0 != 6'h1A & (io_rob_prd_0 == 6'h1A | arat_26);
  wire        _GEN_26 = io_rob_pprd_0 != 6'h1B & (io_rob_prd_0 == 6'h1B | arat_27);
  wire        _GEN_27 = io_rob_pprd_0 != 6'h1C & (io_rob_prd_0 == 6'h1C | arat_28);
  wire        _GEN_28 = io_rob_pprd_0 != 6'h1D & (io_rob_prd_0 == 6'h1D | arat_29);
  wire        _GEN_29 = io_rob_pprd_0 != 6'h1E & (io_rob_prd_0 == 6'h1E | arat_30);
  wire        _GEN_30 = io_rob_pprd_0 != 6'h1F & (io_rob_prd_0 == 6'h1F | arat_31);
  wire        _GEN_31 = io_rob_pprd_0 != 6'h20 & (io_rob_prd_0 == 6'h20 | arat_32);
  wire        _GEN_32 = io_rob_pprd_0 != 6'h21 & (io_rob_prd_0 == 6'h21 | arat_33);
  wire        _GEN_33 = io_rob_pprd_0 != 6'h22 & (io_rob_prd_0 == 6'h22 | arat_34);
  wire        _GEN_34 = io_rob_pprd_0 != 6'h23 & (io_rob_prd_0 == 6'h23 | arat_35);
  wire        _GEN_35 = io_rob_pprd_0 != 6'h24 & (io_rob_prd_0 == 6'h24 | arat_36);
  wire        _GEN_36 = io_rob_pprd_0 != 6'h25 & (io_rob_prd_0 == 6'h25 | arat_37);
  wire        _GEN_37 = io_rob_pprd_0 != 6'h26 & (io_rob_prd_0 == 6'h26 | arat_38);
  wire        _GEN_38 = io_rob_pprd_0 != 6'h27 & (io_rob_prd_0 == 6'h27 | arat_39);
  wire        _GEN_39 = io_rob_pprd_0 != 6'h28 & (io_rob_prd_0 == 6'h28 | arat_40);
  wire        _GEN_40 = io_rob_pprd_0 != 6'h29 & (io_rob_prd_0 == 6'h29 | arat_41);
  wire        _GEN_41 = io_rob_pprd_0 != 6'h2A & (io_rob_prd_0 == 6'h2A | arat_42);
  wire        _GEN_42 = io_rob_pprd_0 != 6'h2B & (io_rob_prd_0 == 6'h2B | arat_43);
  wire        _GEN_43 = io_rob_pprd_0 != 6'h2C & (io_rob_prd_0 == 6'h2C | arat_44);
  wire        _GEN_44 = io_rob_pprd_0 != 6'h2D & (io_rob_prd_0 == 6'h2D | arat_45);
  wire        _GEN_45 = io_rob_pprd_0 != 6'h2E & (io_rob_prd_0 == 6'h2E | arat_46);
  wire        _GEN_46 = io_rob_pprd_0 != 6'h2F & (io_rob_prd_0 == 6'h2F | arat_47);
  wire        _GEN_47 = io_rob_pprd_0 != 6'h30 & (io_rob_prd_0 == 6'h30 | arat_48);
  wire        _GEN_48 = io_rob_pprd_0 != 6'h31 & (io_rob_prd_0 == 6'h31 | arat_49);
  wire        _GEN_49 = io_rob_pprd_0 != 6'h32 & (io_rob_prd_0 == 6'h32 | arat_50);
  wire        _GEN_50 = io_rob_pprd_0 != 6'h33 & (io_rob_prd_0 == 6'h33 | arat_51);
  wire        _GEN_51 = io_rob_pprd_0 != 6'h34 & (io_rob_prd_0 == 6'h34 | arat_52);
  wire        _GEN_52 = io_rob_pprd_0 != 6'h35 & (io_rob_prd_0 == 6'h35 | arat_53);
  wire [6:0]  _head_T_2 =
    7'({1'h0, head} + {5'h0, 2'({1'h0, rd_write_0} + {1'h0, rd_write_1})});
  wire        _GEN_53 = io_br_type == 2'h1 & io_pred_update_en;
  wire        _GEN_54 = io_br_type[1] & io_pred_update_en;
  wire        _GEN_55 = rd_write_0 ? _GEN : arat_0;
  wire        _GEN_56 = rd_write_0 ? _GEN_0 : arat_1;
  wire        _GEN_57 = rd_write_0 ? _GEN_1 : arat_2;
  wire        _GEN_58 = rd_write_0 ? _GEN_2 : arat_3;
  wire        _GEN_59 = rd_write_0 ? _GEN_3 : arat_4;
  wire        _GEN_60 = rd_write_0 ? _GEN_4 : arat_5;
  wire        _GEN_61 = rd_write_0 ? _GEN_5 : arat_6;
  wire        _GEN_62 = rd_write_0 ? _GEN_6 : arat_7;
  wire        _GEN_63 = rd_write_0 ? _GEN_7 : arat_8;
  wire        _GEN_64 = rd_write_0 ? _GEN_8 : arat_9;
  wire        _GEN_65 = rd_write_0 ? _GEN_9 : arat_10;
  wire        _GEN_66 = rd_write_0 ? _GEN_10 : arat_11;
  wire        _GEN_67 = rd_write_0 ? _GEN_11 : arat_12;
  wire        _GEN_68 = rd_write_0 ? _GEN_12 : arat_13;
  wire        _GEN_69 = rd_write_0 ? _GEN_13 : arat_14;
  wire        _GEN_70 = rd_write_0 ? _GEN_14 : arat_15;
  wire        _GEN_71 = rd_write_0 ? _GEN_15 : arat_16;
  wire        _GEN_72 = rd_write_0 ? _GEN_16 : arat_17;
  wire        _GEN_73 = rd_write_0 ? _GEN_17 : arat_18;
  wire        _GEN_74 = rd_write_0 ? _GEN_18 : arat_19;
  wire        _GEN_75 = rd_write_0 ? _GEN_19 : arat_20;
  wire        _GEN_76 = rd_write_0 ? _GEN_20 : arat_21;
  wire        _GEN_77 = rd_write_0 ? _GEN_21 : arat_22;
  wire        _GEN_78 = rd_write_0 ? _GEN_22 : arat_23;
  wire        _GEN_79 = rd_write_0 ? _GEN_23 : arat_24;
  wire        _GEN_80 = rd_write_0 ? _GEN_24 : arat_25;
  wire        _GEN_81 = rd_write_0 ? _GEN_25 : arat_26;
  wire        _GEN_82 = rd_write_0 ? _GEN_26 : arat_27;
  wire        _GEN_83 = rd_write_0 ? _GEN_27 : arat_28;
  wire        _GEN_84 = rd_write_0 ? _GEN_28 : arat_29;
  wire        _GEN_85 = rd_write_0 ? _GEN_29 : arat_30;
  wire        _GEN_86 = rd_write_0 ? _GEN_30 : arat_31;
  wire        _GEN_87 = rd_write_0 ? _GEN_31 : arat_32;
  wire        _GEN_88 = rd_write_0 ? _GEN_32 : arat_33;
  wire        _GEN_89 = rd_write_0 ? _GEN_33 : arat_34;
  wire        _GEN_90 = rd_write_0 ? _GEN_34 : arat_35;
  wire        _GEN_91 = rd_write_0 ? _GEN_35 : arat_36;
  wire        _GEN_92 = rd_write_0 ? _GEN_36 : arat_37;
  wire        _GEN_93 = rd_write_0 ? _GEN_37 : arat_38;
  wire        _GEN_94 = rd_write_0 ? _GEN_38 : arat_39;
  wire        _GEN_95 = rd_write_0 ? _GEN_39 : arat_40;
  wire        _GEN_96 = rd_write_0 ? _GEN_40 : arat_41;
  wire        _GEN_97 = rd_write_0 ? _GEN_41 : arat_42;
  wire        _GEN_98 = rd_write_0 ? _GEN_42 : arat_43;
  wire        _GEN_99 = rd_write_0 ? _GEN_43 : arat_44;
  wire        _GEN_100 = rd_write_0 ? _GEN_44 : arat_45;
  wire        _GEN_101 = rd_write_0 ? _GEN_45 : arat_46;
  wire        _GEN_102 = rd_write_0 ? _GEN_46 : arat_47;
  wire        _GEN_103 = rd_write_0 ? _GEN_47 : arat_48;
  wire        _GEN_104 = rd_write_0 ? _GEN_48 : arat_49;
  wire        _GEN_105 = rd_write_0 ? _GEN_49 : arat_50;
  wire        _GEN_106 = rd_write_0 ? _GEN_50 : arat_51;
  wire        _GEN_107 = rd_write_0 ? _GEN_51 : arat_52;
  wire        _GEN_108 = rd_write_0 ? _GEN_52 : arat_53;
  always @(posedge clock) begin
    if (reset) begin
      arat_0 <= 1'h0;
      arat_1 <= 1'h0;
      arat_2 <= 1'h0;
      arat_3 <= 1'h0;
      arat_4 <= 1'h0;
      arat_5 <= 1'h0;
      arat_6 <= 1'h0;
      arat_7 <= 1'h0;
      arat_8 <= 1'h0;
      arat_9 <= 1'h0;
      arat_10 <= 1'h0;
      arat_11 <= 1'h0;
      arat_12 <= 1'h0;
      arat_13 <= 1'h0;
      arat_14 <= 1'h0;
      arat_15 <= 1'h0;
      arat_16 <= 1'h0;
      arat_17 <= 1'h0;
      arat_18 <= 1'h0;
      arat_19 <= 1'h0;
      arat_20 <= 1'h0;
      arat_21 <= 1'h0;
      arat_22 <= 1'h0;
      arat_23 <= 1'h0;
      arat_24 <= 1'h0;
      arat_25 <= 1'h0;
      arat_26 <= 1'h0;
      arat_27 <= 1'h0;
      arat_28 <= 1'h0;
      arat_29 <= 1'h0;
      arat_30 <= 1'h0;
      arat_31 <= 1'h0;
      arat_32 <= 1'h0;
      arat_33 <= 1'h0;
      arat_34 <= 1'h0;
      arat_35 <= 1'h0;
      arat_36 <= 1'h0;
      arat_37 <= 1'h0;
      arat_38 <= 1'h0;
      arat_39 <= 1'h0;
      arat_40 <= 1'h0;
      arat_41 <= 1'h0;
      arat_42 <= 1'h0;
      arat_43 <= 1'h0;
      arat_44 <= 1'h0;
      arat_45 <= 1'h0;
      arat_46 <= 1'h0;
      arat_47 <= 1'h0;
      arat_48 <= 1'h0;
      arat_49 <= 1'h0;
      arat_50 <= 1'h0;
      arat_51 <= 1'h0;
      arat_52 <= 1'h0;
      arat_53 <= 1'h0;
      head <= 6'h0;
      top <= 3'h7;
      ras_0 <= 32'h1C000000;
      ras_1 <= 32'h1C000000;
      ras_2 <= 32'h1C000000;
      ras_3 <= 32'h1C000000;
      ras_4 <= 32'h1C000000;
      ras_5 <= 32'h1C000000;
      ras_6 <= 32'h1C000000;
      ras_7 <= 32'h1C000000;
      ghr <= 8'h0;
    end
    else begin
      if (rd_write_1) begin
        arat_0 <= (|io_rob_pprd_1) & (io_rob_prd_1 == 6'h0 | _GEN_55);
        arat_1 <= io_rob_pprd_1 != 6'h1 & (io_rob_prd_1 == 6'h1 | _GEN_56);
        arat_2 <= io_rob_pprd_1 != 6'h2 & (io_rob_prd_1 == 6'h2 | _GEN_57);
        arat_3 <= io_rob_pprd_1 != 6'h3 & (io_rob_prd_1 == 6'h3 | _GEN_58);
        arat_4 <= io_rob_pprd_1 != 6'h4 & (io_rob_prd_1 == 6'h4 | _GEN_59);
        arat_5 <= io_rob_pprd_1 != 6'h5 & (io_rob_prd_1 == 6'h5 | _GEN_60);
        arat_6 <= io_rob_pprd_1 != 6'h6 & (io_rob_prd_1 == 6'h6 | _GEN_61);
        arat_7 <= io_rob_pprd_1 != 6'h7 & (io_rob_prd_1 == 6'h7 | _GEN_62);
        arat_8 <= io_rob_pprd_1 != 6'h8 & (io_rob_prd_1 == 6'h8 | _GEN_63);
        arat_9 <= io_rob_pprd_1 != 6'h9 & (io_rob_prd_1 == 6'h9 | _GEN_64);
        arat_10 <= io_rob_pprd_1 != 6'hA & (io_rob_prd_1 == 6'hA | _GEN_65);
        arat_11 <= io_rob_pprd_1 != 6'hB & (io_rob_prd_1 == 6'hB | _GEN_66);
        arat_12 <= io_rob_pprd_1 != 6'hC & (io_rob_prd_1 == 6'hC | _GEN_67);
        arat_13 <= io_rob_pprd_1 != 6'hD & (io_rob_prd_1 == 6'hD | _GEN_68);
        arat_14 <= io_rob_pprd_1 != 6'hE & (io_rob_prd_1 == 6'hE | _GEN_69);
        arat_15 <= io_rob_pprd_1 != 6'hF & (io_rob_prd_1 == 6'hF | _GEN_70);
        arat_16 <= io_rob_pprd_1 != 6'h10 & (io_rob_prd_1 == 6'h10 | _GEN_71);
        arat_17 <= io_rob_pprd_1 != 6'h11 & (io_rob_prd_1 == 6'h11 | _GEN_72);
        arat_18 <= io_rob_pprd_1 != 6'h12 & (io_rob_prd_1 == 6'h12 | _GEN_73);
        arat_19 <= io_rob_pprd_1 != 6'h13 & (io_rob_prd_1 == 6'h13 | _GEN_74);
        arat_20 <= io_rob_pprd_1 != 6'h14 & (io_rob_prd_1 == 6'h14 | _GEN_75);
        arat_21 <= io_rob_pprd_1 != 6'h15 & (io_rob_prd_1 == 6'h15 | _GEN_76);
        arat_22 <= io_rob_pprd_1 != 6'h16 & (io_rob_prd_1 == 6'h16 | _GEN_77);
        arat_23 <= io_rob_pprd_1 != 6'h17 & (io_rob_prd_1 == 6'h17 | _GEN_78);
        arat_24 <= io_rob_pprd_1 != 6'h18 & (io_rob_prd_1 == 6'h18 | _GEN_79);
        arat_25 <= io_rob_pprd_1 != 6'h19 & (io_rob_prd_1 == 6'h19 | _GEN_80);
        arat_26 <= io_rob_pprd_1 != 6'h1A & (io_rob_prd_1 == 6'h1A | _GEN_81);
        arat_27 <= io_rob_pprd_1 != 6'h1B & (io_rob_prd_1 == 6'h1B | _GEN_82);
        arat_28 <= io_rob_pprd_1 != 6'h1C & (io_rob_prd_1 == 6'h1C | _GEN_83);
        arat_29 <= io_rob_pprd_1 != 6'h1D & (io_rob_prd_1 == 6'h1D | _GEN_84);
        arat_30 <= io_rob_pprd_1 != 6'h1E & (io_rob_prd_1 == 6'h1E | _GEN_85);
        arat_31 <= io_rob_pprd_1 != 6'h1F & (io_rob_prd_1 == 6'h1F | _GEN_86);
        arat_32 <= io_rob_pprd_1 != 6'h20 & (io_rob_prd_1 == 6'h20 | _GEN_87);
        arat_33 <= io_rob_pprd_1 != 6'h21 & (io_rob_prd_1 == 6'h21 | _GEN_88);
        arat_34 <= io_rob_pprd_1 != 6'h22 & (io_rob_prd_1 == 6'h22 | _GEN_89);
        arat_35 <= io_rob_pprd_1 != 6'h23 & (io_rob_prd_1 == 6'h23 | _GEN_90);
        arat_36 <= io_rob_pprd_1 != 6'h24 & (io_rob_prd_1 == 6'h24 | _GEN_91);
        arat_37 <= io_rob_pprd_1 != 6'h25 & (io_rob_prd_1 == 6'h25 | _GEN_92);
        arat_38 <= io_rob_pprd_1 != 6'h26 & (io_rob_prd_1 == 6'h26 | _GEN_93);
        arat_39 <= io_rob_pprd_1 != 6'h27 & (io_rob_prd_1 == 6'h27 | _GEN_94);
        arat_40 <= io_rob_pprd_1 != 6'h28 & (io_rob_prd_1 == 6'h28 | _GEN_95);
        arat_41 <= io_rob_pprd_1 != 6'h29 & (io_rob_prd_1 == 6'h29 | _GEN_96);
        arat_42 <= io_rob_pprd_1 != 6'h2A & (io_rob_prd_1 == 6'h2A | _GEN_97);
        arat_43 <= io_rob_pprd_1 != 6'h2B & (io_rob_prd_1 == 6'h2B | _GEN_98);
        arat_44 <= io_rob_pprd_1 != 6'h2C & (io_rob_prd_1 == 6'h2C | _GEN_99);
        arat_45 <= io_rob_pprd_1 != 6'h2D & (io_rob_prd_1 == 6'h2D | _GEN_100);
        arat_46 <= io_rob_pprd_1 != 6'h2E & (io_rob_prd_1 == 6'h2E | _GEN_101);
        arat_47 <= io_rob_pprd_1 != 6'h2F & (io_rob_prd_1 == 6'h2F | _GEN_102);
        arat_48 <= io_rob_pprd_1 != 6'h30 & (io_rob_prd_1 == 6'h30 | _GEN_103);
        arat_49 <= io_rob_pprd_1 != 6'h31 & (io_rob_prd_1 == 6'h31 | _GEN_104);
        arat_50 <= io_rob_pprd_1 != 6'h32 & (io_rob_prd_1 == 6'h32 | _GEN_105);
        arat_51 <= io_rob_pprd_1 != 6'h33 & (io_rob_prd_1 == 6'h33 | _GEN_106);
        arat_52 <= io_rob_pprd_1 != 6'h34 & (io_rob_prd_1 == 6'h34 | _GEN_107);
        arat_53 <= io_rob_pprd_1 != 6'h35 & (io_rob_prd_1 == 6'h35 | _GEN_108);
      end
      else if (rd_write_0) begin
        arat_0 <= _GEN;
        arat_1 <= _GEN_0;
        arat_2 <= _GEN_1;
        arat_3 <= _GEN_2;
        arat_4 <= _GEN_3;
        arat_5 <= _GEN_4;
        arat_6 <= _GEN_5;
        arat_7 <= _GEN_6;
        arat_8 <= _GEN_7;
        arat_9 <= _GEN_8;
        arat_10 <= _GEN_9;
        arat_11 <= _GEN_10;
        arat_12 <= _GEN_11;
        arat_13 <= _GEN_12;
        arat_14 <= _GEN_13;
        arat_15 <= _GEN_14;
        arat_16 <= _GEN_15;
        arat_17 <= _GEN_16;
        arat_18 <= _GEN_17;
        arat_19 <= _GEN_18;
        arat_20 <= _GEN_19;
        arat_21 <= _GEN_20;
        arat_22 <= _GEN_21;
        arat_23 <= _GEN_22;
        arat_24 <= _GEN_23;
        arat_25 <= _GEN_24;
        arat_26 <= _GEN_25;
        arat_27 <= _GEN_26;
        arat_28 <= _GEN_27;
        arat_29 <= _GEN_28;
        arat_30 <= _GEN_29;
        arat_31 <= _GEN_30;
        arat_32 <= _GEN_31;
        arat_33 <= _GEN_32;
        arat_34 <= _GEN_33;
        arat_35 <= _GEN_34;
        arat_36 <= _GEN_35;
        arat_37 <= _GEN_36;
        arat_38 <= _GEN_37;
        arat_39 <= _GEN_38;
        arat_40 <= _GEN_39;
        arat_41 <= _GEN_40;
        arat_42 <= _GEN_41;
        arat_43 <= _GEN_42;
        arat_44 <= _GEN_43;
        arat_45 <= _GEN_44;
        arat_46 <= _GEN_45;
        arat_47 <= _GEN_46;
        arat_48 <= _GEN_47;
        arat_49 <= _GEN_48;
        arat_50 <= _GEN_49;
        arat_51 <= _GEN_50;
        arat_52 <= _GEN_51;
        arat_53 <= _GEN_52;
      end
      head <= _head_T_2 > 7'h34 ? 6'(_head_T_2[5:0] + 6'hB) : _head_T_2[5:0];
      if (_GEN_53)
        top <= 3'(top - 3'h1);
      else if (_GEN_54)
        top <= 3'(top + 3'h1);
      if (_GEN_53 | ~(_GEN_54 & top == 3'h0)) begin
      end
      else
        ras_0 <= io_pc_cmt;
      if (_GEN_53 | ~(_GEN_54 & top == 3'h1)) begin
      end
      else
        ras_1 <= io_pc_cmt;
      if (_GEN_53 | ~(_GEN_54 & top == 3'h2)) begin
      end
      else
        ras_2 <= io_pc_cmt;
      if (_GEN_53 | ~(_GEN_54 & top == 3'h3)) begin
      end
      else
        ras_3 <= io_pc_cmt;
      if (_GEN_53 | ~(_GEN_54 & top == 3'h4)) begin
      end
      else
        ras_4 <= io_pc_cmt;
      if (_GEN_53 | ~(_GEN_54 & top == 3'h5)) begin
      end
      else
        ras_5 <= io_pc_cmt;
      if (_GEN_53 | ~(_GEN_54 & top == 3'h6)) begin
      end
      else
        ras_6 <= io_pc_cmt;
      if (_GEN_53 | ~(_GEN_54 & (&top))) begin
      end
      else
        ras_7 <= io_pc_cmt;
      if (io_pred_update_en)
        ghr <= {ghr[6:0], io_real_jump};
    end
  end // always @(posedge)
  assign io_arat_0 = arat_0;
  assign io_arat_1 = arat_1;
  assign io_arat_2 = arat_2;
  assign io_arat_3 = arat_3;
  assign io_arat_4 = arat_4;
  assign io_arat_5 = arat_5;
  assign io_arat_6 = arat_6;
  assign io_arat_7 = arat_7;
  assign io_arat_8 = arat_8;
  assign io_arat_9 = arat_9;
  assign io_arat_10 = arat_10;
  assign io_arat_11 = arat_11;
  assign io_arat_12 = arat_12;
  assign io_arat_13 = arat_13;
  assign io_arat_14 = arat_14;
  assign io_arat_15 = arat_15;
  assign io_arat_16 = arat_16;
  assign io_arat_17 = arat_17;
  assign io_arat_18 = arat_18;
  assign io_arat_19 = arat_19;
  assign io_arat_20 = arat_20;
  assign io_arat_21 = arat_21;
  assign io_arat_22 = arat_22;
  assign io_arat_23 = arat_23;
  assign io_arat_24 = arat_24;
  assign io_arat_25 = arat_25;
  assign io_arat_26 = arat_26;
  assign io_arat_27 = arat_27;
  assign io_arat_28 = arat_28;
  assign io_arat_29 = arat_29;
  assign io_arat_30 = arat_30;
  assign io_arat_31 = arat_31;
  assign io_arat_32 = arat_32;
  assign io_arat_33 = arat_33;
  assign io_arat_34 = arat_34;
  assign io_arat_35 = arat_35;
  assign io_arat_36 = arat_36;
  assign io_arat_37 = arat_37;
  assign io_arat_38 = arat_38;
  assign io_arat_39 = arat_39;
  assign io_arat_40 = arat_40;
  assign io_arat_41 = arat_41;
  assign io_arat_42 = arat_42;
  assign io_arat_43 = arat_43;
  assign io_arat_44 = arat_44;
  assign io_arat_45 = arat_45;
  assign io_arat_46 = arat_46;
  assign io_arat_47 = arat_47;
  assign io_arat_48 = arat_48;
  assign io_arat_49 = arat_49;
  assign io_arat_50 = arat_50;
  assign io_arat_51 = arat_51;
  assign io_arat_52 = arat_52;
  assign io_arat_53 = arat_53;
  assign io_head = head;
  assign io_top = top;
  assign io_ras_0 = ras_0;
  assign io_ras_1 = ras_1;
  assign io_ras_2 = ras_2;
  assign io_ras_3 = ras_3;
  assign io_ras_4 = ras_4;
  assign io_ras_5 = ras_5;
  assign io_ras_6 = ras_6;
  assign io_ras_7 = ras_7;
  assign io_ghr = ghr;
endmodule

