// Generated by CIRCT firtool-1.62.0
module Branch(
  input  [3:0]  io_br_type,
  input  [31:0] io_src1,
                io_src2,
                io_pc,
                io_imm,
  input         io_pred_jump,
  input  [31:0] io_pred_npc,
  output        io_branch_en,
  output [31:0] io_branch_target,
  output        io_predict_fail
);

  wire        io_branch_en_0;
  wire [31:0] _io_branch_target_T_1 = io_br_type == 4'h3 ? io_src1 : io_pc;
  wire [31:0] _io_branch_target_T_2 = 32'(_io_branch_target_T_1 + io_imm);
  wire        _io_branch_en_T_13 =
    io_br_type == 4'h7 ? io_src1 != io_src2 : io_br_type == 4'h6 & io_src1 == io_src2;
  wire        _io_branch_en_T_15 =
    io_br_type == 4'h8 ? $signed(io_src1) < $signed(io_src2) : _io_branch_en_T_13;
  wire        _io_branch_en_T_17 =
    io_br_type == 4'h9 ? $signed(io_src1) >= $signed(io_src2) : _io_branch_en_T_15;
  wire        _io_branch_en_T_19 =
    io_br_type == 4'hA ? io_src1 < io_src2 : _io_branch_en_T_17;
  wire        _io_branch_en_T_21 =
    io_br_type == 4'hB ? io_src1 >= io_src2 : _io_branch_en_T_19;
  assign io_branch_en_0 =
    io_br_type == 4'h5 | io_br_type == 4'h4 | io_br_type == 4'h3 | _io_branch_en_T_21;
  assign io_branch_en = io_branch_en_0;
  assign io_branch_target = _io_branch_target_T_2;
  assign io_predict_fail =
    io_branch_en_0 ^ io_pred_jump | io_pred_jump & io_pred_npc != _io_branch_target_T_2;
endmodule

