// Generated by CIRCT firtool-1.62.0
module CounterModule(
  input         clock,
                reset,
  output [63:0] io_cnt
);

  reg [63:0] cnt;
  always @(posedge clock) begin
    if (reset)
      cnt <= 64'h0;
    else
      cnt <= 64'(cnt + 64'h1);
  end // always @(posedge)
  assign io_cnt = cnt;
endmodule

