// Generated by CIRCT firtool-1.62.0
module CSR_reg(
  input         clock,
                reset,
  input  [13:0] io_raddr,
  output [31:0] io_rdata,
  input  [13:0] io_waddr,
  input         io_we,
  input  [31:0] io_wdata,
  input  [7:0]  io_exception,
  input  [31:0] io_badv_exp,
  input         io_is_ertn,
  input  [31:0] io_pc_exp,
  output [31:0] io_eentry_global,
                io_tlbrentry_global,
  input  [7:0]  io_interrupt,
  input         io_ip_int,
  output [11:0] io_interrupt_vec,
  output [9:0]  io_asid_global,
  output [1:0]  io_plv_global,
  output [5:0]  io_crmd_trans,
  output [31:0] io_dmw0_global,
                io_dmw1_global,
  output [18:0] io_tlbehi_global,
  output [3:0]  io_tlbidx_global,
  output [18:0] io_tlbentry_global_vppn,
  output [5:0]  io_tlbentry_global_ps,
  output        io_tlbentry_global_g,
  output [9:0]  io_tlbentry_global_asid,
  output        io_tlbentry_global_e,
  output [19:0] io_tlbentry_global_ppn0,
  output [1:0]  io_tlbentry_global_plv0,
                io_tlbentry_global_mat0,
  output        io_tlbentry_global_d0,
                io_tlbentry_global_v0,
  output [19:0] io_tlbentry_global_ppn1,
  output [1:0]  io_tlbentry_global_plv1,
                io_tlbentry_global_mat1,
  output        io_tlbentry_global_d1,
                io_tlbentry_global_v1,
  input  [18:0] io_tlbentry_in_vppn,
  input  [5:0]  io_tlbentry_in_ps,
  input         io_tlbentry_in_g,
  input  [9:0]  io_tlbentry_in_asid,
  input         io_tlbentry_in_e,
  input  [19:0] io_tlbentry_in_ppn0,
  input  [1:0]  io_tlbentry_in_plv0,
                io_tlbentry_in_mat0,
  input         io_tlbentry_in_d0,
                io_tlbentry_in_v0,
  input  [19:0] io_tlbentry_in_ppn1,
  input  [1:0]  io_tlbentry_in_plv1,
                io_tlbentry_in_mat1,
  input         io_tlbentry_in_d1,
                io_tlbentry_in_v1,
                io_tlbrd_en,
                io_tlbsrch_en,
  output        io_llbit_global,
  input         io_llbit_set,
                io_llbit_clear,
  output [31:0] io_csr_reg_crmd,
                io_csr_reg_prmd,
                io_csr_reg_estat,
                io_csr_reg_euen,
                io_csr_reg_ecfg,
                io_csr_reg_era,
                io_csr_reg_badv,
                io_csr_reg_eentry,
                io_csr_reg_cpuid,
                io_csr_reg_save0,
                io_csr_reg_save1,
                io_csr_reg_save2,
                io_csr_reg_save3,
                io_csr_reg_llbctl,
                io_csr_reg_tlbidx,
                io_csr_reg_tlbehi,
                io_csr_reg_tlbelo0,
                io_csr_reg_tlbelo1,
                io_csr_reg_asid,
                io_csr_reg_pgdl,
                io_csr_reg_pgdh,
                io_csr_reg_pgd,
                io_csr_reg_tlbrentry,
                io_csr_reg_dmw0,
                io_csr_reg_dmw1,
                io_csr_reg_tid,
                io_csr_reg_tcfg,
                io_csr_reg_tval
);

  reg  [31:0] crmd;
  reg  [31:0] prmd;
  reg  [31:0] estat;
  reg  [31:0] euen;
  reg  [31:0] ecfg;
  reg  [31:0] era;
  reg  [31:0] badv;
  reg  [31:0] eentry;
  reg  [31:0] cpuid;
  reg  [31:0] save0;
  reg  [31:0] save1;
  reg  [31:0] save2;
  reg  [31:0] save3;
  reg  [31:0] llbctl;
  reg  [31:0] tlbidx;
  reg  [31:0] tlbehi;
  reg  [31:0] tlbelo0;
  reg  [31:0] tlbelo1;
  reg  [31:0] asid;
  reg  [31:0] pgdl;
  reg  [31:0] pgdh;
  reg  [31:0] pgd;
  reg  [31:0] tlbrentry;
  reg  [31:0] dmw0;
  reg  [31:0] dmw1;
  reg  [31:0] tid;
  reg  [31:0] tcfg;
  reg  [31:0] tval;
  reg         time_int;
  wire        is_tlbr = io_exception[6:0] == 7'h3F;
  wire        _GEN = io_we & io_waddr == 14'h0;
  wire        _GEN_0 = io_we & io_waddr == 14'h1;
  wire        _GEN_1 = io_we & io_waddr == 14'h2;
  wire        _GEN_2 = io_we & io_waddr == 14'h4;
  wire        _GEN_3 = io_we & io_waddr == 14'h5;
  wire        _GEN_4 = io_we & io_waddr == 14'h6;
  wire [31:0] _GEN_5 = _GEN_4 ? io_wdata : era;
  wire        _GEN_6 =
    io_exception[7]
    & (io_exception[6:0] == 7'h3F | io_exception[6:0] == 7'h8 | io_exception[6:0] == 7'h9
       | io_exception[6:0] < 7'h8 & (|(io_exception[6:0])));
  wire        _GEN_7 = io_we & io_waddr == 14'h7;
  wire [31:0] _GEN_8 = _GEN_7 ? io_wdata : badv;
  wire        _GEN_9 = io_we & io_waddr == 14'hC;
  wire        _GEN_10 = io_we & io_waddr == 14'h20;
  wire        _GEN_11 = io_we & io_waddr == 14'h30;
  wire        _GEN_12 = io_we & io_waddr == 14'h31;
  wire        _GEN_13 = io_we & io_waddr == 14'h32;
  wire        _GEN_14 = io_we & io_waddr == 14'h33;
  wire        _GEN_15 = io_we & io_waddr == 14'h60;
  wire        _GEN_16 = io_we & io_waddr == 14'h10;
  wire        _GEN_17 =
    io_exception[7] & (is_tlbr | (|(io_exception[6:0])) & io_exception[6:0] < 7'h8);
  wire        _GEN_18 = io_we & io_waddr == 14'h11;
  wire        _GEN_19 = io_we & io_waddr == 14'h12;
  wire        _GEN_20 = io_we & io_waddr == 14'h13;
  wire        _GEN_21 = io_we & io_waddr == 14'h18;
  wire        _GEN_22 = io_we & io_waddr == 14'h19;
  wire        _GEN_23 = io_we & io_waddr == 14'h1A;
  wire        _GEN_24 = io_we & io_waddr == 14'h1B;
  wire        _GEN_25 = io_we & io_waddr == 14'h88;
  wire        _GEN_26 = io_we & io_waddr == 14'h180;
  wire        _GEN_27 = io_we & io_waddr == 14'h181;
  wire        _GEN_28 = io_we & io_waddr == 14'h40;
  wire        _GEN_29 = io_we & io_waddr == 14'h41;
  wire        _GEN_30 = tval == 32'h0;
  reg  [31:0] tval_priv;
  wire [31:0] _io_rdata_T_1 = badv[31] ? pgdh : pgdl;
  wire [31:0] _GEN_31 = io_raddr == 14'h42 ? tval : 32'h0;
  wire [31:0] _GEN_32 = io_raddr == 14'h41 ? tcfg : _GEN_31;
  wire [31:0] _GEN_33 = io_raddr == 14'h40 ? tid : _GEN_32;
  wire [31:0] _GEN_34 = io_raddr == 14'h181 ? dmw1 : _GEN_33;
  wire [31:0] _GEN_35 = io_raddr == 14'h180 ? dmw0 : _GEN_34;
  wire [31:0] _GEN_36 = io_raddr == 14'h88 ? tlbrentry : _GEN_35;
  wire [31:0] _GEN_37 = io_raddr == 14'h1B ? _io_rdata_T_1 : _GEN_36;
  wire [31:0] _GEN_38 = io_raddr == 14'h1A ? pgdh : _GEN_37;
  wire [31:0] _GEN_39 = io_raddr == 14'h19 ? pgdl : _GEN_38;
  wire [31:0] _GEN_40 = io_raddr == 14'h18 ? asid : _GEN_39;
  wire [31:0] _GEN_41 = io_raddr == 14'h13 ? tlbelo1 : _GEN_40;
  wire [31:0] _GEN_42 = io_raddr == 14'h12 ? tlbelo0 : _GEN_41;
  wire [31:0] _GEN_43 = io_raddr == 14'h11 ? tlbehi : _GEN_42;
  wire [31:0] _GEN_44 = io_raddr == 14'h10 ? tlbidx : _GEN_43;
  wire [31:0] _GEN_45 = io_raddr == 14'h60 ? llbctl : _GEN_44;
  wire [31:0] _GEN_46 = io_raddr == 14'h33 ? save3 : _GEN_45;
  wire [31:0] _GEN_47 = io_raddr == 14'h32 ? save2 : _GEN_46;
  wire [31:0] _GEN_48 = io_raddr == 14'h31 ? save1 : _GEN_47;
  wire [31:0] _GEN_49 = io_raddr == 14'h30 ? save0 : _GEN_48;
  wire [31:0] _GEN_50 = io_raddr == 14'h20 ? cpuid : _GEN_49;
  wire [31:0] _GEN_51 = io_raddr == 14'hC ? eentry : _GEN_50;
  wire [31:0] _GEN_52 = io_raddr == 14'h7 ? badv : _GEN_51;
  wire [31:0] _GEN_53 = io_raddr == 14'h6 ? era : _GEN_52;
  wire [31:0] _GEN_54 = io_raddr == 14'h5 ? estat : _GEN_53;
  wire [31:0] _GEN_55 = io_raddr == 14'h4 ? ecfg : _GEN_54;
  wire [31:0] _GEN_56 = io_raddr == 14'h2 ? euen : _GEN_55;
  wire [31:0] _GEN_57 = io_raddr == 14'h1 ? prmd : _GEN_56;
  wire [1:0]  _io_csr_reg_crmd_T_2 = is_tlbr ? 2'h1 : crmd[4:3];
  wire [1:0]  _io_csr_reg_crmd_T_7 = (&(estat[21:16])) ? 2'h2 : crmd[4:3];
  wire [31:0] _GEN_58 = _GEN ? {23'h0, io_wdata[8:0]} : crmd;
  wire [31:0] _GEN_59 =
    io_is_ertn ? {crmd[31:5], _io_csr_reg_crmd_T_7, prmd[2:0]} : _GEN_58;
  wire [31:0] _GEN_60 = _GEN_0 ? {29'h0, io_wdata[2:0]} : prmd;
  wire [30:0] _GEN_61 =
    _GEN_3
      ? {estat[30:16], 3'h0, io_ip_int, time_int, 1'h0, io_interrupt, io_wdata[1:0]}
      : {estat[30:16], 3'h0, io_ip_int, time_int, 1'h0, io_interrupt, estat[1:0]};
  wire [31:0] _GEN_62 =
    _GEN_15 ? {llbctl[31:3], io_wdata[2], 1'h0, ~(io_wdata[1]) & llbctl[0]} : llbctl;
  wire [31:0] _GEN_63 =
    io_is_ertn ? {llbctl[31:3], 1'h0, llbctl[1], llbctl[2] & llbctl[0]} : _GEN_62;
  wire [31:0] _GEN_64 = io_llbit_clear ? {llbctl[31:1], 1'h0} : _GEN_63;
  wire [31:0] _GEN_65 =
    io_wdata[4] ? {1'h0, tlbidx[30:4], io_wdata[3:0]} : {1'h1, tlbidx[30:0]};
  wire [5:0]  _io_csr_reg_tlbidx_T_8 = io_tlbentry_in_e ? io_tlbentry_in_ps : 6'h0;
  wire [31:0] _GEN_66 =
    _GEN_16 ? {io_wdata[31], 1'h0, io_wdata[29:24], 20'h0, io_wdata[3:0]} : tlbidx;
  wire [31:0] _GEN_67 =
    io_tlbrd_en
      ? {~io_tlbentry_in_e, 1'h0, _io_csr_reg_tlbidx_T_8, tlbidx[23:0]}
      : _GEN_66;
  wire [31:0] _io_csr_reg_tlbehi_T_3 =
    io_tlbentry_in_e ? {io_tlbentry_in_vppn, 13'h0} : 32'h0;
  wire [31:0] _GEN_68 = _GEN_18 ? {io_wdata[31:13], 13'h0} : tlbehi;
  wire [31:0] _GEN_69 = io_tlbrd_en ? _io_csr_reg_tlbehi_T_3 : _GEN_68;
  wire [31:0] _io_csr_reg_tlbelo0_T_8 =
    io_tlbentry_in_e
      ? {tlbelo0[31:28],
         io_tlbentry_in_ppn0,
         1'h0,
         io_tlbentry_in_g,
         io_tlbentry_in_mat0,
         io_tlbentry_in_plv0,
         io_tlbentry_in_d0,
         io_tlbentry_in_v0}
      : 32'h0;
  wire [31:0] _GEN_70 = _GEN_19 ? {4'h0, io_wdata[27:8], 1'h0, io_wdata[6:0]} : tlbelo0;
  wire [31:0] _io_csr_reg_tlbelo1_T_8 =
    io_tlbentry_in_e
      ? {tlbelo1[31:28],
         io_tlbentry_in_ppn1,
         1'h0,
         io_tlbentry_in_g,
         io_tlbentry_in_mat1,
         io_tlbentry_in_plv1,
         io_tlbentry_in_d1,
         io_tlbentry_in_v1}
      : 32'h0;
  wire [31:0] _GEN_71 = _GEN_20 ? {4'h0, io_wdata[27:8], 1'h0, io_wdata[6:0]} : tlbelo1;
  wire [9:0]  _io_csr_reg_asid_T_1 = io_tlbentry_in_e ? io_tlbentry_in_asid : 10'h0;
  wire [31:0] _GEN_72 = _GEN_21 ? {22'h0, io_wdata[9:0]} : asid;
  wire [29:0] _io_csr_reg_tval_T_6 = tcfg[1] ? {tcfg[29:2], 2'h0} : 30'h0;
  wire [31:0] _GEN_73 = _GEN_30 ? {2'h0, _io_csr_reg_tval_T_6} : 32'(tval - 32'h1);
  wire [31:0] _GEN_74 = tcfg[0] ? _GEN_73 : tval;
  wire [1:0]  _crmd_T_2 = is_tlbr ? 2'h1 : crmd[4:3];
  wire [1:0]  _crmd_T_7 = (&(estat[21:16])) ? 2'h2 : crmd[4:3];
  wire [30:0] _GEN_75 =
    _GEN_3
      ? {estat[30:16], 3'h0, io_ip_int, time_int, 1'h0, io_interrupt, io_wdata[1:0]}
      : {estat[30:16], 3'h0, io_ip_int, time_int, 1'h0, io_interrupt, estat[1:0]};
  wire [5:0]  _tlbidx_T_8 = io_tlbentry_in_e ? io_tlbentry_in_ps : 6'h0;
  wire [9:0]  _asid_T_1 = io_tlbentry_in_e ? io_tlbentry_in_asid : 10'h0;
  wire [29:0] _tval_T_6 = tcfg[1] ? {tcfg[29:2], 2'h0} : 30'h0;
  always @(posedge clock) begin
    if (reset) begin
      crmd <= 32'h8;
      prmd <= 32'h0;
      estat <= 32'h0;
      euen <= 32'h0;
      ecfg <= 32'h0;
      era <= 32'h0;
      badv <= 32'h0;
      eentry <= 32'h0;
      cpuid <= 32'h0;
      save0 <= 32'h0;
      save1 <= 32'h0;
      save2 <= 32'h0;
      save3 <= 32'h0;
      llbctl <= 32'h0;
      tlbidx <= 32'h0;
      tlbehi <= 32'h0;
      tlbelo0 <= 32'h0;
      tlbelo1 <= 32'h0;
      asid <= 32'h0;
      pgdl <= 32'h0;
      pgdh <= 32'h0;
      pgd <= 32'h0;
      tlbrentry <= 32'h0;
      dmw0 <= 32'h0;
      dmw1 <= 32'h0;
      tid <= 32'h0;
      tcfg <= 32'h0;
      tval <= 32'h0;
      time_int <= 1'h0;
    end
    else begin
      if (io_exception[7]) begin
        crmd <= {crmd[31:5], _crmd_T_2, 3'h0};
        prmd <= {prmd[31:3], crmd[2:0]};
        estat <= {9'h0, io_exception[6:0], estat[15:0]};
        era <= io_pc_exp;
      end
      else begin
        if (io_is_ertn)
          crmd <= {crmd[31:5], _crmd_T_7, prmd[2:0]};
        else if (_GEN)
          crmd <= {23'h0, io_wdata[8:0]};
        if (_GEN_0)
          prmd <= {29'h0, io_wdata[2:0]};
        estat <= {1'h0, _GEN_75};
        if (_GEN_4)
          era <= io_wdata;
      end
      if (_GEN_1)
        euen <= {31'h0, io_wdata[0]};
      if (_GEN_2)
        ecfg <= {19'h0, io_wdata[12:11], 1'h0, io_wdata[9:0]};
      if (_GEN_6)
        badv <= io_badv_exp;
      else if (_GEN_7)
        badv <= io_wdata;
      if (_GEN_9)
        eentry <= {io_wdata[31:6], 6'h0};
      if (_GEN_10)
        cpuid <= {23'h0, io_wdata[8:0]};
      if (_GEN_11)
        save0 <= io_wdata;
      if (_GEN_12)
        save1 <= io_wdata;
      if (_GEN_13)
        save2 <= io_wdata;
      if (_GEN_14)
        save3 <= io_wdata;
      if (io_llbit_set)
        llbctl <= {llbctl[31:1], 1'h1};
      else if (io_llbit_clear)
        llbctl <= {llbctl[31:1], 1'h0};
      else if (io_is_ertn)
        llbctl <= {llbctl[31:3], 1'h0, llbctl[1], llbctl[2] & llbctl[0]};
      else if (_GEN_15)
        llbctl <= {llbctl[31:3], io_wdata[2], 1'h0, ~(io_wdata[1]) & llbctl[0]};
      if (io_tlbsrch_en) begin
        if (io_wdata[4])
          tlbidx <= {1'h0, tlbidx[30:4], io_wdata[3:0]};
        else
          tlbidx <= {1'h1, tlbidx[30:0]};
      end
      else if (io_tlbrd_en)
        tlbidx <= {~io_tlbentry_in_e, 1'h0, _tlbidx_T_8, tlbidx[23:0]};
      else if (_GEN_16)
        tlbidx <= {io_wdata[31], 1'h0, io_wdata[29:24], 20'h0, io_wdata[3:0]};
      if (_GEN_17)
        tlbehi <= {io_badv_exp[31:13], 13'h0};
      else if (io_tlbrd_en)
        tlbehi <= io_tlbentry_in_e ? {io_tlbentry_in_vppn, 13'h0} : 32'h0;
      else if (_GEN_18)
        tlbehi <= {io_wdata[31:13], 13'h0};
      if (io_tlbrd_en) begin
        if (io_tlbentry_in_e) begin
          tlbelo0 <=
            {tlbelo0[31:28],
             io_tlbentry_in_ppn0,
             1'h0,
             io_tlbentry_in_g,
             io_tlbentry_in_mat0,
             io_tlbentry_in_plv0,
             io_tlbentry_in_d0,
             io_tlbentry_in_v0};
          tlbelo1 <=
            {tlbelo1[31:28],
             io_tlbentry_in_ppn1,
             1'h0,
             io_tlbentry_in_g,
             io_tlbentry_in_mat1,
             io_tlbentry_in_plv1,
             io_tlbentry_in_d1,
             io_tlbentry_in_v1};
        end
        else begin
          tlbelo0 <= 32'h0;
          tlbelo1 <= 32'h0;
        end
        asid <= {asid[31:10], _asid_T_1};
      end
      else begin
        if (_GEN_19)
          tlbelo0 <= {4'h0, io_wdata[27:8], 1'h0, io_wdata[6:0]};
        if (_GEN_20)
          tlbelo1 <= {4'h0, io_wdata[27:8], 1'h0, io_wdata[6:0]};
        if (_GEN_21)
          asid <= {22'h0, io_wdata[9:0]};
      end
      if (_GEN_22)
        pgdl <= {io_wdata[31:12], 12'h0};
      if (_GEN_23)
        pgdh <= {io_wdata[31:12], 12'h0};
      if (_GEN_24)
        pgd <= {io_wdata[31:12], 12'h0};
      if (_GEN_25)
        tlbrentry <= {io_wdata[31:6], 6'h0};
      if (_GEN_26)
        dmw0 <=
          {io_wdata[31:29],
           1'h0,
           io_wdata[27:25],
           19'h0,
           io_wdata[5:3],
           2'h0,
           io_wdata[0]};
      if (_GEN_27)
        dmw1 <=
          {io_wdata[31:29],
           1'h0,
           io_wdata[27:25],
           19'h0,
           io_wdata[5:3],
           2'h0,
           io_wdata[0]};
      if (_GEN_28)
        tid <= io_wdata;
      if (_GEN_29) begin
        tcfg <= {2'h0, io_wdata[29:0]};
        tval <= {2'h0, io_wdata[29:2], 2'h1};
      end
      else if (tcfg[0]) begin
        if (_GEN_30)
          tval <= {2'h0, _tval_T_6};
        else
          tval <= 32'(tval - 32'h1);
      end
      time_int <=
        ~(io_we & io_waddr == 14'h44 & io_wdata[0])
        & (tcfg[0] & _GEN_30 & tval_priv == 32'h1 | time_int);
    end
    tval_priv <= tval;
  end // always @(posedge)
  assign io_rdata = io_raddr == 14'h0 ? crmd : _GEN_57;
  assign io_eentry_global = eentry;
  assign io_tlbrentry_global = tlbrentry;
  assign io_interrupt_vec =
    crmd[2] ? {estat[12:11] & ecfg[12:11], estat[9:0] & ecfg[9:0]} : 12'h0;
  assign io_asid_global = asid[9:0];
  assign io_plv_global = crmd[1:0];
  assign io_crmd_trans = crmd[8:3];
  assign io_dmw0_global = dmw0;
  assign io_dmw1_global = dmw1;
  assign io_tlbehi_global = tlbehi[31:13];
  assign io_tlbidx_global = tlbidx[3:0];
  assign io_tlbentry_global_vppn = tlbehi[31:13];
  assign io_tlbentry_global_ps = tlbidx[29:24];
  assign io_tlbentry_global_g = tlbelo0[6] & tlbelo1[6];
  assign io_tlbentry_global_asid = asid[9:0];
  assign io_tlbentry_global_e = (&(estat[21:16])) | ~(tlbidx[31]);
  assign io_tlbentry_global_ppn0 = tlbelo0[27:8];
  assign io_tlbentry_global_plv0 = tlbelo0[3:2];
  assign io_tlbentry_global_mat0 = tlbelo0[5:4];
  assign io_tlbentry_global_d0 = tlbelo0[1];
  assign io_tlbentry_global_v0 = tlbelo0[0];
  assign io_tlbentry_global_ppn1 = tlbelo1[27:8];
  assign io_tlbentry_global_plv1 = tlbelo1[3:2];
  assign io_tlbentry_global_mat1 = tlbelo1[5:4];
  assign io_tlbentry_global_d1 = tlbelo1[1];
  assign io_tlbentry_global_v1 = tlbelo1[0];
  assign io_llbit_global = llbctl[0];
  assign io_csr_reg_crmd =
    io_exception[7] ? {crmd[31:5], _io_csr_reg_crmd_T_2, 3'h0} : _GEN_59;
  assign io_csr_reg_prmd = io_exception[7] ? {prmd[31:3], crmd[2:0]} : _GEN_60;
  assign io_csr_reg_estat =
    io_exception[7] ? {9'h0, io_exception[6:0], estat[15:0]} : {1'h0, _GEN_61};
  assign io_csr_reg_euen = _GEN_1 ? {31'h0, io_wdata[0]} : euen;
  assign io_csr_reg_ecfg = _GEN_2 ? {19'h0, io_wdata[12:11], 1'h0, io_wdata[9:0]} : ecfg;
  assign io_csr_reg_era = io_exception[7] ? io_pc_exp : _GEN_5;
  assign io_csr_reg_badv = _GEN_6 ? io_badv_exp : _GEN_8;
  assign io_csr_reg_eentry = _GEN_9 ? {io_wdata[31:6], 6'h0} : eentry;
  assign io_csr_reg_cpuid = _GEN_10 ? {23'h0, io_wdata[8:0]} : cpuid;
  assign io_csr_reg_save0 = _GEN_11 ? io_wdata : save0;
  assign io_csr_reg_save1 = _GEN_12 ? io_wdata : save1;
  assign io_csr_reg_save2 = _GEN_13 ? io_wdata : save2;
  assign io_csr_reg_save3 = _GEN_14 ? io_wdata : save3;
  assign io_csr_reg_llbctl = io_llbit_set ? {llbctl[31:1], 1'h1} : _GEN_64;
  assign io_csr_reg_tlbidx = io_tlbsrch_en ? _GEN_65 : _GEN_67;
  assign io_csr_reg_tlbehi = _GEN_17 ? {io_badv_exp[31:13], 13'h0} : _GEN_69;
  assign io_csr_reg_tlbelo0 = io_tlbrd_en ? _io_csr_reg_tlbelo0_T_8 : _GEN_70;
  assign io_csr_reg_tlbelo1 = io_tlbrd_en ? _io_csr_reg_tlbelo1_T_8 : _GEN_71;
  assign io_csr_reg_asid = io_tlbrd_en ? {asid[31:10], _io_csr_reg_asid_T_1} : _GEN_72;
  assign io_csr_reg_pgdl = _GEN_22 ? {io_wdata[31:12], 12'h0} : pgdl;
  assign io_csr_reg_pgdh = _GEN_23 ? {io_wdata[31:12], 12'h0} : pgdh;
  assign io_csr_reg_pgd = _GEN_24 ? {io_wdata[31:12], 12'h0} : pgd;
  assign io_csr_reg_tlbrentry = _GEN_25 ? {io_wdata[31:6], 6'h0} : tlbrentry;
  assign io_csr_reg_dmw0 =
    _GEN_26
      ? {io_wdata[31:29], 1'h0, io_wdata[27:25], 19'h0, io_wdata[5:3], 2'h0, io_wdata[0]}
      : dmw0;
  assign io_csr_reg_dmw1 =
    _GEN_27
      ? {io_wdata[31:29], 1'h0, io_wdata[27:25], 19'h0, io_wdata[5:3], 2'h0, io_wdata[0]}
      : dmw1;
  assign io_csr_reg_tid = _GEN_28 ? io_wdata : tid;
  assign io_csr_reg_tcfg = _GEN_29 ? {2'h0, io_wdata[29:0]} : tcfg;
  assign io_csr_reg_tval = _GEN_29 ? {2'h0, io_wdata[29:2], 2'h1} : _GEN_74;
endmodule

