// Generated by CIRCT firtool-1.62.0
module Dcache(
  input         clock,
                reset,
  input  [31:0] io_addr_EX,
                io_wdata_EX,
  input  [4:0]  io_mem_type_EX,
  input         io_store_cmt_EX,
                io_cacop_en,
  input  [1:0]  io_cacop_op,
  input         io_uncache,
  input  [4:0]  io_rob_index_TC,
  input  [31:0] io_paddr_TC,
  input         io_exception,
  input  [4:0]  io_rob_index_CMT,
  output [31:0] io_rdata_MEM,
  input         io_d_rready,
                io_d_rlast,
  input  [31:0] io_d_rdata,
  output        io_d_rvalid,
  output [31:0] io_d_raddr,
  output [2:0]  io_d_rsize,
  output [7:0]  io_d_rlen,
  input         io_d_wready,
                io_d_bvalid,
  output [31:0] io_d_waddr,
                io_d_wdata,
  output [7:0]  io_d_wlen,
  output [2:0]  io_d_wsize,
  output [3:0]  io_d_wmask,
  output        io_d_wvalid,
                io_d_wlast,
                io_d_bready,
  input         io_stall,
                io_flush,
  output        io_cache_miss
);

  wire              wrt_finish;
  wire              addr_sel;
  wire              data_sel;
  wire [4:0]        _xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_1_addra;
  wire [255:0]      _xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_1_doutb;
  wire [4:0]        _xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_addra;
  wire [255:0]      _xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_doutb;
  wire [4:0]        _xilinx_simple_dual_port_1_clock_ram_write_first_1_addra;
  wire              _xilinx_simple_dual_port_1_clock_ram_write_first_1_wea;
  wire [22:0]       _xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb;
  wire [4:0]        _xilinx_simple_dual_port_1_clock_ram_write_first_addra;
  wire              _xilinx_simple_dual_port_1_clock_ram_write_first_wea;
  wire [22:0]       _xilinx_simple_dual_port_1_clock_ram_write_first_doutb;
  reg  [31:0]       addr_reg_EX_TC;
  reg  [4:0]        mem_type_reg_EX_TC;
  reg  [31:0]       wdata_reg_EX_TC;
  reg               store_cmt_reg_EX_TC;
  reg               cacop_en_reg_EX_TC;
  reg  [1:0]        cacop_op_reg_EX_TC;
  reg               flush_reg_EX_TC;
  wire [4:0]        tag_addrb_0 = addr_sel ? addr_reg_EX_TC[9:5] : io_addr_EX[9:5];
  wire [4:0]        cmem_addrb_0 = addr_sel ? addr_reg_EX_TC[9:5] : io_addr_EX[9:5];
  wire [4:0]        tag_addrb_1 = addr_sel ? addr_reg_EX_TC[9:5] : io_addr_EX[9:5];
  wire [4:0]        cmem_addrb_1 = addr_sel ? addr_reg_EX_TC[9:5] : io_addr_EX[9:5];
  reg  [31:0]       paddr_reg_TC_MEM;
  reg  [4:0]        mem_type_reg_TC_MEM;
  reg  [31:0]       wdata_reg_TC_MEM;
  reg               uncache_reg_TC_MEM;
  reg  [1:0]        hit_reg_TC_MEM;
  reg  [21:0]       tag_r_reg_TC_MEM_0;
  reg  [21:0]       tag_r_reg_TC_MEM_1;
  reg               cacop_en_reg_TC_MEM;
  reg  [1:0]        cacop_op_reg_TC_MEM;
  reg               flush_reg_TC_MEM;
  reg  [255:0]      cmem_rdata_reg_TC_MEM_0;
  reg  [255:0]      cmem_rdata_reg_TC_MEM_1;
  reg               exception_reg_TC_MEM;
  reg  [4:0]        rob_index_reg_TC_MEM;
  wire              cacop_way_MEM =
    cacop_op_reg_TC_MEM[1] ? hit_reg_TC_MEM[1] : paddr_reg_TC_MEM[0];
  wire              cacop_exec_MEM = ~(cacop_op_reg_TC_MEM[1]) | (|hit_reg_TC_MEM);
  reg               lru_mem_0;
  reg               lru_mem_1;
  reg               lru_mem_2;
  reg               lru_mem_3;
  reg               lru_mem_4;
  reg               lru_mem_5;
  reg               lru_mem_6;
  reg               lru_mem_7;
  reg               lru_mem_8;
  reg               lru_mem_9;
  reg               lru_mem_10;
  reg               lru_mem_11;
  reg               lru_mem_12;
  reg               lru_mem_13;
  reg               lru_mem_14;
  reg               lru_mem_15;
  reg               lru_mem_16;
  reg               lru_mem_17;
  reg               lru_mem_18;
  reg               lru_mem_19;
  reg               lru_mem_20;
  reg               lru_mem_21;
  reg               lru_mem_22;
  reg               lru_mem_23;
  reg               lru_mem_24;
  reg               lru_mem_25;
  reg               lru_mem_26;
  reg               lru_mem_27;
  reg               lru_mem_28;
  reg               lru_mem_29;
  reg               lru_mem_30;
  reg               lru_mem_31;
  wire [31:0]       _GEN =
    {{lru_mem_31},
     {lru_mem_30},
     {lru_mem_29},
     {lru_mem_28},
     {lru_mem_27},
     {lru_mem_26},
     {lru_mem_25},
     {lru_mem_24},
     {lru_mem_23},
     {lru_mem_22},
     {lru_mem_21},
     {lru_mem_20},
     {lru_mem_19},
     {lru_mem_18},
     {lru_mem_17},
     {lru_mem_16},
     {lru_mem_15},
     {lru_mem_14},
     {lru_mem_13},
     {lru_mem_12},
     {lru_mem_11},
     {lru_mem_10},
     {lru_mem_9},
     {lru_mem_8},
     {lru_mem_7},
     {lru_mem_6},
     {lru_mem_5},
     {lru_mem_4},
     {lru_mem_3},
     {lru_mem_2},
     {lru_mem_1},
     {lru_mem_0}};
  wire              _GEN_0 = _GEN[paddr_reg_TC_MEM[9:5]];
  reg  [255:0]      ret_buf;
  wire [255:0]      _GEN_1 =
    hit_reg_TC_MEM[1] ? cmem_rdata_reg_TC_MEM_1 : cmem_rdata_reg_TC_MEM_0;
  wire [31:0][31:0] _GEN_2 =
    {{{24'h0, ret_buf[255:248]}},
     {{16'h0, ret_buf[255:240]}},
     {{8'h0, ret_buf[255:232]}},
     {ret_buf[255:224]},
     {ret_buf[247:216]},
     {ret_buf[239:208]},
     {ret_buf[231:200]},
     {ret_buf[223:192]},
     {ret_buf[215:184]},
     {ret_buf[207:176]},
     {ret_buf[199:168]},
     {ret_buf[191:160]},
     {ret_buf[183:152]},
     {ret_buf[175:144]},
     {ret_buf[167:136]},
     {ret_buf[159:128]},
     {ret_buf[151:120]},
     {ret_buf[143:112]},
     {ret_buf[135:104]},
     {ret_buf[127:96]},
     {ret_buf[119:88]},
     {ret_buf[111:80]},
     {ret_buf[103:72]},
     {ret_buf[95:64]},
     {ret_buf[87:56]},
     {ret_buf[79:48]},
     {ret_buf[71:40]},
     {ret_buf[63:32]},
     {ret_buf[55:24]},
     {ret_buf[47:16]},
     {ret_buf[39:8]},
     {ret_buf[31:0]}};
  wire [31:0]       _rdata_temp_T_2 =
    uncache_reg_TC_MEM ? ret_buf[255:224] : _GEN_2[paddr_reg_TC_MEM[4:0]];
  wire [31:0][31:0] _GEN_3 =
    {{{24'h0, _GEN_1[255:248]}},
     {{16'h0, _GEN_1[255:240]}},
     {{8'h0, _GEN_1[255:232]}},
     {_GEN_1[255:224]},
     {_GEN_1[247:216]},
     {_GEN_1[239:208]},
     {_GEN_1[231:200]},
     {_GEN_1[223:192]},
     {_GEN_1[215:184]},
     {_GEN_1[207:176]},
     {_GEN_1[199:168]},
     {_GEN_1[191:160]},
     {_GEN_1[183:152]},
     {_GEN_1[175:144]},
     {_GEN_1[167:136]},
     {_GEN_1[159:128]},
     {_GEN_1[151:120]},
     {_GEN_1[143:112]},
     {_GEN_1[135:104]},
     {_GEN_1[127:96]},
     {_GEN_1[119:88]},
     {_GEN_1[111:80]},
     {_GEN_1[103:72]},
     {_GEN_1[95:64]},
     {_GEN_1[87:56]},
     {_GEN_1[79:48]},
     {_GEN_1[71:40]},
     {_GEN_1[63:32]},
     {_GEN_1[55:24]},
     {_GEN_1[47:16]},
     {_GEN_1[39:8]},
     {_GEN_1[31:0]}};
  wire [31:0]       rdata_temp =
    data_sel ? _rdata_temp_T_2 : _GEN_3[paddr_reg_TC_MEM[4:0]];
  wire [31:0]       _GEN_4 =
    mem_type_reg_TC_MEM[1:0] == 2'h1 ? 32'hFFFF : {32{mem_type_reg_TC_MEM[1:0] == 2'h2}};
  wire [31:0]       rmask = mem_type_reg_TC_MEM[1:0] == 2'h0 ? 32'hFF : _GEN_4;
  reg               dirty_table_0_0;
  reg               dirty_table_0_1;
  reg               dirty_table_0_2;
  reg               dirty_table_0_3;
  reg               dirty_table_0_4;
  reg               dirty_table_0_5;
  reg               dirty_table_0_6;
  reg               dirty_table_0_7;
  reg               dirty_table_0_8;
  reg               dirty_table_0_9;
  reg               dirty_table_0_10;
  reg               dirty_table_0_11;
  reg               dirty_table_0_12;
  reg               dirty_table_0_13;
  reg               dirty_table_0_14;
  reg               dirty_table_0_15;
  reg               dirty_table_0_16;
  reg               dirty_table_0_17;
  reg               dirty_table_0_18;
  reg               dirty_table_0_19;
  reg               dirty_table_0_20;
  reg               dirty_table_0_21;
  reg               dirty_table_0_22;
  reg               dirty_table_0_23;
  reg               dirty_table_0_24;
  reg               dirty_table_0_25;
  reg               dirty_table_0_26;
  reg               dirty_table_0_27;
  reg               dirty_table_0_28;
  reg               dirty_table_0_29;
  reg               dirty_table_0_30;
  reg               dirty_table_0_31;
  reg               dirty_table_1_0;
  reg               dirty_table_1_1;
  reg               dirty_table_1_2;
  reg               dirty_table_1_3;
  reg               dirty_table_1_4;
  reg               dirty_table_1_5;
  reg               dirty_table_1_6;
  reg               dirty_table_1_7;
  reg               dirty_table_1_8;
  reg               dirty_table_1_9;
  reg               dirty_table_1_10;
  reg               dirty_table_1_11;
  reg               dirty_table_1_12;
  reg               dirty_table_1_13;
  reg               dirty_table_1_14;
  reg               dirty_table_1_15;
  reg               dirty_table_1_16;
  reg               dirty_table_1_17;
  reg               dirty_table_1_18;
  reg               dirty_table_1_19;
  reg               dirty_table_1_20;
  reg               dirty_table_1_21;
  reg               dirty_table_1_22;
  reg               dirty_table_1_23;
  reg               dirty_table_1_24;
  reg               dirty_table_1_25;
  reg               dirty_table_1_26;
  reg               dirty_table_1_27;
  reg               dirty_table_1_28;
  reg               dirty_table_1_29;
  reg               dirty_table_1_30;
  reg               dirty_table_1_31;
  wire [22:0]       _tag_dina_1_T = {1'h1, paddr_reg_TC_MEM[31:10]};
  wire [22:0]       tag_dina_0 = cacop_en_reg_TC_MEM ? 23'h0 : _tag_dina_1_T;
  wire [22:0]       tag_dina_1 = cacop_en_reg_TC_MEM ? 23'h0 : _tag_dina_1_T;
  wire [510:0]      _GEN_5 = {503'h0, paddr_reg_TC_MEM[4:0], 3'h0};
  wire [510:0]      _wmask_T_1 = {479'h0, rmask} << _GEN_5;
  wire [255:0]      wmask = mem_type_reg_TC_MEM[2] ? _wmask_T_1[255:0] : 256'h0;
  wire [510:0]      wdata_refill = {479'h0, wdata_reg_TC_MEM} << _GEN_5;
  wire [31:0]       wmask_byte =
    {wmask[248],
     wmask[240],
     wmask[232],
     wmask[224],
     wmask[216],
     wmask[208],
     wmask[200],
     wmask[192],
     wmask[184],
     wmask[176],
     wmask[168],
     wmask[160],
     wmask[152],
     wmask[144],
     wmask[136],
     wmask[128],
     wmask[120],
     wmask[112],
     wmask[104],
     wmask[96],
     wmask[88],
     wmask[80],
     wmask[72],
     wmask[64],
     wmask[56],
     wmask[48],
     wmask[40],
     wmask[32],
     wmask[24],
     wmask[16],
     wmask[8],
     wmask[0]};
  wire [255:0]      cmem_dina_0 = wmask & wdata_refill[255:0] | ~wmask & ret_buf;
  reg  [287:0]      wrt_buf;
  reg  [2:0]        state;
  wire              _GEN_6 = state == 3'h0;
  wire              _GEN_7 =
    cacop_en_reg_TC_MEM
      ? cacop_exec_MEM
      : mem_type_reg_TC_MEM[4] & (uncache_reg_TC_MEM | ~(|hit_reg_TC_MEM));
  assign data_sel =
    ~_GEN_6 | cacop_en_reg_TC_MEM | ~(mem_type_reg_TC_MEM[4]) | uncache_reg_TC_MEM;
  wire              _dirty_we_T = mem_type_reg_TC_MEM[2] & (|hit_reg_TC_MEM);
  wire [31:0]       _GEN_8 =
    cacop_en_reg_TC_MEM | ~(mem_type_reg_TC_MEM[4]) | uncache_reg_TC_MEM
    | ~(~(hit_reg_TC_MEM[1]) & _dirty_we_T)
      ? 32'h0
      : wmask_byte;
  wire [31:0]       _GEN_9 =
    cacop_en_reg_TC_MEM | ~(mem_type_reg_TC_MEM[4]) | uncache_reg_TC_MEM
    | ~(hit_reg_TC_MEM[1] & _dirty_we_T)
      ? 32'h0
      : wmask_byte;
  wire              _GEN_10 =
    cacop_en_reg_TC_MEM ? cacop_exec_MEM : mem_type_reg_TC_MEM[4] & uncache_reg_TC_MEM;
  wire              _GEN_11 = state == 3'h1;
  wire              _GEN_12 = state == 3'h2;
  wire              tag_idx = cacop_en_reg_TC_MEM ? cacop_way_MEM : _GEN_0;
  wire              _GEN_13 = _GEN_6 | _GEN_11;
  wire              lru_miss_upd = ~_GEN_13 & _GEN_12 & ~cacop_en_reg_TC_MEM;
  wire [31:0]       _GEN_14 =
    _GEN_11 | ~(_GEN_12 & ~_GEN_0) | cacop_en_reg_TC_MEM ? 32'h0 : 32'hFFFFFFFF;
  wire [31:0]       cmem_we_0 = _GEN_6 ? _GEN_8 : _GEN_14;
  wire [31:0]       _GEN_15 =
    _GEN_11 | ~(_GEN_12 & _GEN_0) | cacop_en_reg_TC_MEM ? 32'h0 : 32'hFFFFFFFF;
  wire [31:0]       cmem_we_1 = _GEN_6 ? _GEN_9 : _GEN_15;
  wire              dirty_clean =
    ~_GEN_13 & _GEN_12 & (~(mem_type_reg_TC_MEM[2]) | cacop_en_reg_TC_MEM);
  wire              _GEN_16 = state == 3'h3;
  wire              _GEN_17 = state == 3'h4;
  wire              _wbuf_we_T_1 = flush_reg_TC_MEM | exception_reg_TC_MEM;
  wire              _GEN_18 = _GEN_16 ? ~wrt_finish : _GEN_17 & ~_wbuf_we_T_1;
  wire              _GEN_19 = _GEN_11 | _GEN_12;
  assign addr_sel = _GEN_6 ? _GEN_10 : _GEN_19 | _GEN_18;
  wire              _GEN_20 = _GEN_16 ? ~wrt_finish : _GEN_17 & ~flush_reg_TC_MEM;
  wire              cache_miss_MEM = _GEN_6 ? _GEN_7 : _GEN_19 | _GEN_20;
  reg  [7:0]        wrt_count;
  wire [2:0]        wrt_num = uncache_reg_TC_MEM ? 3'h0 : 3'h7;
  wire [7:0]        io_d_wlen_0 = {5'h0, wrt_num};
  reg  [1:0]        wrt_state;
  wire              _GEN_21 = wrt_state == 2'h0;
  wire              _GEN_22 = wrt_state == 2'h1;
  wire              d_wvalid = ~_GEN_21 & _GEN_22 & wrt_count != 8'hFF;
  assign wrt_finish = ~(_GEN_21 | _GEN_22) & wrt_state == 2'h2 & ~io_stall;
  wire [1:0]        _io_d_rsize_T_1 =
    uncache_reg_TC_MEM ? mem_type_reg_TC_MEM[1:0] : 2'h2;
  wire [15:0]       _io_d_wmask_T_2 = 16'h1 << (4'h1 << mem_type_reg_TC_MEM[1:0]);
  wire [1:0]        _io_d_wsize_T_1 =
    uncache_reg_TC_MEM ? mem_type_reg_TC_MEM[1:0] : 2'h2;
  wire              uncache_TC = ~store_cmt_reg_EX_TC & (flush_reg_EX_TC | io_uncache);
  wire [21:0]       tag_TC =
    store_cmt_reg_EX_TC ? addr_reg_EX_TC[31:10] : io_paddr_TC[31:10];
  wire              write_way = (|hit_reg_TC_MEM) ? hit_reg_TC_MEM[1] : _GEN_0;
  wire [21:0]       _GEN_23 = _GEN_0 ? tag_r_reg_TC_MEM_1 : tag_r_reg_TC_MEM_0;
  wire [255:0]      _GEN_24 = _GEN_0 ? cmem_rdata_reg_TC_MEM_1 : cmem_rdata_reg_TC_MEM_0;
  wire [287:0]      _GEN_25 =
    uncache_reg_TC_MEM
      ? {224'h0, wdata_reg_TC_MEM, paddr_reg_TC_MEM}
      : {_GEN_24, _GEN_23, paddr_reg_TC_MEM[9:5], 5'h0};
  wire              cmem_wb_idx =
    cacop_op_reg_TC_MEM[1] ? hit_reg_TC_MEM[1] : paddr_reg_TC_MEM[0];
  wire [255:0]      _GEN_26 =
    cmem_wb_idx ? cmem_rdata_reg_TC_MEM_1 : cmem_rdata_reg_TC_MEM_0;
  wire              _EX_TC_en_T = io_stall | cache_miss_MEM;
  wire              _GEN_27 = paddr_reg_TC_MEM[9:5] == 5'h0;
  wire              _GEN_28 = paddr_reg_TC_MEM[9:5] == 5'h1;
  wire              _GEN_29 = paddr_reg_TC_MEM[9:5] == 5'h2;
  wire              _GEN_30 = paddr_reg_TC_MEM[9:5] == 5'h3;
  wire              _GEN_31 = paddr_reg_TC_MEM[9:5] == 5'h4;
  wire              _GEN_32 = paddr_reg_TC_MEM[9:5] == 5'h5;
  wire              _GEN_33 = paddr_reg_TC_MEM[9:5] == 5'h6;
  wire              _GEN_34 = paddr_reg_TC_MEM[9:5] == 5'h7;
  wire              _GEN_35 = paddr_reg_TC_MEM[9:5] == 5'h8;
  wire              _GEN_36 = paddr_reg_TC_MEM[9:5] == 5'h9;
  wire              _GEN_37 = paddr_reg_TC_MEM[9:5] == 5'hA;
  wire              _GEN_38 = paddr_reg_TC_MEM[9:5] == 5'hB;
  wire              _GEN_39 = paddr_reg_TC_MEM[9:5] == 5'hC;
  wire              _GEN_40 = paddr_reg_TC_MEM[9:5] == 5'hD;
  wire              _GEN_41 = paddr_reg_TC_MEM[9:5] == 5'hE;
  wire              _GEN_42 = paddr_reg_TC_MEM[9:5] == 5'hF;
  wire              _GEN_43 = paddr_reg_TC_MEM[9:5] == 5'h10;
  wire              _GEN_44 = paddr_reg_TC_MEM[9:5] == 5'h11;
  wire              _GEN_45 = paddr_reg_TC_MEM[9:5] == 5'h12;
  wire              _GEN_46 = paddr_reg_TC_MEM[9:5] == 5'h13;
  wire              _GEN_47 = paddr_reg_TC_MEM[9:5] == 5'h14;
  wire              _GEN_48 = paddr_reg_TC_MEM[9:5] == 5'h15;
  wire              _GEN_49 = paddr_reg_TC_MEM[9:5] == 5'h16;
  wire              _GEN_50 = paddr_reg_TC_MEM[9:5] == 5'h17;
  wire              _GEN_51 = paddr_reg_TC_MEM[9:5] == 5'h18;
  wire              _GEN_52 = paddr_reg_TC_MEM[9:5] == 5'h19;
  wire              _GEN_53 = paddr_reg_TC_MEM[9:5] == 5'h1A;
  wire              _GEN_54 = paddr_reg_TC_MEM[9:5] == 5'h1B;
  wire              _GEN_55 = paddr_reg_TC_MEM[9:5] == 5'h1C;
  wire              _GEN_56 = paddr_reg_TC_MEM[9:5] == 5'h1D;
  wire              _GEN_57 = paddr_reg_TC_MEM[9:5] == 5'h1E;
  wire              _GEN_58 =
    cacop_en_reg_TC_MEM
      ? cacop_exec_MEM
      : mem_type_reg_TC_MEM[4] & ~uncache_reg_TC_MEM & ~(|hit_reg_TC_MEM);
  wire              confirm_exec = io_rob_index_CMT == rob_index_reg_TC_MEM;
  wire              _GEN_59 = _GEN_11 | _GEN_12 | _GEN_16;
  wire              wfsm_en =
    _GEN_6 ? _GEN_58 : ~_GEN_59 & _GEN_17 & confirm_exec & ~_wbuf_we_T_1;
  wire [31:0]       _GEN_60 =
    _GEN_0
      ? {{dirty_table_1_31},
         {dirty_table_1_30},
         {dirty_table_1_29},
         {dirty_table_1_28},
         {dirty_table_1_27},
         {dirty_table_1_26},
         {dirty_table_1_25},
         {dirty_table_1_24},
         {dirty_table_1_23},
         {dirty_table_1_22},
         {dirty_table_1_21},
         {dirty_table_1_20},
         {dirty_table_1_19},
         {dirty_table_1_18},
         {dirty_table_1_17},
         {dirty_table_1_16},
         {dirty_table_1_15},
         {dirty_table_1_14},
         {dirty_table_1_13},
         {dirty_table_1_12},
         {dirty_table_1_11},
         {dirty_table_1_10},
         {dirty_table_1_9},
         {dirty_table_1_8},
         {dirty_table_1_7},
         {dirty_table_1_6},
         {dirty_table_1_5},
         {dirty_table_1_4},
         {dirty_table_1_3},
         {dirty_table_1_2},
         {dirty_table_1_1},
         {dirty_table_1_0}}
      : {{dirty_table_0_31},
         {dirty_table_0_30},
         {dirty_table_0_29},
         {dirty_table_0_28},
         {dirty_table_0_27},
         {dirty_table_0_26},
         {dirty_table_0_25},
         {dirty_table_0_24},
         {dirty_table_0_23},
         {dirty_table_0_22},
         {dirty_table_0_21},
         {dirty_table_0_20},
         {dirty_table_0_19},
         {dirty_table_0_18},
         {dirty_table_0_17},
         {dirty_table_0_16},
         {dirty_table_0_15},
         {dirty_table_0_14},
         {dirty_table_0_13},
         {dirty_table_0_12},
         {dirty_table_0_11},
         {dirty_table_0_10},
         {dirty_table_0_9},
         {dirty_table_0_8},
         {dirty_table_0_7},
         {dirty_table_0_6},
         {dirty_table_0_5},
         {dirty_table_0_4},
         {dirty_table_0_3},
         {dirty_table_0_2},
         {dirty_table_0_1},
         {dirty_table_0_0}};
  wire              _GEN_61 = _GEN_60[paddr_reg_TC_MEM[9:5]];
  wire              dirty_we =
    _GEN_6
      ? ~cacop_en_reg_TC_MEM & mem_type_reg_TC_MEM[4] & ~uncache_reg_TC_MEM & _dirty_we_T
      : ~_GEN_11 & _GEN_12 & mem_type_reg_TC_MEM[2];
  wire              wbuf_we =
    _GEN_6 ? _GEN_58 : ~_GEN_59 & _GEN_17 & confirm_exec & ~_wbuf_we_T_1;
  wire [2:0]        _state_T_8 =
    confirm_exec ? {1'h0, mem_type_reg_TC_MEM[2], 1'h1} : 3'h4;
  wire [2:0]        _state_T_9 = _wbuf_we_T_1 ? 3'h0 : _state_T_8;
  wire [2:0]        _state_T_5 = wrt_finish ? 3'h0 : 3'h3;
  wire [2:0]        _state_T_4 =
    io_d_rready & io_d_rlast ? {2'h1, uncache_reg_TC_MEM} : 3'h1;
  wire [2:0]        _GEN_62 = uncache_reg_TC_MEM ? 3'h4 : {2'h0, ~(|hit_reg_TC_MEM)};
  wire [2:0]        _GEN_63 = mem_type_reg_TC_MEM[4] ? _GEN_62 : state;
  wire [2:0]        _GEN_64 =
    cacop_en_reg_TC_MEM ? {1'h0, cacop_exec_MEM, 1'h0} : _GEN_63;
  wire [7:0][2:0]   _GEN_65 =
    {{state},
     {state},
     {state},
     {_state_T_9},
     {_state_T_5},
     {3'h3},
     {_state_T_4},
     {_GEN_64}};
  wire [1:0]        _wrt_state_T_5 = io_d_bvalid ? 2'h2 : 2'h1;
  wire              _GEN_66 = uncache_reg_TC_MEM ? mem_type_reg_TC_MEM[2] : _GEN_61;
  wire [1:0]        _GEN_67 = _GEN_66 ? 2'h1 : 2'h2;
  wire [1:0]        _wrt_state_T_2 = cacop_op_reg_TC_MEM == 2'h0 | ~_GEN_61 ? 2'h2 : 2'h1;
  wire [1:0]        _GEN_68 = cacop_en_reg_TC_MEM ? _wrt_state_T_2 : _GEN_67;
  wire [1:0]        _GEN_69 = wfsm_en ? _GEN_68 : wrt_state;
  wire [3:0][1:0]   _GEN_70 =
    {{wrt_state},
     {{~(~(_GEN_6 | _GEN_19) & (_GEN_16 | _GEN_17 & _wbuf_we_T_1) & ~io_stall), 1'h0}},
     {_wrt_state_T_5},
     {_GEN_69}};
  always @(posedge clock) begin
    if (reset) begin
      addr_reg_EX_TC <= 32'h0;
      mem_type_reg_EX_TC <= 5'h0;
      wdata_reg_EX_TC <= 32'h0;
      store_cmt_reg_EX_TC <= 1'h0;
      cacop_en_reg_EX_TC <= 1'h0;
      cacop_op_reg_EX_TC <= 2'h0;
      flush_reg_EX_TC <= 1'h0;
      paddr_reg_TC_MEM <= 32'h0;
      mem_type_reg_TC_MEM <= 5'h0;
      wdata_reg_TC_MEM <= 32'h0;
      uncache_reg_TC_MEM <= 1'h0;
      hit_reg_TC_MEM <= 2'h0;
      tag_r_reg_TC_MEM_0 <= 22'h0;
      tag_r_reg_TC_MEM_1 <= 22'h0;
      cacop_en_reg_TC_MEM <= 1'h0;
      cacop_op_reg_TC_MEM <= 2'h0;
      flush_reg_TC_MEM <= 1'h0;
      cmem_rdata_reg_TC_MEM_0 <= 256'h0;
      cmem_rdata_reg_TC_MEM_1 <= 256'h0;
      exception_reg_TC_MEM <= 1'h0;
      rob_index_reg_TC_MEM <= 5'h0;
      lru_mem_0 <= 1'h0;
      lru_mem_1 <= 1'h0;
      lru_mem_2 <= 1'h0;
      lru_mem_3 <= 1'h0;
      lru_mem_4 <= 1'h0;
      lru_mem_5 <= 1'h0;
      lru_mem_6 <= 1'h0;
      lru_mem_7 <= 1'h0;
      lru_mem_8 <= 1'h0;
      lru_mem_9 <= 1'h0;
      lru_mem_10 <= 1'h0;
      lru_mem_11 <= 1'h0;
      lru_mem_12 <= 1'h0;
      lru_mem_13 <= 1'h0;
      lru_mem_14 <= 1'h0;
      lru_mem_15 <= 1'h0;
      lru_mem_16 <= 1'h0;
      lru_mem_17 <= 1'h0;
      lru_mem_18 <= 1'h0;
      lru_mem_19 <= 1'h0;
      lru_mem_20 <= 1'h0;
      lru_mem_21 <= 1'h0;
      lru_mem_22 <= 1'h0;
      lru_mem_23 <= 1'h0;
      lru_mem_24 <= 1'h0;
      lru_mem_25 <= 1'h0;
      lru_mem_26 <= 1'h0;
      lru_mem_27 <= 1'h0;
      lru_mem_28 <= 1'h0;
      lru_mem_29 <= 1'h0;
      lru_mem_30 <= 1'h0;
      lru_mem_31 <= 1'h0;
      ret_buf <= 256'h0;
      dirty_table_0_0 <= 1'h0;
      dirty_table_0_1 <= 1'h0;
      dirty_table_0_2 <= 1'h0;
      dirty_table_0_3 <= 1'h0;
      dirty_table_0_4 <= 1'h0;
      dirty_table_0_5 <= 1'h0;
      dirty_table_0_6 <= 1'h0;
      dirty_table_0_7 <= 1'h0;
      dirty_table_0_8 <= 1'h0;
      dirty_table_0_9 <= 1'h0;
      dirty_table_0_10 <= 1'h0;
      dirty_table_0_11 <= 1'h0;
      dirty_table_0_12 <= 1'h0;
      dirty_table_0_13 <= 1'h0;
      dirty_table_0_14 <= 1'h0;
      dirty_table_0_15 <= 1'h0;
      dirty_table_0_16 <= 1'h0;
      dirty_table_0_17 <= 1'h0;
      dirty_table_0_18 <= 1'h0;
      dirty_table_0_19 <= 1'h0;
      dirty_table_0_20 <= 1'h0;
      dirty_table_0_21 <= 1'h0;
      dirty_table_0_22 <= 1'h0;
      dirty_table_0_23 <= 1'h0;
      dirty_table_0_24 <= 1'h0;
      dirty_table_0_25 <= 1'h0;
      dirty_table_0_26 <= 1'h0;
      dirty_table_0_27 <= 1'h0;
      dirty_table_0_28 <= 1'h0;
      dirty_table_0_29 <= 1'h0;
      dirty_table_0_30 <= 1'h0;
      dirty_table_0_31 <= 1'h0;
      dirty_table_1_0 <= 1'h0;
      dirty_table_1_1 <= 1'h0;
      dirty_table_1_2 <= 1'h0;
      dirty_table_1_3 <= 1'h0;
      dirty_table_1_4 <= 1'h0;
      dirty_table_1_5 <= 1'h0;
      dirty_table_1_6 <= 1'h0;
      dirty_table_1_7 <= 1'h0;
      dirty_table_1_8 <= 1'h0;
      dirty_table_1_9 <= 1'h0;
      dirty_table_1_10 <= 1'h0;
      dirty_table_1_11 <= 1'h0;
      dirty_table_1_12 <= 1'h0;
      dirty_table_1_13 <= 1'h0;
      dirty_table_1_14 <= 1'h0;
      dirty_table_1_15 <= 1'h0;
      dirty_table_1_16 <= 1'h0;
      dirty_table_1_17 <= 1'h0;
      dirty_table_1_18 <= 1'h0;
      dirty_table_1_19 <= 1'h0;
      dirty_table_1_20 <= 1'h0;
      dirty_table_1_21 <= 1'h0;
      dirty_table_1_22 <= 1'h0;
      dirty_table_1_23 <= 1'h0;
      dirty_table_1_24 <= 1'h0;
      dirty_table_1_25 <= 1'h0;
      dirty_table_1_26 <= 1'h0;
      dirty_table_1_27 <= 1'h0;
      dirty_table_1_28 <= 1'h0;
      dirty_table_1_29 <= 1'h0;
      dirty_table_1_30 <= 1'h0;
      dirty_table_1_31 <= 1'h0;
      wrt_buf <= 288'h0;
      state <= 3'h0;
      wrt_count <= 8'h0;
      wrt_state <= 2'h0;
    end
    else begin
      if (~_EX_TC_en_T) begin
        addr_reg_EX_TC <= io_addr_EX;
        mem_type_reg_EX_TC <= io_mem_type_EX;
        wdata_reg_EX_TC <= io_wdata_EX;
        store_cmt_reg_EX_TC <= io_store_cmt_EX;
        cacop_en_reg_EX_TC <= io_cacop_en;
        cacop_op_reg_EX_TC <= io_cacop_op;
        paddr_reg_TC_MEM <=
          store_cmt_reg_EX_TC | flush_reg_EX_TC ? addr_reg_EX_TC : io_paddr_TC;
        mem_type_reg_TC_MEM <=
          ~(mem_type_reg_EX_TC[2]) | uncache_TC | store_cmt_reg_EX_TC
            ? mem_type_reg_EX_TC
            : 5'h0;
        wdata_reg_TC_MEM <= wdata_reg_EX_TC;
        uncache_reg_TC_MEM <= uncache_TC;
        hit_reg_TC_MEM <=
          {_xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb[22]
             & (_xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb[21:0]
                ^ tag_TC) == 22'h0,
           _xilinx_simple_dual_port_1_clock_ram_write_first_doutb[22]
             & (_xilinx_simple_dual_port_1_clock_ram_write_first_doutb[21:0]
                ^ tag_TC) == 22'h0};
        tag_r_reg_TC_MEM_0 <=
          _xilinx_simple_dual_port_1_clock_ram_write_first_doutb[21:0];
        tag_r_reg_TC_MEM_1 <=
          _xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb[21:0];
        cacop_en_reg_TC_MEM <= cacop_en_reg_EX_TC;
        cacop_op_reg_TC_MEM <= cacop_op_reg_EX_TC;
        cmem_rdata_reg_TC_MEM_0 <=
          _xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_doutb;
        cmem_rdata_reg_TC_MEM_1 <=
          _xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_1_doutb;
        rob_index_reg_TC_MEM <= io_rob_index_TC;
      end
      if (~_EX_TC_en_T | io_flush)
        flush_reg_EX_TC <= io_flush;
      if (~_EX_TC_en_T | io_flush)
        flush_reg_TC_MEM <= io_flush ? io_flush : flush_reg_EX_TC;
      exception_reg_TC_MEM <= io_exception;
      if (_GEN_6 & ~cacop_en_reg_TC_MEM & mem_type_reg_TC_MEM[4] & ~uncache_reg_TC_MEM
          & (|hit_reg_TC_MEM)) begin
        if (_GEN_27)
          lru_mem_0 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_28)
          lru_mem_1 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_29)
          lru_mem_2 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_30)
          lru_mem_3 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_31)
          lru_mem_4 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_32)
          lru_mem_5 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_33)
          lru_mem_6 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_34)
          lru_mem_7 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_35)
          lru_mem_8 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_36)
          lru_mem_9 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_37)
          lru_mem_10 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_38)
          lru_mem_11 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_39)
          lru_mem_12 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_40)
          lru_mem_13 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_41)
          lru_mem_14 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_42)
          lru_mem_15 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_43)
          lru_mem_16 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_44)
          lru_mem_17 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_45)
          lru_mem_18 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_46)
          lru_mem_19 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_47)
          lru_mem_20 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_48)
          lru_mem_21 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_49)
          lru_mem_22 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_50)
          lru_mem_23 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_51)
          lru_mem_24 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_52)
          lru_mem_25 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_53)
          lru_mem_26 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_54)
          lru_mem_27 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_55)
          lru_mem_28 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_56)
          lru_mem_29 <= ~(hit_reg_TC_MEM[1]);
        if (_GEN_57)
          lru_mem_30 <= ~(hit_reg_TC_MEM[1]);
        if (&(paddr_reg_TC_MEM[9:5]))
          lru_mem_31 <= ~(hit_reg_TC_MEM[1]);
      end
      else begin
        if (lru_miss_upd & _GEN_27)
          lru_mem_0 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_28)
          lru_mem_1 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_29)
          lru_mem_2 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_30)
          lru_mem_3 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_31)
          lru_mem_4 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_32)
          lru_mem_5 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_33)
          lru_mem_6 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_34)
          lru_mem_7 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_35)
          lru_mem_8 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_36)
          lru_mem_9 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_37)
          lru_mem_10 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_38)
          lru_mem_11 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_39)
          lru_mem_12 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_40)
          lru_mem_13 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_41)
          lru_mem_14 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_42)
          lru_mem_15 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_43)
          lru_mem_16 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_44)
          lru_mem_17 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_45)
          lru_mem_18 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_46)
          lru_mem_19 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_47)
          lru_mem_20 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_48)
          lru_mem_21 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_49)
          lru_mem_22 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_50)
          lru_mem_23 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_51)
          lru_mem_24 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_52)
          lru_mem_25 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_53)
          lru_mem_26 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_54)
          lru_mem_27 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_55)
          lru_mem_28 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_56)
          lru_mem_29 <= ~_GEN_0;
        if (lru_miss_upd & _GEN_57)
          lru_mem_30 <= ~_GEN_0;
        if (lru_miss_upd & (&(paddr_reg_TC_MEM[9:5])))
          lru_mem_31 <= ~_GEN_0;
      end
      if (io_d_rready)
        ret_buf <= {io_d_rdata, ret_buf[255:32]};
      if (dirty_we) begin
        dirty_table_0_0 <= ~write_way & _GEN_27 | dirty_table_0_0;
        dirty_table_0_1 <= ~write_way & _GEN_28 | dirty_table_0_1;
        dirty_table_0_2 <= ~write_way & _GEN_29 | dirty_table_0_2;
        dirty_table_0_3 <= ~write_way & _GEN_30 | dirty_table_0_3;
        dirty_table_0_4 <= ~write_way & _GEN_31 | dirty_table_0_4;
        dirty_table_0_5 <= ~write_way & _GEN_32 | dirty_table_0_5;
        dirty_table_0_6 <= ~write_way & _GEN_33 | dirty_table_0_6;
        dirty_table_0_7 <= ~write_way & _GEN_34 | dirty_table_0_7;
        dirty_table_0_8 <= ~write_way & _GEN_35 | dirty_table_0_8;
        dirty_table_0_9 <= ~write_way & _GEN_36 | dirty_table_0_9;
        dirty_table_0_10 <= ~write_way & _GEN_37 | dirty_table_0_10;
        dirty_table_0_11 <= ~write_way & _GEN_38 | dirty_table_0_11;
        dirty_table_0_12 <= ~write_way & _GEN_39 | dirty_table_0_12;
        dirty_table_0_13 <= ~write_way & _GEN_40 | dirty_table_0_13;
        dirty_table_0_14 <= ~write_way & _GEN_41 | dirty_table_0_14;
        dirty_table_0_15 <= ~write_way & _GEN_42 | dirty_table_0_15;
        dirty_table_0_16 <= ~write_way & _GEN_43 | dirty_table_0_16;
        dirty_table_0_17 <= ~write_way & _GEN_44 | dirty_table_0_17;
        dirty_table_0_18 <= ~write_way & _GEN_45 | dirty_table_0_18;
        dirty_table_0_19 <= ~write_way & _GEN_46 | dirty_table_0_19;
        dirty_table_0_20 <= ~write_way & _GEN_47 | dirty_table_0_20;
        dirty_table_0_21 <= ~write_way & _GEN_48 | dirty_table_0_21;
        dirty_table_0_22 <= ~write_way & _GEN_49 | dirty_table_0_22;
        dirty_table_0_23 <= ~write_way & _GEN_50 | dirty_table_0_23;
        dirty_table_0_24 <= ~write_way & _GEN_51 | dirty_table_0_24;
        dirty_table_0_25 <= ~write_way & _GEN_52 | dirty_table_0_25;
        dirty_table_0_26 <= ~write_way & _GEN_53 | dirty_table_0_26;
        dirty_table_0_27 <= ~write_way & _GEN_54 | dirty_table_0_27;
        dirty_table_0_28 <= ~write_way & _GEN_55 | dirty_table_0_28;
        dirty_table_0_29 <= ~write_way & _GEN_56 | dirty_table_0_29;
        dirty_table_0_30 <= ~write_way & _GEN_57 | dirty_table_0_30;
        dirty_table_0_31 <= ~write_way & (&(paddr_reg_TC_MEM[9:5])) | dirty_table_0_31;
        dirty_table_1_0 <= write_way & _GEN_27 | dirty_table_1_0;
        dirty_table_1_1 <= write_way & _GEN_28 | dirty_table_1_1;
        dirty_table_1_2 <= write_way & _GEN_29 | dirty_table_1_2;
        dirty_table_1_3 <= write_way & _GEN_30 | dirty_table_1_3;
        dirty_table_1_4 <= write_way & _GEN_31 | dirty_table_1_4;
        dirty_table_1_5 <= write_way & _GEN_32 | dirty_table_1_5;
        dirty_table_1_6 <= write_way & _GEN_33 | dirty_table_1_6;
        dirty_table_1_7 <= write_way & _GEN_34 | dirty_table_1_7;
        dirty_table_1_8 <= write_way & _GEN_35 | dirty_table_1_8;
        dirty_table_1_9 <= write_way & _GEN_36 | dirty_table_1_9;
        dirty_table_1_10 <= write_way & _GEN_37 | dirty_table_1_10;
        dirty_table_1_11 <= write_way & _GEN_38 | dirty_table_1_11;
        dirty_table_1_12 <= write_way & _GEN_39 | dirty_table_1_12;
        dirty_table_1_13 <= write_way & _GEN_40 | dirty_table_1_13;
        dirty_table_1_14 <= write_way & _GEN_41 | dirty_table_1_14;
        dirty_table_1_15 <= write_way & _GEN_42 | dirty_table_1_15;
        dirty_table_1_16 <= write_way & _GEN_43 | dirty_table_1_16;
        dirty_table_1_17 <= write_way & _GEN_44 | dirty_table_1_17;
        dirty_table_1_18 <= write_way & _GEN_45 | dirty_table_1_18;
        dirty_table_1_19 <= write_way & _GEN_46 | dirty_table_1_19;
        dirty_table_1_20 <= write_way & _GEN_47 | dirty_table_1_20;
        dirty_table_1_21 <= write_way & _GEN_48 | dirty_table_1_21;
        dirty_table_1_22 <= write_way & _GEN_49 | dirty_table_1_22;
        dirty_table_1_23 <= write_way & _GEN_50 | dirty_table_1_23;
        dirty_table_1_24 <= write_way & _GEN_51 | dirty_table_1_24;
        dirty_table_1_25 <= write_way & _GEN_52 | dirty_table_1_25;
        dirty_table_1_26 <= write_way & _GEN_53 | dirty_table_1_26;
        dirty_table_1_27 <= write_way & _GEN_54 | dirty_table_1_27;
        dirty_table_1_28 <= write_way & _GEN_55 | dirty_table_1_28;
        dirty_table_1_29 <= write_way & _GEN_56 | dirty_table_1_29;
        dirty_table_1_30 <= write_way & _GEN_57 | dirty_table_1_30;
        dirty_table_1_31 <= write_way & (&(paddr_reg_TC_MEM[9:5])) | dirty_table_1_31;
      end
      else begin
        dirty_table_0_0 <= ~(dirty_clean & ~_GEN_0 & _GEN_27) & dirty_table_0_0;
        dirty_table_0_1 <= ~(dirty_clean & ~_GEN_0 & _GEN_28) & dirty_table_0_1;
        dirty_table_0_2 <= ~(dirty_clean & ~_GEN_0 & _GEN_29) & dirty_table_0_2;
        dirty_table_0_3 <= ~(dirty_clean & ~_GEN_0 & _GEN_30) & dirty_table_0_3;
        dirty_table_0_4 <= ~(dirty_clean & ~_GEN_0 & _GEN_31) & dirty_table_0_4;
        dirty_table_0_5 <= ~(dirty_clean & ~_GEN_0 & _GEN_32) & dirty_table_0_5;
        dirty_table_0_6 <= ~(dirty_clean & ~_GEN_0 & _GEN_33) & dirty_table_0_6;
        dirty_table_0_7 <= ~(dirty_clean & ~_GEN_0 & _GEN_34) & dirty_table_0_7;
        dirty_table_0_8 <= ~(dirty_clean & ~_GEN_0 & _GEN_35) & dirty_table_0_8;
        dirty_table_0_9 <= ~(dirty_clean & ~_GEN_0 & _GEN_36) & dirty_table_0_9;
        dirty_table_0_10 <= ~(dirty_clean & ~_GEN_0 & _GEN_37) & dirty_table_0_10;
        dirty_table_0_11 <= ~(dirty_clean & ~_GEN_0 & _GEN_38) & dirty_table_0_11;
        dirty_table_0_12 <= ~(dirty_clean & ~_GEN_0 & _GEN_39) & dirty_table_0_12;
        dirty_table_0_13 <= ~(dirty_clean & ~_GEN_0 & _GEN_40) & dirty_table_0_13;
        dirty_table_0_14 <= ~(dirty_clean & ~_GEN_0 & _GEN_41) & dirty_table_0_14;
        dirty_table_0_15 <= ~(dirty_clean & ~_GEN_0 & _GEN_42) & dirty_table_0_15;
        dirty_table_0_16 <= ~(dirty_clean & ~_GEN_0 & _GEN_43) & dirty_table_0_16;
        dirty_table_0_17 <= ~(dirty_clean & ~_GEN_0 & _GEN_44) & dirty_table_0_17;
        dirty_table_0_18 <= ~(dirty_clean & ~_GEN_0 & _GEN_45) & dirty_table_0_18;
        dirty_table_0_19 <= ~(dirty_clean & ~_GEN_0 & _GEN_46) & dirty_table_0_19;
        dirty_table_0_20 <= ~(dirty_clean & ~_GEN_0 & _GEN_47) & dirty_table_0_20;
        dirty_table_0_21 <= ~(dirty_clean & ~_GEN_0 & _GEN_48) & dirty_table_0_21;
        dirty_table_0_22 <= ~(dirty_clean & ~_GEN_0 & _GEN_49) & dirty_table_0_22;
        dirty_table_0_23 <= ~(dirty_clean & ~_GEN_0 & _GEN_50) & dirty_table_0_23;
        dirty_table_0_24 <= ~(dirty_clean & ~_GEN_0 & _GEN_51) & dirty_table_0_24;
        dirty_table_0_25 <= ~(dirty_clean & ~_GEN_0 & _GEN_52) & dirty_table_0_25;
        dirty_table_0_26 <= ~(dirty_clean & ~_GEN_0 & _GEN_53) & dirty_table_0_26;
        dirty_table_0_27 <= ~(dirty_clean & ~_GEN_0 & _GEN_54) & dirty_table_0_27;
        dirty_table_0_28 <= ~(dirty_clean & ~_GEN_0 & _GEN_55) & dirty_table_0_28;
        dirty_table_0_29 <= ~(dirty_clean & ~_GEN_0 & _GEN_56) & dirty_table_0_29;
        dirty_table_0_30 <= ~(dirty_clean & ~_GEN_0 & _GEN_57) & dirty_table_0_30;
        dirty_table_0_31 <=
          ~(dirty_clean & ~_GEN_0 & (&(paddr_reg_TC_MEM[9:5]))) & dirty_table_0_31;
        dirty_table_1_0 <= ~(dirty_clean & _GEN_0 & _GEN_27) & dirty_table_1_0;
        dirty_table_1_1 <= ~(dirty_clean & _GEN_0 & _GEN_28) & dirty_table_1_1;
        dirty_table_1_2 <= ~(dirty_clean & _GEN_0 & _GEN_29) & dirty_table_1_2;
        dirty_table_1_3 <= ~(dirty_clean & _GEN_0 & _GEN_30) & dirty_table_1_3;
        dirty_table_1_4 <= ~(dirty_clean & _GEN_0 & _GEN_31) & dirty_table_1_4;
        dirty_table_1_5 <= ~(dirty_clean & _GEN_0 & _GEN_32) & dirty_table_1_5;
        dirty_table_1_6 <= ~(dirty_clean & _GEN_0 & _GEN_33) & dirty_table_1_6;
        dirty_table_1_7 <= ~(dirty_clean & _GEN_0 & _GEN_34) & dirty_table_1_7;
        dirty_table_1_8 <= ~(dirty_clean & _GEN_0 & _GEN_35) & dirty_table_1_8;
        dirty_table_1_9 <= ~(dirty_clean & _GEN_0 & _GEN_36) & dirty_table_1_9;
        dirty_table_1_10 <= ~(dirty_clean & _GEN_0 & _GEN_37) & dirty_table_1_10;
        dirty_table_1_11 <= ~(dirty_clean & _GEN_0 & _GEN_38) & dirty_table_1_11;
        dirty_table_1_12 <= ~(dirty_clean & _GEN_0 & _GEN_39) & dirty_table_1_12;
        dirty_table_1_13 <= ~(dirty_clean & _GEN_0 & _GEN_40) & dirty_table_1_13;
        dirty_table_1_14 <= ~(dirty_clean & _GEN_0 & _GEN_41) & dirty_table_1_14;
        dirty_table_1_15 <= ~(dirty_clean & _GEN_0 & _GEN_42) & dirty_table_1_15;
        dirty_table_1_16 <= ~(dirty_clean & _GEN_0 & _GEN_43) & dirty_table_1_16;
        dirty_table_1_17 <= ~(dirty_clean & _GEN_0 & _GEN_44) & dirty_table_1_17;
        dirty_table_1_18 <= ~(dirty_clean & _GEN_0 & _GEN_45) & dirty_table_1_18;
        dirty_table_1_19 <= ~(dirty_clean & _GEN_0 & _GEN_46) & dirty_table_1_19;
        dirty_table_1_20 <= ~(dirty_clean & _GEN_0 & _GEN_47) & dirty_table_1_20;
        dirty_table_1_21 <= ~(dirty_clean & _GEN_0 & _GEN_48) & dirty_table_1_21;
        dirty_table_1_22 <= ~(dirty_clean & _GEN_0 & _GEN_49) & dirty_table_1_22;
        dirty_table_1_23 <= ~(dirty_clean & _GEN_0 & _GEN_50) & dirty_table_1_23;
        dirty_table_1_24 <= ~(dirty_clean & _GEN_0 & _GEN_51) & dirty_table_1_24;
        dirty_table_1_25 <= ~(dirty_clean & _GEN_0 & _GEN_52) & dirty_table_1_25;
        dirty_table_1_26 <= ~(dirty_clean & _GEN_0 & _GEN_53) & dirty_table_1_26;
        dirty_table_1_27 <= ~(dirty_clean & _GEN_0 & _GEN_54) & dirty_table_1_27;
        dirty_table_1_28 <= ~(dirty_clean & _GEN_0 & _GEN_55) & dirty_table_1_28;
        dirty_table_1_29 <= ~(dirty_clean & _GEN_0 & _GEN_56) & dirty_table_1_29;
        dirty_table_1_30 <= ~(dirty_clean & _GEN_0 & _GEN_57) & dirty_table_1_30;
        dirty_table_1_31 <=
          ~(dirty_clean & _GEN_0 & (&(paddr_reg_TC_MEM[9:5]))) & dirty_table_1_31;
      end
      if (wbuf_we)
        wrt_buf <= cacop_en_reg_TC_MEM ? {_GEN_26, paddr_reg_TC_MEM} : _GEN_25;
      else if (io_d_wready & d_wvalid)
        wrt_buf <= {32'h0, wrt_buf[287:64], wrt_buf[31:0]};
      state <= _GEN_65[state];
      if (_GEN_21 & wfsm_en)
        wrt_count <= io_d_wlen_0;
      else if (d_wvalid & io_d_wready)
        wrt_count <= 8'(wrt_count - 8'h1);
      wrt_state <= _GEN_70[wrt_state];
    end
  end // always @(posedge)
  assign _xilinx_simple_dual_port_1_clock_ram_write_first_addra = paddr_reg_TC_MEM[9:5];
  assign _xilinx_simple_dual_port_1_clock_ram_write_first_wea =
    ~_GEN_13 & _GEN_12 & ~tag_idx;
  xilinx_simple_dual_port_1_clock_ram_write_first #(
    .RAM_DEPTH(32),
    .RAM_WIDTH(23)
  ) xilinx_simple_dual_port_1_clock_ram_write_first (
    .addra (_xilinx_simple_dual_port_1_clock_ram_write_first_addra),
    .addrb (tag_addrb_0),
    .dina  (tag_dina_0),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_write_first_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_write_first_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_write_first_1_addra = paddr_reg_TC_MEM[9:5];
  assign _xilinx_simple_dual_port_1_clock_ram_write_first_1_wea =
    ~_GEN_13 & _GEN_12 & tag_idx;
  xilinx_simple_dual_port_1_clock_ram_write_first #(
    .RAM_DEPTH(32),
    .RAM_WIDTH(23)
  ) xilinx_simple_dual_port_1_clock_ram_write_first_1 (
    .addra (_xilinx_simple_dual_port_1_clock_ram_write_first_1_addra),
    .addrb (tag_addrb_1),
    .dina  (tag_dina_1),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_write_first_1_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_write_first_1_doutb)
  );
  assign _xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_addra =
    paddr_reg_TC_MEM[9:5];
  xilinx_simple_dual_port_byte_write_1_clock_ram_read_first #(
    .COL_WIDTH(8),
    .NB_COL(32),
    .RAM_DEPTH(32)
  ) xilinx_simple_dual_port_byte_write_1_clock_ram_read_first (
    .addra (_xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_addra),
    .addrb (cmem_addrb_0),
    .dina  (cmem_dina_0),
    .clka  (clock),
    .wea   (cmem_we_0),
    .doutb (_xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_doutb)
  );
  assign _xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_1_addra =
    paddr_reg_TC_MEM[9:5];
  xilinx_simple_dual_port_byte_write_1_clock_ram_read_first #(
    .COL_WIDTH(8),
    .NB_COL(32),
    .RAM_DEPTH(32)
  ) xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_1 (
    .addra (_xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_1_addra),
    .addrb (cmem_addrb_1),
    .dina  (cmem_dina_0),
    .clka  (clock),
    .wea   (cmem_we_1),
    .doutb (_xilinx_simple_dual_port_byte_write_1_clock_ram_read_first_1_doutb)
  );
  assign io_rdata_MEM = rdata_temp & rmask;
  assign io_d_rvalid = ~_GEN_6 & _GEN_11;
  assign io_d_raddr =
    uncache_reg_TC_MEM ? paddr_reg_TC_MEM : {paddr_reg_TC_MEM[31:5], 5'h0};
  assign io_d_rsize = {1'h0, _io_d_rsize_T_1};
  assign io_d_rlen = io_d_wlen_0;
  assign io_d_waddr = wrt_buf[31:0];
  assign io_d_wdata = wrt_buf[63:32];
  assign io_d_wlen = io_d_wlen_0;
  assign io_d_wsize = {1'h0, _io_d_wsize_T_1};
  assign io_d_wmask = uncache_reg_TC_MEM ? 4'(_io_d_wmask_T_2[3:0] - 4'h1) : 4'hF;
  assign io_d_wvalid = d_wvalid;
  assign io_d_wlast = ~_GEN_21 & _GEN_22 & wrt_count == 8'h0;
  assign io_d_bready = ~_GEN_21 & _GEN_22;
  assign io_cache_miss = cache_miss_MEM;
endmodule

