// Generated by CIRCT firtool-1.62.0
module Dispatch(
  input        io_inst_pack_inst_valid_0,
               io_inst_pack_inst_valid_1,
  input  [2:0] io_inst_pack_ins_type_0,
               io_inst_pack_ins_type_1,
               io_elem_0,
               io_elem_1,
  output       io_inst_valid_0_0,
               io_inst_valid_0_1,
               io_inst_valid_1_0,
               io_inst_valid_1_1,
               io_inst_valid_2_0,
               io_inst_valid_2_1,
               io_inst_valid_3_0,
               io_inst_valid_3_1
);

  wire       _queue_hit_1_T_1 = io_elem_0 <= io_elem_1;
  wire [1:0] _queue_hit_0_T_2 = _queue_hit_1_T_1 ? 2'h1 : 2'h2;
  wire [1:0] _queue_hit_0_T_4 =
    io_inst_pack_ins_type_0[2] ? _queue_hit_0_T_2 : io_inst_pack_ins_type_0[1:0];
  wire [3:0] queue_hit_0 = 4'h1 << _queue_hit_0_T_4 & {4{io_inst_pack_inst_valid_0}};
  wire [1:0] _queue_hit_1_T_2 = _queue_hit_1_T_1 ? 2'h1 : 2'h2;
  wire [1:0] _queue_hit_1_T_4 =
    io_inst_pack_ins_type_1[2] ? _queue_hit_1_T_2 : io_inst_pack_ins_type_1[1:0];
  wire [3:0] queue_hit_1 = 4'h1 << _queue_hit_1_T_4 & {4{io_inst_pack_inst_valid_1}};
  assign io_inst_valid_0_0 = queue_hit_0[0];
  assign io_inst_valid_0_1 = queue_hit_1[0];
  assign io_inst_valid_1_0 = queue_hit_0[1];
  assign io_inst_valid_1_1 = queue_hit_1[1];
  assign io_inst_valid_2_0 = queue_hit_0[2];
  assign io_inst_valid_2_1 = queue_hit_1[2];
  assign io_inst_valid_3_0 = queue_hit_0[3];
  assign io_inst_valid_3_1 = queue_hit_1[3];
endmodule

