// Generated by CIRCT firtool-1.62.0
module MDU(
  input         clock,
                reset,
  input  [31:0] io_src1,
                io_src2,
  output [31:0] io_mul_res,
                io_div_res,
  input  [3:0]  io_op,
  output        io_busy,
  input         io_inst_valid
);

  wire _div_io_busy;
  wire _mul_io_busy;
  assign _mul_io_busy = _div_io_busy;
  multiplier mul (
    .clock   (clock),
    .reset   (reset),
    .io_src1 (io_src1),
    .io_src2 (io_src2),
    .io_res  (io_mul_res),
    .io_op   (io_op),
    .io_busy (_mul_io_busy)
  );
  divider div (
    .clock         (clock),
    .reset         (reset),
    .io_src1       (io_src1),
    .io_src2       (io_src2),
    .io_op         (io_op),
    .io_res        (io_div_res),
    .io_inst_valid (io_inst_valid),
    .io_busy       (_div_io_busy)
  );
  assign io_busy = _div_io_busy;
endmodule

