// Generated by CIRCT firtool-1.62.0
module Predict(
  input         clock,
                reset,
  input  [31:0] io_pc,
                io_npc,
  output        io_pred_jump_0,
                io_pred_jump_1,
                io_pred_valid_0,
                io_pred_valid_1,
  output [31:0] io_pred_npc,
  output [1:0]  io_br_cnt_0,
                io_br_cnt_1,
  input         io_real_jump,
  input  [31:0] io_branch_target,
  input         io_update_en,
  input  [1:0]  io_br_type,
                io_cmt_br_cnt,
  input  [2:0]  io_top_arch,
  input  [31:0] io_ras_arch_0,
                io_ras_arch_1,
                io_ras_arch_2,
                io_ras_arch_3,
                io_ras_arch_4,
                io_ras_arch_5,
                io_ras_arch_6,
                io_ras_arch_7,
  input         io_predict_fail,
  input  [7:0]  io_ghr_arch,
  input         io_pd_fix_en,
                io_pd_fix_is_bl,
  input  [31:0] io_pd_fix_pc
);

  wire [7:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_5_addra;
  wire [7:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_5_addrb;
  wire [31:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_5_dina;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_5_wea;
  wire [31:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_5_doutb;
  wire [7:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_4_addra;
  wire [7:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_4_addrb;
  wire [31:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_4_dina;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_4_wea;
  wire [31:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_4_doutb;
  wire [7:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_3_addra;
  wire [7:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_3_addrb;
  wire [20:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_3_dina;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_3_wea;
  wire [20:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_3_doutb;
  wire [7:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_2_addra;
  wire [7:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_2_addrb;
  wire [20:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_2_dina;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_2_wea;
  wire [20:0]      _xilinx_simple_dual_port_1_clock_ram_read_first_2_doutb;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_1_wea;
  wire [1:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_1_doutb;
  wire             _xilinx_simple_dual_port_1_clock_ram_read_first_wea;
  wire [1:0]       _xilinx_simple_dual_port_1_clock_ram_read_first_doutb;
  reg  [7:0]       ghr;
  wire [11:0]      pht_rindex = {ghr ^ io_npc[14:7], io_npc[6:3]};
  wire [11:0]      pht_windex = {ghr ^ io_pc[14:7], io_pc[6:3]};
  wire [1:0]       pht_wdata =
    io_real_jump
      ? 2'(io_cmt_br_cnt + {1'h0, io_cmt_br_cnt != 2'h3})
      : 2'(io_cmt_br_cnt - {1'h0, |io_cmt_br_cnt});
  wire             pred_valid_0 =
    _xilinx_simple_dual_port_1_clock_ram_read_first_2_doutb[20]
    & (_xilinx_simple_dual_port_1_clock_ram_read_first_2_doutb[19:0]
       ^ io_pc[31:12]) == 20'h0 & ~(io_pc[2]);
  wire             pred_valid_1 =
    _xilinx_simple_dual_port_1_clock_ram_read_first_3_doutb[20]
    & (_xilinx_simple_dual_port_1_clock_ram_read_first_3_doutb[19:0]
       ^ io_pc[31:12]) == 20'h0;
  wire             pred_jump_0 =
    pred_valid_0 & _xilinx_simple_dual_port_1_clock_ram_read_first_doutb[1];
  wire             pred_jump_1 =
    pred_valid_1 & _xilinx_simple_dual_port_1_clock_ram_read_first_1_doutb[1];
  reg  [31:0]      ras_0;
  reg  [31:0]      ras_1;
  reg  [31:0]      ras_2;
  reg  [31:0]      ras_3;
  reg  [31:0]      ras_4;
  reg  [31:0]      ras_5;
  reg  [31:0]      ras_6;
  reg  [31:0]      ras_7;
  reg  [2:0]       top;
  wire [1:0]       _GEN =
    pred_jump_0
      ? _xilinx_simple_dual_port_1_clock_ram_read_first_4_doutb[1:0]
      : _xilinx_simple_dual_port_1_clock_ram_read_first_5_doutb[1:0];
  wire [29:0]      _GEN_0 =
    pred_jump_0
      ? _xilinx_simple_dual_port_1_clock_ram_read_first_4_doutb[31:2]
      : _xilinx_simple_dual_port_1_clock_ram_read_first_5_doutb[31:2];
  wire [7:0][31:0] _GEN_1 =
    {{ras_7}, {ras_6}, {ras_5}, {ras_4}, {ras_3}, {ras_2}, {ras_1}, {ras_0}};
  wire [2:0]       _top_T = 3'(top + 3'h1);
  wire             _GEN_2 = pred_jump_0 ? pred_valid_0 : pred_valid_1;
  wire             _GEN_3 = _GEN[1] & _GEN_2;
  wire [2:0]       _top_T_2 = 3'(top + 3'h1);
  wire [31:0]      _ras_T_2 = {io_pc[31:3], ~pred_jump_0, 2'h0};
  wire [1:0]       _jump_T = {pred_valid_1, pred_valid_0};
  always @(posedge clock) begin
    if (reset) begin
      ghr <= 8'h0;
      ras_0 <= 32'h1C000000;
      ras_1 <= 32'h1C000000;
      ras_2 <= 32'h1C000000;
      ras_3 <= 32'h1C000000;
      ras_4 <= 32'h1C000000;
      ras_5 <= 32'h1C000000;
      ras_6 <= 32'h1C000000;
      ras_7 <= 32'h1C000000;
      top <= 3'h7;
    end
    else if (io_predict_fail) begin
      ghr <= io_ghr_arch;
      ras_0 <= io_ras_arch_0;
      ras_1 <= io_ras_arch_1;
      ras_2 <= io_ras_arch_2;
      ras_3 <= io_ras_arch_3;
      ras_4 <= io_ras_arch_4;
      ras_5 <= io_ras_arch_5;
      ras_6 <= io_ras_arch_6;
      ras_7 <= io_ras_arch_7;
      top <= io_top_arch;
    end
    else begin
      if ((|_jump_T) & ~io_pd_fix_en)
        ghr <= {ghr[6:0], |(_jump_T & {pred_jump_1, pred_jump_0})};
      if (io_pd_fix_en & io_pd_fix_is_bl) begin
        if (_top_T == 3'h0)
          ras_0 <= io_pd_fix_pc;
        if (_top_T == 3'h1)
          ras_1 <= io_pd_fix_pc;
        if (_top_T == 3'h2)
          ras_2 <= io_pd_fix_pc;
        if (_top_T == 3'h3)
          ras_3 <= io_pd_fix_pc;
        if (_top_T == 3'h4)
          ras_4 <= io_pd_fix_pc;
        if (_top_T == 3'h5)
          ras_5 <= io_pd_fix_pc;
        if (_top_T == 3'h6)
          ras_6 <= io_pd_fix_pc;
        if (&_top_T)
          ras_7 <= io_pd_fix_pc;
        top <= _top_T;
      end
      else begin
        if (_GEN_3 & _top_T_2 == 3'h0)
          ras_0 <= _ras_T_2;
        if (_GEN_3 & _top_T_2 == 3'h1)
          ras_1 <= _ras_T_2;
        if (_GEN_3 & _top_T_2 == 3'h2)
          ras_2 <= _ras_T_2;
        if (_GEN_3 & _top_T_2 == 3'h3)
          ras_3 <= _ras_T_2;
        if (_GEN_3 & _top_T_2 == 3'h4)
          ras_4 <= _ras_T_2;
        if (_GEN_3 & _top_T_2 == 3'h5)
          ras_5 <= _ras_T_2;
        if (_GEN_3 & _top_T_2 == 3'h6)
          ras_6 <= _ras_T_2;
        if (_GEN_3 & (&_top_T_2))
          ras_7 <= _ras_T_2;
        if (_GEN_3)
          top <= _top_T_2;
        else if (_GEN == 2'h1 & _GEN_2)
          top <= 3'(top - 3'h1);
      end
    end
  end // always @(posedge)
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_wea = io_update_en & ~(io_pc[2]);
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(4096),
    .RAM_WIDTH(2)
  ) xilinx_simple_dual_port_1_clock_ram_read_first (
    .addra (pht_windex),
    .addrb (pht_rindex),
    .dina  (pht_wdata),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_1_wea = io_update_en & io_pc[2];
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(4096),
    .RAM_WIDTH(2)
  ) xilinx_simple_dual_port_1_clock_ram_read_first_1 (
    .addra (pht_windex),
    .addrb (pht_rindex),
    .dina  (pht_wdata),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_1_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_1_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_2_addra = io_pc[10:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_2_addrb = io_npc[10:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_2_dina = {1'h1, io_pc[31:12]};
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_2_wea =
    io_update_en & ~(io_pc[2]);
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(256),
    .RAM_WIDTH(21)
  ) xilinx_simple_dual_port_1_clock_ram_read_first_2 (
    .addra (_xilinx_simple_dual_port_1_clock_ram_read_first_2_addra),
    .addrb (_xilinx_simple_dual_port_1_clock_ram_read_first_2_addrb),
    .dina  (_xilinx_simple_dual_port_1_clock_ram_read_first_2_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_2_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_2_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_3_addra = io_pc[10:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_3_addrb = io_npc[10:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_3_dina = {1'h1, io_pc[31:12]};
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_3_wea = io_update_en & io_pc[2];
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(256),
    .RAM_WIDTH(21)
  ) xilinx_simple_dual_port_1_clock_ram_read_first_3 (
    .addra (_xilinx_simple_dual_port_1_clock_ram_read_first_3_addra),
    .addrb (_xilinx_simple_dual_port_1_clock_ram_read_first_3_addrb),
    .dina  (_xilinx_simple_dual_port_1_clock_ram_read_first_3_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_3_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_3_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_4_addra = io_pc[10:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_4_addrb = io_npc[10:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_4_dina =
    {io_branch_target[31:2], io_br_type};
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_4_wea =
    io_update_en & ~(io_pc[2]);
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(256),
    .RAM_WIDTH(32)
  ) xilinx_simple_dual_port_1_clock_ram_read_first_4 (
    .addra (_xilinx_simple_dual_port_1_clock_ram_read_first_4_addra),
    .addrb (_xilinx_simple_dual_port_1_clock_ram_read_first_4_addrb),
    .dina  (_xilinx_simple_dual_port_1_clock_ram_read_first_4_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_4_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_4_doutb)
  );
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_5_addra = io_pc[10:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_5_addrb = io_npc[10:3];
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_5_dina =
    {io_branch_target[31:2], io_br_type};
  assign _xilinx_simple_dual_port_1_clock_ram_read_first_5_wea = io_update_en & io_pc[2];
  xilinx_simple_dual_port_1_clock_ram_read_first #(
    .RAM_DEPTH(256),
    .RAM_WIDTH(32)
  ) xilinx_simple_dual_port_1_clock_ram_read_first_5 (
    .addra (_xilinx_simple_dual_port_1_clock_ram_read_first_5_addra),
    .addrb (_xilinx_simple_dual_port_1_clock_ram_read_first_5_addrb),
    .dina  (_xilinx_simple_dual_port_1_clock_ram_read_first_5_dina),
    .clka  (clock),
    .wea   (_xilinx_simple_dual_port_1_clock_ram_read_first_5_wea),
    .doutb (_xilinx_simple_dual_port_1_clock_ram_read_first_5_doutb)
  );
  assign io_pred_jump_0 = io_pc[2] ? pred_jump_1 : pred_jump_0;
  assign io_pred_jump_1 = pred_jump_1;
  assign io_pred_valid_0 = io_pc[2] ? pred_valid_1 : pred_valid_0;
  assign io_pred_valid_1 = pred_valid_1;
  assign io_pred_npc =
    _GEN == 2'h1 ? 32'(_GEN_1[3'(top - 3'h1)] + 32'h4) : {_GEN_0, 2'h0};
  assign io_br_cnt_0 = _xilinx_simple_dual_port_1_clock_ram_read_first_doutb;
  assign io_br_cnt_1 = _xilinx_simple_dual_port_1_clock_ram_read_first_1_doutb;
endmodule

