// Generated by CIRCT firtool-1.62.0
module RegFile(
  input         clock,
                reset,
  input  [5:0]  io_prj_0,
                io_prj_1,
                io_prj_2,
                io_prj_3,
                io_prk_0,
                io_prk_1,
                io_prk_2,
                io_prk_3,
  output [31:0] io_prj_data_0,
                io_prj_data_1,
                io_prj_data_2,
                io_prj_data_3,
                io_prk_data_0,
                io_prk_data_1,
                io_prk_data_2,
                io_prk_data_3,
  input  [5:0]  io_prd_0,
                io_prd_1,
                io_prd_2,
                io_prd_3,
  input  [31:0] io_wdata_0,
                io_wdata_1,
                io_wdata_2,
                io_wdata_3,
  input         io_we_0,
                io_we_1,
                io_we_2,
                io_we_3
);

  reg  [31:0]       rf_0;
  reg  [31:0]       rf_1;
  reg  [31:0]       rf_2;
  reg  [31:0]       rf_3;
  reg  [31:0]       rf_4;
  reg  [31:0]       rf_5;
  reg  [31:0]       rf_6;
  reg  [31:0]       rf_7;
  reg  [31:0]       rf_8;
  reg  [31:0]       rf_9;
  reg  [31:0]       rf_10;
  reg  [31:0]       rf_11;
  reg  [31:0]       rf_12;
  reg  [31:0]       rf_13;
  reg  [31:0]       rf_14;
  reg  [31:0]       rf_15;
  reg  [31:0]       rf_16;
  reg  [31:0]       rf_17;
  reg  [31:0]       rf_18;
  reg  [31:0]       rf_19;
  reg  [31:0]       rf_20;
  reg  [31:0]       rf_21;
  reg  [31:0]       rf_22;
  reg  [31:0]       rf_23;
  reg  [31:0]       rf_24;
  reg  [31:0]       rf_25;
  reg  [31:0]       rf_26;
  reg  [31:0]       rf_27;
  reg  [31:0]       rf_28;
  reg  [31:0]       rf_29;
  reg  [31:0]       rf_30;
  reg  [31:0]       rf_31;
  reg  [31:0]       rf_32;
  reg  [31:0]       rf_33;
  reg  [31:0]       rf_34;
  reg  [31:0]       rf_35;
  reg  [31:0]       rf_36;
  reg  [31:0]       rf_37;
  reg  [31:0]       rf_38;
  reg  [31:0]       rf_39;
  reg  [31:0]       rf_40;
  reg  [31:0]       rf_41;
  reg  [31:0]       rf_42;
  reg  [31:0]       rf_43;
  reg  [31:0]       rf_44;
  reg  [31:0]       rf_45;
  reg  [31:0]       rf_46;
  reg  [31:0]       rf_47;
  reg  [31:0]       rf_48;
  reg  [31:0]       rf_49;
  reg  [31:0]       rf_50;
  reg  [31:0]       rf_51;
  reg  [31:0]       rf_52;
  reg  [31:0]       rf_53;
  wire              we_0 = io_we_0 & (|io_prd_0);
  wire              we_1 = io_we_1 & (|io_prd_1);
  wire              we_2 = io_we_2 & (|io_prd_2);
  wire              we_3 = io_we_3 & (|io_prd_3);
  wire              _w_hit_T_1 = we_0 & io_prd_0 == io_prj_0;
  wire              _w_hit_T_3 = we_1 & io_prd_1 == io_prj_0;
  wire              _w_hit_T_5 = we_2 & io_prd_2 == io_prj_0;
  wire              _w_hit_T_7 = we_3 & io_prd_3 == io_prj_0;
  wire [31:0]       _io_prj_data_0_T_5 = _w_hit_T_1 ? io_wdata_0 : 32'h0;
  wire [31:0]       _io_prj_data_0_T_6 = _w_hit_T_3 ? io_wdata_1 : 32'h0;
  wire [31:0]       _io_prj_data_0_T_7 = _w_hit_T_5 ? io_wdata_2 : 32'h0;
  wire [31:0]       _io_prj_data_0_T_8 = _w_hit_T_7 ? io_wdata_3 : 32'h0;
  wire [63:0][31:0] _GEN =
    {{rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_53},
     {rf_52},
     {rf_51},
     {rf_50},
     {rf_49},
     {rf_48},
     {rf_47},
     {rf_46},
     {rf_45},
     {rf_44},
     {rf_43},
     {rf_42},
     {rf_41},
     {rf_40},
     {rf_39},
     {rf_38},
     {rf_37},
     {rf_36},
     {rf_35},
     {rf_34},
     {rf_33},
     {rf_32},
     {rf_31},
     {rf_30},
     {rf_29},
     {rf_28},
     {rf_27},
     {rf_26},
     {rf_25},
     {rf_24},
     {rf_23},
     {rf_22},
     {rf_21},
     {rf_20},
     {rf_19},
     {rf_18},
     {rf_17},
     {rf_16},
     {rf_15},
     {rf_14},
     {rf_13},
     {rf_12},
     {rf_11},
     {rf_10},
     {rf_9},
     {rf_8},
     {rf_7},
     {rf_6},
     {rf_5},
     {rf_4},
     {rf_3},
     {rf_2},
     {rf_1},
     {rf_0}};
  wire              _w_hit_T_9 = we_0 & io_prd_0 == io_prk_0;
  wire              _w_hit_T_11 = we_1 & io_prd_1 == io_prk_0;
  wire              _w_hit_T_13 = we_2 & io_prd_2 == io_prk_0;
  wire              _w_hit_T_15 = we_3 & io_prd_3 == io_prk_0;
  wire [31:0]       _io_prk_data_0_T_5 = _w_hit_T_9 ? io_wdata_0 : 32'h0;
  wire [31:0]       _io_prk_data_0_T_6 = _w_hit_T_11 ? io_wdata_1 : 32'h0;
  wire [31:0]       _io_prk_data_0_T_7 = _w_hit_T_13 ? io_wdata_2 : 32'h0;
  wire [31:0]       _io_prk_data_0_T_8 = _w_hit_T_15 ? io_wdata_3 : 32'h0;
  wire              _w_hit_T_17 = we_0 & io_prd_0 == io_prj_1;
  wire              _w_hit_T_19 = we_1 & io_prd_1 == io_prj_1;
  wire              _w_hit_T_21 = we_2 & io_prd_2 == io_prj_1;
  wire              _w_hit_T_23 = we_3 & io_prd_3 == io_prj_1;
  wire [31:0]       _io_prj_data_1_T_5 = _w_hit_T_17 ? io_wdata_0 : 32'h0;
  wire [31:0]       _io_prj_data_1_T_6 = _w_hit_T_19 ? io_wdata_1 : 32'h0;
  wire [31:0]       _io_prj_data_1_T_7 = _w_hit_T_21 ? io_wdata_2 : 32'h0;
  wire [31:0]       _io_prj_data_1_T_8 = _w_hit_T_23 ? io_wdata_3 : 32'h0;
  wire              _w_hit_T_25 = we_0 & io_prd_0 == io_prk_1;
  wire              _w_hit_T_27 = we_1 & io_prd_1 == io_prk_1;
  wire              _w_hit_T_29 = we_2 & io_prd_2 == io_prk_1;
  wire              _w_hit_T_31 = we_3 & io_prd_3 == io_prk_1;
  wire [31:0]       _io_prk_data_1_T_5 = _w_hit_T_25 ? io_wdata_0 : 32'h0;
  wire [31:0]       _io_prk_data_1_T_6 = _w_hit_T_27 ? io_wdata_1 : 32'h0;
  wire [31:0]       _io_prk_data_1_T_7 = _w_hit_T_29 ? io_wdata_2 : 32'h0;
  wire [31:0]       _io_prk_data_1_T_8 = _w_hit_T_31 ? io_wdata_3 : 32'h0;
  wire              _w_hit_T_33 = we_0 & io_prd_0 == io_prj_2;
  wire              _w_hit_T_35 = we_1 & io_prd_1 == io_prj_2;
  wire              _w_hit_T_37 = we_2 & io_prd_2 == io_prj_2;
  wire              _w_hit_T_39 = we_3 & io_prd_3 == io_prj_2;
  wire [31:0]       _io_prj_data_2_T_5 = _w_hit_T_33 ? io_wdata_0 : 32'h0;
  wire [31:0]       _io_prj_data_2_T_6 = _w_hit_T_35 ? io_wdata_1 : 32'h0;
  wire [31:0]       _io_prj_data_2_T_7 = _w_hit_T_37 ? io_wdata_2 : 32'h0;
  wire [31:0]       _io_prj_data_2_T_8 = _w_hit_T_39 ? io_wdata_3 : 32'h0;
  wire              _w_hit_T_41 = we_0 & io_prd_0 == io_prk_2;
  wire              _w_hit_T_43 = we_1 & io_prd_1 == io_prk_2;
  wire              _w_hit_T_45 = we_2 & io_prd_2 == io_prk_2;
  wire              _w_hit_T_47 = we_3 & io_prd_3 == io_prk_2;
  wire [31:0]       _io_prk_data_2_T_5 = _w_hit_T_41 ? io_wdata_0 : 32'h0;
  wire [31:0]       _io_prk_data_2_T_6 = _w_hit_T_43 ? io_wdata_1 : 32'h0;
  wire [31:0]       _io_prk_data_2_T_7 = _w_hit_T_45 ? io_wdata_2 : 32'h0;
  wire [31:0]       _io_prk_data_2_T_8 = _w_hit_T_47 ? io_wdata_3 : 32'h0;
  wire              _w_hit_T_49 = we_0 & io_prd_0 == io_prj_3;
  wire              _w_hit_T_51 = we_1 & io_prd_1 == io_prj_3;
  wire              _w_hit_T_53 = we_2 & io_prd_2 == io_prj_3;
  wire              _w_hit_T_55 = we_3 & io_prd_3 == io_prj_3;
  wire [31:0]       _io_prj_data_3_T_5 = _w_hit_T_49 ? io_wdata_0 : 32'h0;
  wire [31:0]       _io_prj_data_3_T_6 = _w_hit_T_51 ? io_wdata_1 : 32'h0;
  wire [31:0]       _io_prj_data_3_T_7 = _w_hit_T_53 ? io_wdata_2 : 32'h0;
  wire [31:0]       _io_prj_data_3_T_8 = _w_hit_T_55 ? io_wdata_3 : 32'h0;
  wire              _w_hit_T_57 = we_0 & io_prd_0 == io_prk_3;
  wire              _w_hit_T_59 = we_1 & io_prd_1 == io_prk_3;
  wire              _w_hit_T_61 = we_2 & io_prd_2 == io_prk_3;
  wire              _w_hit_T_63 = we_3 & io_prd_3 == io_prk_3;
  wire [31:0]       _io_prk_data_3_T_5 = _w_hit_T_57 ? io_wdata_0 : 32'h0;
  wire [31:0]       _io_prk_data_3_T_6 = _w_hit_T_59 ? io_wdata_1 : 32'h0;
  wire [31:0]       _io_prk_data_3_T_7 = _w_hit_T_61 ? io_wdata_2 : 32'h0;
  wire [31:0]       _io_prk_data_3_T_8 = _w_hit_T_63 ? io_wdata_3 : 32'h0;
  always @(posedge clock) begin
    if (reset) begin
      rf_0 <= 32'h0;
      rf_1 <= 32'h0;
      rf_2 <= 32'h0;
      rf_3 <= 32'h0;
      rf_4 <= 32'h0;
      rf_5 <= 32'h0;
      rf_6 <= 32'h0;
      rf_7 <= 32'h0;
      rf_8 <= 32'h0;
      rf_9 <= 32'h0;
      rf_10 <= 32'h0;
      rf_11 <= 32'h0;
      rf_12 <= 32'h0;
      rf_13 <= 32'h0;
      rf_14 <= 32'h0;
      rf_15 <= 32'h0;
      rf_16 <= 32'h0;
      rf_17 <= 32'h0;
      rf_18 <= 32'h0;
      rf_19 <= 32'h0;
      rf_20 <= 32'h0;
      rf_21 <= 32'h0;
      rf_22 <= 32'h0;
      rf_23 <= 32'h0;
      rf_24 <= 32'h0;
      rf_25 <= 32'h0;
      rf_26 <= 32'h0;
      rf_27 <= 32'h0;
      rf_28 <= 32'h0;
      rf_29 <= 32'h0;
      rf_30 <= 32'h0;
      rf_31 <= 32'h0;
      rf_32 <= 32'h0;
      rf_33 <= 32'h0;
      rf_34 <= 32'h0;
      rf_35 <= 32'h0;
      rf_36 <= 32'h0;
      rf_37 <= 32'h0;
      rf_38 <= 32'h0;
      rf_39 <= 32'h0;
      rf_40 <= 32'h0;
      rf_41 <= 32'h0;
      rf_42 <= 32'h0;
      rf_43 <= 32'h0;
      rf_44 <= 32'h0;
      rf_45 <= 32'h0;
      rf_46 <= 32'h0;
      rf_47 <= 32'h0;
      rf_48 <= 32'h0;
      rf_49 <= 32'h0;
      rf_50 <= 32'h0;
      rf_51 <= 32'h0;
      rf_52 <= 32'h0;
      rf_53 <= 32'h0;
    end
    else begin
      if (we_3 & io_prd_3 == 6'h0)
        rf_0 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h0)
        rf_0 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h0)
        rf_0 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h0)
        rf_0 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h1)
        rf_1 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h1)
        rf_1 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h1)
        rf_1 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h1)
        rf_1 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h2)
        rf_2 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h2)
        rf_2 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h2)
        rf_2 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h2)
        rf_2 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h3)
        rf_3 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h3)
        rf_3 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h3)
        rf_3 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h3)
        rf_3 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h4)
        rf_4 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h4)
        rf_4 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h4)
        rf_4 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h4)
        rf_4 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h5)
        rf_5 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h5)
        rf_5 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h5)
        rf_5 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h5)
        rf_5 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h6)
        rf_6 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h6)
        rf_6 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h6)
        rf_6 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h6)
        rf_6 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h7)
        rf_7 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h7)
        rf_7 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h7)
        rf_7 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h7)
        rf_7 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h8)
        rf_8 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h8)
        rf_8 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h8)
        rf_8 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h8)
        rf_8 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h9)
        rf_9 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h9)
        rf_9 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h9)
        rf_9 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h9)
        rf_9 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'hA)
        rf_10 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'hA)
        rf_10 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'hA)
        rf_10 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'hA)
        rf_10 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'hB)
        rf_11 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'hB)
        rf_11 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'hB)
        rf_11 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'hB)
        rf_11 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'hC)
        rf_12 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'hC)
        rf_12 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'hC)
        rf_12 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'hC)
        rf_12 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'hD)
        rf_13 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'hD)
        rf_13 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'hD)
        rf_13 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'hD)
        rf_13 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'hE)
        rf_14 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'hE)
        rf_14 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'hE)
        rf_14 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'hE)
        rf_14 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'hF)
        rf_15 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'hF)
        rf_15 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'hF)
        rf_15 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'hF)
        rf_15 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h10)
        rf_16 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h10)
        rf_16 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h10)
        rf_16 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h10)
        rf_16 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h11)
        rf_17 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h11)
        rf_17 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h11)
        rf_17 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h11)
        rf_17 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h12)
        rf_18 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h12)
        rf_18 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h12)
        rf_18 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h12)
        rf_18 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h13)
        rf_19 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h13)
        rf_19 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h13)
        rf_19 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h13)
        rf_19 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h14)
        rf_20 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h14)
        rf_20 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h14)
        rf_20 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h14)
        rf_20 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h15)
        rf_21 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h15)
        rf_21 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h15)
        rf_21 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h15)
        rf_21 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h16)
        rf_22 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h16)
        rf_22 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h16)
        rf_22 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h16)
        rf_22 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h17)
        rf_23 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h17)
        rf_23 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h17)
        rf_23 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h17)
        rf_23 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h18)
        rf_24 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h18)
        rf_24 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h18)
        rf_24 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h18)
        rf_24 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h19)
        rf_25 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h19)
        rf_25 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h19)
        rf_25 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h19)
        rf_25 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h1A)
        rf_26 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h1A)
        rf_26 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h1A)
        rf_26 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h1A)
        rf_26 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h1B)
        rf_27 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h1B)
        rf_27 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h1B)
        rf_27 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h1B)
        rf_27 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h1C)
        rf_28 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h1C)
        rf_28 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h1C)
        rf_28 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h1C)
        rf_28 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h1D)
        rf_29 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h1D)
        rf_29 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h1D)
        rf_29 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h1D)
        rf_29 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h1E)
        rf_30 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h1E)
        rf_30 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h1E)
        rf_30 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h1E)
        rf_30 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h1F)
        rf_31 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h1F)
        rf_31 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h1F)
        rf_31 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h1F)
        rf_31 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h20)
        rf_32 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h20)
        rf_32 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h20)
        rf_32 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h20)
        rf_32 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h21)
        rf_33 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h21)
        rf_33 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h21)
        rf_33 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h21)
        rf_33 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h22)
        rf_34 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h22)
        rf_34 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h22)
        rf_34 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h22)
        rf_34 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h23)
        rf_35 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h23)
        rf_35 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h23)
        rf_35 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h23)
        rf_35 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h24)
        rf_36 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h24)
        rf_36 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h24)
        rf_36 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h24)
        rf_36 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h25)
        rf_37 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h25)
        rf_37 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h25)
        rf_37 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h25)
        rf_37 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h26)
        rf_38 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h26)
        rf_38 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h26)
        rf_38 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h26)
        rf_38 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h27)
        rf_39 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h27)
        rf_39 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h27)
        rf_39 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h27)
        rf_39 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h28)
        rf_40 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h28)
        rf_40 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h28)
        rf_40 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h28)
        rf_40 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h29)
        rf_41 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h29)
        rf_41 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h29)
        rf_41 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h29)
        rf_41 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h2A)
        rf_42 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h2A)
        rf_42 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h2A)
        rf_42 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h2A)
        rf_42 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h2B)
        rf_43 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h2B)
        rf_43 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h2B)
        rf_43 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h2B)
        rf_43 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h2C)
        rf_44 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h2C)
        rf_44 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h2C)
        rf_44 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h2C)
        rf_44 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h2D)
        rf_45 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h2D)
        rf_45 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h2D)
        rf_45 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h2D)
        rf_45 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h2E)
        rf_46 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h2E)
        rf_46 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h2E)
        rf_46 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h2E)
        rf_46 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h2F)
        rf_47 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h2F)
        rf_47 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h2F)
        rf_47 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h2F)
        rf_47 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h30)
        rf_48 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h30)
        rf_48 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h30)
        rf_48 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h30)
        rf_48 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h31)
        rf_49 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h31)
        rf_49 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h31)
        rf_49 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h31)
        rf_49 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h32)
        rf_50 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h32)
        rf_50 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h32)
        rf_50 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h32)
        rf_50 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h33)
        rf_51 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h33)
        rf_51 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h33)
        rf_51 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h33)
        rf_51 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h34)
        rf_52 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h34)
        rf_52 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h34)
        rf_52 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h34)
        rf_52 <= io_wdata_0;
      if (we_3 & io_prd_3 == 6'h35)
        rf_53 <= io_wdata_3;
      else if (we_2 & io_prd_2 == 6'h35)
        rf_53 <= io_wdata_2;
      else if (we_1 & io_prd_1 == 6'h35)
        rf_53 <= io_wdata_1;
      else if (we_0 & io_prd_0 == 6'h35)
        rf_53 <= io_wdata_0;
    end
  end // always @(posedge)
  assign io_prj_data_0 =
    (|{_w_hit_T_7, _w_hit_T_5, _w_hit_T_3, _w_hit_T_1})
      ? _io_prj_data_0_T_5 | _io_prj_data_0_T_6 | _io_prj_data_0_T_7 | _io_prj_data_0_T_8
      : _GEN[io_prj_0];
  assign io_prj_data_1 =
    (|{_w_hit_T_23, _w_hit_T_21, _w_hit_T_19, _w_hit_T_17})
      ? _io_prj_data_1_T_5 | _io_prj_data_1_T_6 | _io_prj_data_1_T_7 | _io_prj_data_1_T_8
      : _GEN[io_prj_1];
  assign io_prj_data_2 =
    (|{_w_hit_T_39, _w_hit_T_37, _w_hit_T_35, _w_hit_T_33})
      ? _io_prj_data_2_T_5 | _io_prj_data_2_T_6 | _io_prj_data_2_T_7 | _io_prj_data_2_T_8
      : _GEN[io_prj_2];
  assign io_prj_data_3 =
    (|{_w_hit_T_55, _w_hit_T_53, _w_hit_T_51, _w_hit_T_49})
      ? _io_prj_data_3_T_5 | _io_prj_data_3_T_6 | _io_prj_data_3_T_7 | _io_prj_data_3_T_8
      : _GEN[io_prj_3];
  assign io_prk_data_0 =
    (|{_w_hit_T_15, _w_hit_T_13, _w_hit_T_11, _w_hit_T_9})
      ? _io_prk_data_0_T_5 | _io_prk_data_0_T_6 | _io_prk_data_0_T_7 | _io_prk_data_0_T_8
      : _GEN[io_prk_0];
  assign io_prk_data_1 =
    (|{_w_hit_T_31, _w_hit_T_29, _w_hit_T_27, _w_hit_T_25})
      ? _io_prk_data_1_T_5 | _io_prk_data_1_T_6 | _io_prk_data_1_T_7 | _io_prk_data_1_T_8
      : _GEN[io_prk_1];
  assign io_prk_data_2 =
    (|{_w_hit_T_47, _w_hit_T_45, _w_hit_T_43, _w_hit_T_41})
      ? _io_prk_data_2_T_5 | _io_prk_data_2_T_6 | _io_prk_data_2_T_7 | _io_prk_data_2_T_8
      : _GEN[io_prk_2];
  assign io_prk_data_3 =
    (|{_w_hit_T_63, _w_hit_T_61, _w_hit_T_59, _w_hit_T_57})
      ? _io_prk_data_3_T_5 | _io_prk_data_3_T_6 | _io_prk_data_3_T_7 | _io_prk_data_3_T_8
      : _GEN[io_prk_3];
endmodule

